### ISSUE TITLE
Regexp comparison by identity is inconsistent with other Ruby implementations

### ISSUE THREAD

**Issue by piotrmurach** [oracle/truffleruby#2851] opened 2023-02-05 14:57 UTC
My [tty-option GitHub CI](https://github.com/piotrmurach/tty-option/actions/runs/4097088247/jobs/7065204769) has failed on `truffleruby-head` when comparing regexp by identity:

```ruby
regexp = /foo/
copy_regexp = regexp.dup
copy_regexp.equal?(regexp) # => true ???
```

On any other Ruby implementation, this is `false`. Is this expected?

Turns out that on `truffleruby 20.1.0` this works as expected. Is this possible regression?

**Comment by eregon** [comment] 2023-02-06 17:02
Hello, thank you for the report.

This is expected, because in TruffleRuby all Regexp instances are immutable and deduplicated.

In CRuby, only Regexp literals are immutable (I'm not sure if deduplicated or not).
In TruffleRuby all Regexp instances are immutable and deduplicated. They are deduplicated because there is no value to have duplicates since they are immutable, it would just increase memory needlessly. And that way they also shared the internal compiled Regexp and its JITed code etc for regexps which happen to be the same.

Is there any need to `.dup` a Regexp in that code?

**Comment by eregon** [comment] 2023-02-06 17:06
I'll close this since this seems expected behavior since (some for CRuby, all for TruffleRuby) Regexp became immutable (needed for Ractor).

**Closed by eregon** 2023-02-06 17:06 UTC
Labels: compatibility

**Comment by piotrmurach** [comment] 2023-02-09 00:21
Thank you for such a swift response and thorough explanation.

The regexes in CRuby and JRuby don't seem to be deduplicated as of the latest releases(I run tests against `jruby-head` and `ruby-head`). Your reasoning behind regexp behaviour makes sense and for whatever it is worth I agree. 

As for the example code, this is what I'd describe as the minimal viable sample that replicates the issue. In my code, what I'm actually doing is deep cloning nested data. One of the nested items is a regexp. This has failed only on the `truffleruby` hence raising this above issue report.

Given all that I wonder what I should do with this behaviour in my tests. Do I add a special case for `truffleruby`? Do I remove regexp from tested types? This is me thinking out loud. Don't feel obliged in any way to answer.
