### ISSUE TITLE
faraday gem test failure: raise 'Parsing should have failed.'

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2424] opened 2021-08-19 19:03 UTC
```
1) Faraday::Response::Json includes the response on the ParsingError instance
     Failure/Error: raise 'Parsing should have failed.'
     
     RuntimeError:
       Parsing should have failed.
     # ./spec/faraday/response/json_spec.rb:80:in `block (2 levels) in <top (required)>'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```
is not happening on MRI ruby 2.7.4

**Comment by nirvdrum** [comment] 2021-09-03 15:51
I cloned the Faraday repo and walked through the test with a debugger to see what was going. The problem is likely in our JSON library. It doesn't fail when parsing only the opening brace for object or array literals.

MRI 2.7.4:

```
❯ ruby -v -r json -e 'puts ::JSON.parse("{").inspect'
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /Users/nirvdrum/.rubies/ruby-2.7.4/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/Users/nirvdrum/.rubies/ruby-2.7.4/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at '{' (JSON::ParserError)

❯ ruby -v -r json -e 'puts ::JSON.parse("[").inspect'
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /Users/nirvdrum/.rubies/ruby-2.7.4/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/Users/nirvdrum/.rubies/ruby-2.7.4/lib/ruby/2.7.0/json/common.rb:156:in `parse': 434: unexpected token at '' (JSON::ParserError)
```

TruffleRuby:

```
❯ jt ruby -v -r json -e 'puts ::JSON.parse("{").inspect'
truffleruby 21.3.0-dev-3ff41798, like ruby 2.7.3, GraalVM CE JVM [x86_64-darwin]
{}

❯ jt ruby -v -r json -e 'puts ::JSON.parse("[").inspect'
truffleruby 21.3.0-dev-3ff41798, like ruby 2.7.3, GraalVM CE JVM [x86_64-darwin]
[]
```

I check if just providing the closing brace induces the same issue. But there, TruffleRuby correctly raises a `JSON::ParserError`:

```
❯ jt ruby -v -r json -e 'puts ::JSON.parse("}").inspect'
truffleruby 21.3.0-dev-3ff41798, like ruby 2.7.3, GraalVM CE JVM [x86_64-darwin]
/Users/nirvdrum/dev/workspaces/truffleruby-ws/graal/sdk/mxbuild/darwin-amd64/GRAALVM_92F985B265_JAVA11/graalvm-92f985b265-java11-21.3.0-dev/Contents/Home/languages/ruby/lib/json/lib/json/pure/parser.rb:121:in `parse': source is not valid JSON! (JSON::ParserError)
	from /Users/nirvdrum/dev/workspaces/truffleruby-ws/graal/sdk/mxbuild/darwin-amd64/GRAALVM_92F985B265_JAVA11/graalvm-92f985b265-java11-21.3.0-dev/Contents/Home/languages/ruby/lib/json/lib/json/common.rb:156:in `parse'
	from -e:1:in `<main>'

❯ jt ruby -v -r json -e 'puts ::JSON.parse("]").inspect'
truffleruby 21.3.0-dev-3ff41798, like ruby 2.7.3, GraalVM CE JVM [x86_64-darwin]
/Users/nirvdrum/dev/workspaces/truffleruby-ws/graal/sdk/mxbuild/darwin-amd64/GRAALVM_92F985B265_JAVA11/graalvm-92f985b265-java11-21.3.0-dev/Contents/Home/languages/ruby/lib/json/lib/json/pure/parser.rb:121:in `parse': source is not valid JSON! (JSON::ParserError)
	from /Users/nirvdrum/dev/workspaces/truffleruby-ws/graal/sdk/mxbuild/darwin-amd64/GRAALVM_92F985B265_JAVA11/graalvm-92f985b265-java11-21.3.0-dev/Contents/Home/languages/ruby/lib/json/lib/json/common.rb:156:in `parse'
	from -e:1:in `<main>'
```

**Comment by bjfish** [comment] 2021-09-03 15:57
@nirvdrum Given these examples, this looks like a duplicate of https://github.com/oracle/truffleruby/issues/1570

**Comment by nirvdrum** [comment] 2021-09-03 16:07
@bjfish Thanks for tracking that down. I thought this looked familiar. I'd say we can close this out as a dupe of the other.

**Comment by bjfish** [comment] 2021-09-03 16:09
Closing this as duplicate of #1570

**Closed by bjfish** 2021-09-03 16:09 UTC
Labels: duplicate
