### ISSUE TITLE
`given block not used` warning from truffleruby-head

### ISSUE THREAD

**Issue by dentarg** [oracle/truffleruby#2859] opened 2023-02-12 20:35 UTC
truffleruby-head

```ruby
$ docker run -it --rm ghcr.io/flavorjones/truffleruby:nightly-slim ruby -v -w -e 'puts ["foo"].map(&:bytesize).reduce(0, :+).to_s'
truffleruby 23.0.0-dev-d28f52ab, like ruby 3.1.3, GraalVM CE Native [x86_64-linux]
-e:1: warning: given block not used
3
```

No warnings:

truffleruby 22.3.1

```ruby
$ docker run --rm -it ghcr.io/graalvm/truffleruby:22.3.1 ruby -v -w -e 'puts ["foo"].map(&:bytesize).reduce(0, :+).to_s'
truffleruby 22.3.1, like ruby 3.0.3, GraalVM CE Native [aarch64-linux]
3
```

CRuby 2.7.7

```ruby
$ ruby -v -w -e 'puts ["foo"].map(&:bytesize).reduce(0, :+).to_s'
ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [arm64-darwin21]
3
```

CRuby 3.2.1

```ruby
$ ruby -v -w -e 'puts ["foo"].map(&:bytesize).reduce(0, :+).to_s'
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin21]
3
```

(the warning [fails the build](https://github.com/sinatra/sinatra/actions/runs/4157866491/jobs/7192670465#step:5:630) in the Sinatra repo)

**Comment by andrykonchin** [comment] 2023-02-13 09:31
Thank you for reporting. I can reproduce the issue.

The issue was introduced recently in https://github.com/oracle/truffleruby/pull/2855.

**Comment by andrykonchin** [comment] 2023-02-13 15:14
Fixed in 34e127f848e43544ae13e8dd75607e879e91a7ec

**Comment by dentarg** [comment] 2023-02-25 19:04
I think this has come back? Reproduces with the nightly built from d1e32dfb

```
docker run -it --rm ghcr.io/flavorjones/truffleruby:nightly-slim bash
```
```
root@5adfac9c5002:/# ruby -v -w -e 'puts ["foo"].map(&:bytesize).reduce(0, :+)'
truffleruby 23.0.0-dev-d1e32dfb, like ruby 3.1.3, GraalVM CE Native [x86_64-linux]
-e:1: warning: given block not used
3
```

**Comment by eregon** [comment] 2023-02-27 16:34
It might be due to https://github.com/oracle/truffleruby/commit/a95249eb65771a62c1d0acc328f2521b11e7916c, I'll take a look.

**Comment by eregon** [comment] 2023-02-27 16:44
FYI we did add a test for no extra warnings in https://github.com/oracle/truffleruby/commit/c0aa65a432d3eb87cbfc95f0e0142e52be5e85f8
But that doesn't run with `$VERBOSE = true` which `-v` and `-w` set, just the default `$VERBOSE = false`.

**Comment by eregon** [comment] 2023-02-27 17:20
https://github.com/oracle/truffleruby/pull/2896 will fix it.

**Closed** 2023-02-27 22:53 UTC
