### ISSUE TITLE
Failing rubocop's cop for grape gem

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2084] opened 2020-08-31 10:40 UTC
For some reason when I ran the grape test suit it fails with 
```
An error occurred while Style/FormatStringToken cop was inspecting /home/travis/build/ruby-grape/grape/lib/grape/exceptions/validation_errors.rb:9:30.
```
but it doesn't for Ruby MRI

The tests are passing btw, but this issue is blocking me from enabling Truffleruby head on grape's CI

Full logs are [here](https://travis-ci.org/github/ruby-grape/grape/jobs/722691736)

**Comment by jaime-rave-conichi** [comment] 2020-08-31 10:51
That might be related to https://github.com/oracle/truffleruby/issues/1913

**Comment by eregon** [comment] 2020-09-01 09:43
I believe this is fixed in [RuboCop 0.90](https://github.com/rubocop-hq/rubocop/releases/tag/v0.90.0) and is a duplicate of https://github.com/oracle/truffleruby/issues/1913.
@gogainda Could you verify it works fine with RuboCop 0.90?

**Closed by eregon** 2020-09-01 09:43 UTC
Labels: duplicate

**Comment by gogainda** [comment] 2020-09-01 10:03
@eregon @jaime-rave-conichi yep, rubocop works fine now
