### ISSUE TITLE
Can't compile unicorn because of kgio

### ISSUE THREAD

**Issue by wildmaples** [oracle/truffleruby#2291] opened 2021-03-09 17:44 UTC
# Issue

We are unable to `bundle install unicorn` on `storefront-renderer`. 

This is the exceptions I get when trying:

```
[....]
"/Users/mapleong/src/github.com/Shopify/truffleruby/mxbuild/truffleruby-jvm-ce/languages/llvm/native/bin/graalvm-native-clang -o conftest -I/Users/mapleong/src/github.com/Shopify/truffleruby/mxbuild/truffleruby-jvm-ce/languages/ruby/lib/cext/include -I/Users/mapleong/src/github.com/Shopify/truffleruby/mxbuild/truffleruby-jvm-ce/languages/ruby/lib/cext/include/ruby/backward -I/Users/mapleong/src/github.com/Shopify/truffleruby/mxbuild/truffleruby-jvm-ce/languages/ruby/lib/cext/include -I.  -D_DARWIN_C_SOURCE   -I/usr/local/opt/openssl@1.1/include -D_GNU_SOURCE -DPOSIX_C_SOURCE=1-D_POSIX_C_SOURCE=200112L   -Wimplicit-function-declaration -Wno-int-conversion -Wno-int-to-pointer-cast -Wno-incompatible-pointer-types -Wno-format-invalid-specifier -Wno-format-extra-args -ferror-limit=500 conftest.c  -L.  -L/usr/local/opt/openssl@1.1/lib     -lgraalvm-llvm    -L/Users/mapleong/src/github.com/Shopify/truffleruby/mxbuild/truffleruby-jvm-ce/languages/ruby/lib/cext -ltruffleruby"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <ruby.h>
 4: #include <ruby/io.h>
 5: typedef struct RFile rbcv_typedef_;
 6: rbcv_typedef_ *rbcv_ptr_;
 7: 
 8: #include <stdio.h>
 9: /*top*/
10: typedef unsigned
11: #ifdef PRI_LL_PREFIX
12: #define PRI_CONFTEST_PREFIX PRI_LL_PREFIX
13: LONG_LONG
14: #else
15: #define PRI_CONFTEST_PREFIX "l"
16: long
17: #endif
18: conftest_type;
19: conftest_type conftest_const = (conftest_type)(sizeof((*rbcv_ptr_)));
20: int main() {printf("%"PRI_CONFTEST_PREFIX"u\n", conftest_const); return 0;}
/* end */

./conftest |
dyld: Library not loaded: @rpath/libgraalvm-llvm.1.dylib
  Referenced from: /Users/mapleong/src/github.com/Shopify/storefront-renderer/vendor/truffleruby/21.1.0-dev-1c3ecb12/gems/kgio-2.11.3/ext/kgio/./conftest
  Reason: image not found

[...]

extconf failed, exit code 1

Gem files will remain installed in
/Users/mapleong/src/github.com/Shopify/storefront-renderer/vendor/truffleruby/21.1.0-dev-1c3ecb12/gems/kgio-2.11.3 for inspection.
Results logged to
/Users/mapleong/src/github.com/Shopify/storefront-renderer/vendor/truffleruby/21.1.0-dev-1c3ecb12/extensions/x86_64-darwin/21.1.0-dev-1c3ecb12/kgio-2.11.3/gem_make.out

An error occurred while installing kgio (2.11.3), and Bundler cannot continue.
Make sure that `gem install kgio -v '2.11.3'` succeeds before bundling.

In Gemfile:
  unicorn was resolved to 5.8.0, which depends on
    kgio
```

We think it is because that there are some internals from `kgio` (used by unicorn) that TruffleRuby haven't implemented yet. 

It seems like this was an issue for others as well but solved by just not using unicorn: https://github.com/oracle/truffleruby/issues/1379 https://github.com/oracle/truffleruby/issues/1475

# Question 

I understand that having the `Process.fork` feature is a requirement for `unicorn` to work and [it isn't working on TR yet](https://github.com/oracle/truffleruby/blob/master/doc/user/compatibility.md#fork), but is there a way we can still get `unicorn` / `kgio` to compile but not work fully? (lol) We are currently only using unicorn for one of the libraries, `::Unicorn::HttpServer::LISTENERS` and AFAIK not using anything that requires `Process.fork` yet.  

In any case, I'm finding a way to refactor the class/test in `storefront-renderer` so it won't require unicorn unless needed, so this is not a blocking issue!

**Comment by eregon** [comment] 2021-03-09 19:58
The specific error above (`@rpath/libgraalvm-llvm.1.dylib not found`) is likely to be fixed by a PR which should be merged soon.
With that `gem install unicorn` succeeds for me on Linux, and `unicorn --help` actually works.

**Comment by eregon** [comment] 2021-03-09 20:39
I forgot to link, the specific error is essentially a duplicate of https://github.com/oracle/truffleruby/issues/2285

**Comment by wildmaples** [comment] 2021-03-09 20:40
Thank you -- was just about to ask!

**Comment by tomstuart** [comment] 2021-03-10 09:24
> The specific error above (`@rpath/libgraalvm-llvm.1.dylib not found`) is likely to be fixed by a PR which should be merged soon.

Is this a PR in `oracle/truffleruby` or elsewhere? (I can’t spot it.)

**Comment by eregon** [comment] 2021-03-10 10:37
It's an internal PR.

**Comment by eregon** [comment] 2021-03-10 13:38
`unicorn` and `kgio` should install fine with b97777e8f898f710d1910f5f86fc4e585f25ef94.

**Closed by eregon** 2021-03-10 13:38 UTC
Labels: cexts, shopify
