### ISSUE TITLE
numo-narray: `rb_exc_raise': wrong argument type (TypeError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#2001] opened 2020-05-07 11:58 UTC
```
truffleruby 20.2.0-dev-b9669c4c, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

To reproduce:
```
gem install numo-narray
ruby -rnumo/narray -e 'Numo::DFloat.new(3,5).seq'
```

Error:

```
~/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1023:in `rb_exc_raise': wrong argument type (TypeError)
	from ruby.c:2008:in `rb_exc_raise'
	from ruby.c:2827:in `rb_check_typeddata'
	from ~/.gem/truffleruby/2.6.5/gems/numo-narray-0.9.1.8/ext/numo/narray/numo/narray.h:265:in `na_get_narray_t'
	from ~/.gem/truffleruby/2.6.5/gems/numo-narray-0.9.1.8/ext/numo/narray/narray.c:264:in `na_array_to_internal_shape'
	from ~/.gem/truffleruby/2.6.5/gems/numo-narray-0.9.1.8/ext/numo/narray/narray.c:393:in `na_initialize'
	from ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `initialize'
	from -e:1:in `new'
	from -e:1:in `<main>'
```

**Comment by deepj** [comment] 2020-06-08 03:59
Closed due to I'm not welcome anymore in Ruby community

**Comment by mc2dx** [comment] 2020-07-05 12:28
Hi @deepj,
I hope that you are well and I am curious if you solved the issue? I reproduced your issue and I have encountered the same problem. I debugged it a little bit. I am new for `truffle-ruby` but I was very excited for me to check your issue and get deeper inside `truffle ruby` and `numo-narray` code. 

_ruby version_
```
ruby -v
truffleruby 20.2.0-dev-6dc25181, like ruby 2.6.6, GraalVM CE Native [x86_64-darwin]
```
_irb console_
```
:009 > Numo::DFloat.new(3, 5).seq
Traceback (most recent call last):
       13: from /Users/mateusz/.rvm/rubies/truffleruby-head/bin/irb:37:in `<main>'
       12: from /Users/mateusz/.rvm/rubies/truffleruby-head/bin/irb:37:in `load'
       11: from /Users/mateusz/.rvm/rubies/truffleruby-head/bin/irb:37:in `load'
       10: from /Users/mateusz/.rvm/rubies/truffleruby-head/lib/gems/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        9: from (irb):9
        8: from (irb):9:in `new'
        7: from /Users/mateusz/.rvm/rubies/truffleruby-head/lib/truffle/truffle/cext_ruby.rb:39:in `initialize'
        6: from /Users/mateusz/.rvm/gems/truffleruby-head/gems/numo-narray-0.9.1.8/ext/numo/narray/narray.c:393:in `na_initialize'
        5: from /Users/mateusz/.rvm/gems/truffleruby-head/gems/numo-narray-0.9.1.8/ext/numo/narray/narray.c:264:in `na_array_to_internal_shape'
        4: from /Users/mateusz/.rvm/gems/truffleruby-head/gems/numo-narray-0.9.1.8/ext/numo/narray/numo/narray.h:265:in `na_get_narray_t'
        3: from data.c:40:in `rb_check_typeddata'
        2: from exception.c:19:in `rb_exc_raise'
        1: from /Users/mateusz/.rvm/rubies/truffleruby-head/lib/truffle/truffle/cext.rb:1029:in `rb_exc_raise'
TypeError (wrong argument type)
```
Let's think about this part https://github.com/ruby-numo/numo-narray/blob/master/ext/numo/narray/numo/narray.h#L260-L268 and https://github.com/oracle/truffleruby/blob/master/doc/contributor/cexts.md#data-and-typed-data because I think that it is definitely a problem with "types". You wrote your own extensions and I am not sure how these types work exactly. 

In `data.c:40` (from `truffle-ruby` repository), we have such code:

```c
void *rb_check_typeddata(VALUE value, const rb_data_type_t *data_type) {
  struct RTypedData* typed_data = RTYPEDDATA(value);
  if (typed_data->type != data_type) {
    rb_raise(rb_eTypeError, "wrong argument type");
  }
  return typed_data->data;
}
```
and (from `numo-narray/ext/numo/narray/numo/narray.h`)

```c
static inline narray_t *
na_get_narray_t(VALUE obj)
{
    narray_t *na;

    Check_TypedStruct(obj,&na_data_type);
    na = (narray_t*)DATA_PTR(obj);
    return na;
}
```
Maybe there is a solution to the issue? Let me know if you want to continue work on this.

**Comment by larskanis** [comment] 2020-08-06 19:21
Narray makes use of [inheritance of T_DATA](https://github.com/ruby-numo/numo-narray/blob/9c645424347bc05502bb5226c34de5f0d015a536/ext/numo/narray/narray.c#L229) objects. This didn't work but seems to be fixed in https://github.com/oracle/truffleruby/commit/f460ce7998c4be937ad298ca3f0daac12d4531e2 .

I noticed the same issue in [ruby-pg](https://github.com/ged/ruby-pg/pull/349). So far I didn't try  narray.gem or ruby-pg on Truffleruby master, but the change looks good. Will the commit in question go into a Truffleruby release soon?

**Comment by eregon** [comment] 2020-08-07 10:56
@larskanis That commit will be part of 20.2.

The release schedule is on https://www.graalvm.org/docs/release-notes/version-roadmap/
> Aug 18, 2020: 20.2

**Comment by eregon** [comment] 2020-08-07 11:01
The `numo-narray` examples works now:
```
$ truffleruby -rnumo/narray -e 'p Numo::DFloat.new(3,5).seq'
Numo::DFloat#shape=[3,5]
[[0, 1, 2, 3, 4], 
 [5, 6, 7, 8, 9], 
 [10, 11, 12, 13, 14]]
```

**Closed by eregon** 2020-08-07 11:01 UTC
Labels: cexts

**Comment by larskanis** [comment] 2020-08-07 13:27
@eregon Thank you for the link to the release schedule! And good to know that it will be no blocker for https://github.com/ged/ruby-pg/pull/349

**Comment by eregon** [comment] 2020-08-10 07:30
@larskanis It would be useful if you can test (temporarily, or could be added as allowed failure) on that PR if `truffleruby-head` works, to make sure there is no other issue.

Adding as an allowed failure would also allow me to track there is no regression with truffleruby-head + latest `pg` [conveniently](https://github.com/eregon/truffleruby-gem-tracker).

**Comment by larskanis** [comment] 2020-08-10 16:16
@eregon TruffleRuby-head looks good: https://travis-ci.org/github/ged/ruby-pg/builds/716604081
Thank you for the hint!

**Comment by larskanis** [comment] 2020-08-30 13:20
@eregon Ruby-pg now has tests on `truffleruby` and `truffleruby-head`: https://travis-ci.org/github/ged/ruby-pg/builds/722468366. Just in case you want to add something to
https://github.com/eregon/truffleruby-gem-tracker
