### ISSUE TITLE
Zlib::Deflate fails to load with certain options

### ISSUE THREAD

**Issue by liamwhite** [oracle/truffleruby#1704] opened 2019-06-09 20:07 UTC
Environment (default vagrant stretch box):
```
vagrant@test:~$ uname -a
Linux test 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
vagrant@test:~$ free -hm
              total        used        free      shared  buff/cache   available
Mem:           3.9G         78M        3.3G         17M        535M        3.5G
Swap:          1.0G         51M        970M
vagrant@test:~$ chruby
 * truffleruby-19.0.0
vagrant@test:~$ irb
irb(main):001:0> [TruffleRuby.cexts?, TruffleRuby.jit?, TruffleRuby.native?, TruffleRuby.revision]
=> [true, true, true, "3b03d739"]
```
Reproduction code:
```
vagrant@test:~$ irb -rzlib
irb(main):001:0> Zlib::Deflate.new(Zlib::BEST_COMPRESSION)
=> #<Zlib::Deflate:0x1f80>
irb(main):002:0> [ERROR] Failed to disable litteral next character
java.io.IOException: Cannot run program "sh": fork() failed
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:308)
	at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
	at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
	at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:194)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2455)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
	at org.truffleruby.stdlib.readline.ReadlineNodes$ReadlineNode.lambda$readline$0(ReadlineNodes.java:173)
	at org.truffleruby.core.thread.ThreadManager.runUntilResult(ThreadManager.java:440)
	at org.truffleruby.core.thread.ThreadManager.runUntilResult(ThreadManager.java:473)
	at org.truffleruby.stdlib.readline.ReadlineNodes$ReadlineNode.readline(ReadlineNodes.java:171)
	at org.truffleruby.stdlib.readline.ReadlineNodesFactory$ReadlineNodeFactory$ReadlineNodeGen.execute(ReadlineNodesFactory.java:404)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:51)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:302)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:239)

  <...>

	at org.truffleruby.launcher.RubyLauncher.runRubyMain(RubyLauncher.java:219)
	at org.truffleruby.launcher.RubyLauncher.launch(RubyLauncher.java:120)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	at org.truffleruby.launcher.RubyLauncher.main(RubyLauncher.java:37)
Caused by: java.io.IOException: fork() failed
	at com.oracle.svm.core.posix.Java_lang_Process_Supplement.forkAndExec(Java_lang_Process_Supplement.java:375)
	at java.lang.UNIXProcess.forkAndExec(UNIXProcess.java:230)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 515 more
```
```
vagrant@test:~$ irb -rzlib
irb(main):001:0> deflater = Zlib::Deflate.new(Zlib::BEST_COMPRESSION, Zlib::MAX_WBITS, Zlib::MAX_MEM_LEVEL)
Traceback (most recent call last):
        8: from /home/vagrant/.rubies/truffleruby-19.0.0/bin/irb:31:in `<main>'
        7: from (irb):1
        6: from (irb):1:in `new'
        5: from /home/vagrant/.rubies/truffleruby-19.0.0/lib/truffle/truffle/cext_ruby.rb:41:in `initialize'
        4: from ./src/main/c/zlib/zlib.c:1555:in `rb_deflate_initialize'
        3: from ./src/main/c/zlib/zlib.c:340:in `raise_zlib_error'
        2: from ./src/main/c/cext/ruby.c:2067:in `rb_exc_raise'
        1: from /home/vagrant/.rubies/truffleruby-19.0.0/lib/truffle/truffle/cext.rb:1160:in `rb_exc_raise'
Zlib::MemError (insufficient memory)
irb(main):002:0> 
```
I'm not sure why it is being reported that there is insufficient memory. 4g should be plenty, no?

[This code is used in Sprockets.](https://github.com/rails/sprockets/blob/master/lib/sprockets/cache/file_store.rb#L99)

**Comment by gogainda** [comment] 2020-11-07 17:50
Similar issues I see in here https://travis-ci.org/github/doorkeeper-gem/doorkeeper/jobs/742109333
```
  1) Edit application updating a valid app

     Failure/Error: <%= stylesheet_link_tag "doorkeeper/admin/application" %>

     

     ActionView::Template::Error:

       insufficient memory

     # /home/travis/.rvm/rubies/truffleruby-head/lib/truffle/truffle/cext.rb:1049:in `rb_exc_raise'

     # exception.c:19:in `rb_exc_raise'

     # zlib.c:340:in `raise_zlib_error'

     # zlib.c:1555:in `rb_deflate_initialize'

     # /home/travis/.rvm/rubies/truffleruby-head/lib/truffle/truffle/cext_ruby.rb:39:in `initialize'

     # <internal:core> core/array.rb:873:in `reverse_each'

     # <internal:core> core/enumerable.rb:627:in `block in find'

     # <internal:core> core/enumerable.rb:625:in `each'

     # <internal:core> core/enumerable.rb:625:in `find'

     # ./app/views/layouts/doorkeeper/admin.html.erb:8:in `__home_travis_build_doorkeeper_gem_doorkeeper_app_views_layouts_doorkeeper_admin_html_erb__4014272067693317404_828168'

     # /home/travis/.rvm/rubies/truffleruby-head/lib/mri/benchmark.rb:308:in `realtime'

     # <internal:core> core/kernel.rb:533:in `tap'

     # /home/travis/.rvm/rubies/truffleruby-head/lib/mri/forwardable.rb:230:in `get'

     # ./spec/requests/applications/applications_request_spec.rb:183:in `block (2 levels) in <top (required)>'

     # <internal:core> core/array.rb:873:in `reverse_each'

     # ------------------

     # --- Caused by: ---

     # Zlib::MemError:

     #   insufficient memory

     #   /home/travis/.rvm/rubies/truffleruby-head/lib/truffle/truffle/cext.rb:1049:in `rb_exc_raise'
```

**Comment by grvm** [comment] 2020-12-23 17:55
Facing the same error. Trying `TruffleRuby 20.3.0` with `Rails 6.1.0` on `Win10 WSL2 (Debian Bullseye)`
Added a scaffold, ran migrations, tried to access the index action & greeted with this

```
Completed 500 Internal Server Error in 569ms (ActiveRecord: 24.7ms | Allocations: 0)



ActionView::Template::Error (insufficient memory):
     6:     <%= csrf_meta_tags %>
     7:     <%= csp_meta_tag %>
     8:
     9:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    10:     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    11:   </head>
    12:

app/views/layouts/application.html.erb:9

NoMethodError: undefined method `bindings' for #<Zlib::MemError: insufficient memory>
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/web-console-4.1.0/lib/web_console/exception_mapper.rb:25:in `initialize'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/web-console-4.1.0/lib/web_console/exception_mapper.rb:8:in `new'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/web-console-4.1.0/lib/web_console/exception_mapper.rb:8:in `follow'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/web-console-4.1.0/lib/web_console/session.rb:34:in `from'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/web-console-4.1.0/lib/web_console/middleware.rb:30:in `block in call'
        from <internal:core> core/throw_catch.rb:36:in `catch'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/web-console-4.1.0/lib/web_console/middleware.rb:17:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/actionpack-6.1.0/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/railties-6.1.0/lib/rails/rack/logger.rb:37:in `call_app'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/railties-6.1.0/lib/rails/rack/logger.rb:26:in `block in call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:37:in `tagged'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/activesupport-6.1.0/lib/active_support/tagged_logging.rb:99:in `tagged'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/railties-6.1.0/lib/rails/rack/logger.rb:26:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/actionpack-6.1.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/actionpack-6.1.0/lib/action_dispatch/middleware/request_id.rb:26:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/activesupport-6.1.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/actionpack-6.1.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/actionpack-6.1.0/lib/action_dispatch/middleware/static.rb:24:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/actionpack-6.1.0/lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/rack-mini-profiler-2.2.1/lib/mini_profiler/profiler.rb:368:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/webpacker-5.2.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/railties-6.1.0/lib/rails/engine.rb:539:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/puma-5.1.1/lib/puma/configuration.rb:246:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/puma-5.1.1/lib/puma/request.rb:76:in `block in handle_request'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/puma-5.1.1/lib/puma/thread_pool.rb:337:in `with_force_shutdown'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/puma-5.1.1/lib/puma/request.rb:75:in `handle_request'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/puma-5.1.1/lib/puma/server.rb:431:in `process_client'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/puma-5.1.1/lib/puma/server.rb:405:in `process_client'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/puma-5.1.1/lib/puma/thread_pool.rb:145:in `call'
        from <HOME>/.asdf/installs/ruby/truffleruby-20.3.0/lib/gems/gems/puma-5.1.1/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

**Comment by eregon** [comment] 2021-01-04 14:40
Maybe it's caused by some inefficient pattern for Ropes.
@norswap is working on a fix for some of that.

**Comment by norswap** [comment] 2021-02-04 18:16
The `irb` reprod now works on master. Most likely fixed by https://github.com/oracle/truffleruby/commit/ec62fae4f65ad57bf6de4d89ff70dd0597dbd058

I'm closing the issue, but please let me know if there are more issues (@grvm I'd be particularly interested to see if it fixes that rails use case, as it's not clear that this issue happens only when constructing the Zlib object).

**Closed by norswap** 2021-02-04 18:16 UTC
Labels: bug, compatibility
