### ISSUE TITLE
prawn: failed to allocate memory (NoMemoryError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1523] opened 2018-12-09 14:03 UTC
This is some deep problem. The problem occurs after running spec, when a complicated PDF document is rendered.

To reproduce:

```
git clone https://github.com/prawnpdf/prawn.git
cd prawn
bundle install
bundle exec rake spec
```

Error:

```
~/.gem/truffleruby/2.4.4/gems/ttfunk-1.5.1/lib/ttfunk/subset/unicode_8bit.rb:59:in `map': failed to allocate memory (NoMemoryError)
	from ~/.gem/truffleruby/2.4.4/gems/ttfunk-1.5.1/lib/ttfunk/subset/unicode_8bit.rb:59:in `original_glyph_ids'
	from ~/.gem/truffleruby/2.4.4/gems/ttfunk-1.5.1/lib/ttfunk/subset/base.rb:32:in `encode'
	from ~/dev/bugs/truffleruby/prawn/lib/prawn/font/ttf.rb:263:in `embed'
	from ~/dev/bugs/truffleruby/prawn/lib/prawn/font/ttf.rb:257:in `block in register'
	from ~/.gem/truffleruby/2.4.4/gems/pdf-core-0.8.1/lib/pdf/core/document_state.rb:64:in `call'
	from ~/.gem/truffleruby/2.4.4/gems/pdf-core-0.8.1/lib/pdf/core/document_state.rb:64:in `block in before_render_actions'
	from ~/.gem/truffleruby/2.4.4/gems/pdf-core-0.8.1/lib/pdf/core/document_state.rb:64:in `each'
	from ~/.gem/truffleruby/2.4.4/gems/pdf-core-0.8.1/lib/pdf/core/document_state.rb:64:in `before_render_actions'
	from ~/.gem/truffleruby/2.4.4/gems/pdf-core-0.8.1/lib/pdf/core/renderer.rb:190:in `render_header'
	from ~/.gem/truffleruby/2.4.4/gems/pdf-core-0.8.1/lib/pdf/core/renderer.rb:166:in `render'
	from ~/dev/bugs/truffleruby/prawn/lib/prawn/document.rb:380:in `render'
	from ~/dev/bugs/truffleruby/prawn/spec/manual_spec.rb:28:in `block (3 levels) in <top (required)>'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `instance_exec'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `map'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `block in run'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `map'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:592:in `run'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (3 levels) in run_specs'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `map'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block (2 levels) in run_specs'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
	from ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/exe/rspec:4:in `<main>'
Thread[TruffleCompilerThread-69,10,main]: Compilation of Prawn::Text::Formatted::Arranger#format_array= ~/dev/bugs/truffleruby/prawn/lib/prawn/text/formatted/arranger.rb:91 failed:
java.lang.OutOfMemoryError: Garbage-collected heap size exceeded.
To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
Retrying compilation of Prawn::Text::Formatted::Arranger#format_array= ~/dev/bugs/truffleruby/prawn/lib/prawn/text/formatted/arranger.rb:91
Graal diagnostic output saved in ~/dev/bugs/truffleruby/prawn/dumps/1544363631610/graal_diagnostics_57854.zip
~/.rubies/truffleruby-1.0.0-rc10/bin/truffleruby -I~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib:~/.gem/truffleruby/2.4.4/gems/rspec-support-3.8.0/lib ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb -t ~unresolved failed
```

**Comment by nirvdrum** [comment] 2019-01-23 23:12
Thanks for the bug report! I'm happy to say that I'm unable to reproduce the issue with TruffleRuby master. We fixed an issue with array handling that had been causing seemingly odd out-of-memory problems. I think that patch fixed this issue as well.

I'm going to close the issue as fixed and I'll follow-up here when TruffleRuby 1.0.0 RC 12 is released so you can verify. If for some reason you're still seeing the problem then, just comment here and I'll reopen the issue.

**Closed by nirvdrum** 2019-01-23 23:12 UTC
Labels: bug

**Comment by eregon** [comment] 2019-02-06 10:08
@deepj Is memory that high just when running specs like above?

**Comment by eregon** [comment] 2019-02-06 10:11
`spec/manual_spec.rb` generates a pretty big PDF IIRC, that might be part of it. How much memory does MRI use?

**Comment by deepj** [comment] 2019-02-06 16:21
@eregon I used Ruby 2.6.1 and these are the results

In a case of the given spec ~ 41.1 MB
In a case of the whole spec suite ~ 89.2 MB

I think prawn can be good "memory usage benchmark" for TruffleRuby.

**Comment by eregon** [comment] 2019-02-06 16:58
OK, 89MB vs 8GB is definitely a problem. Part of it might be due to #1569.
Could you extract it in a new issue since this one is closed?
