### ISSUE TITLE
net-scp: Net::SCP is not a class (TypeError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1593] opened 2019-02-23 13:52 UTC
This issue is occurred when I run `net-scp` tests

To reproduce:

```
git clone https://github.com/net-ssh/net-scp.git
cd net-scp
bundle
bundle exec rake test
```

Error:

```
~/dev/bugs/truffleruby/net-scp/lib/net/scp/errors.rb:1:in `Net': Net::SCP is not a class (TypeError)
	from ~/dev/bugs/truffleruby/net-scp/lib/net/scp/errors.rb:1:in `<top (required)>'
	from ~/dev/bugs/truffleruby/net-scp/lib/net/scp.rb:5:in `require'
	from ~/dev/bugs/truffleruby/net-scp/lib/net/scp.rb:5:in `<top (required)>'
	from ~/dev/bugs/truffleruby/net-scp/test/common.rb:21:in `require'
	from ~/dev/bugs/truffleruby/net-scp/test/common.rb:21:in `<top (required)>'
	from ~/dev/bugs/truffleruby/net-scp/test/test_download.rb:1:in `require'
	from ~/dev/bugs/truffleruby/net-scp/test/test_download.rb:1:in `<top (required)>'
	from ~/dev/bugs/truffleruby/net-scp/test/test_all.rb:2:in `require'
	from ~/dev/bugs/truffleruby/net-scp/test/test_all.rb:2:in `block (2 levels) in <top (required)>'
	from ~/dev/bugs/truffleruby/net-scp/test/test_all.rb:2:in `each'
	from ~/dev/bugs/truffleruby/net-scp/test/test_all.rb:2:in `block in <top (required)>'
	from ~/dev/bugs/truffleruby/net-scp/test/test_all.rb:1:in `chdir'
	from ~/dev/bugs/truffleruby/net-scp/test/test_all.rb:1:in `<top (required)>'
	from ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:17:in `require'
	from ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	from ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:5:in `select'
	from ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
Command failed with status (1)
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `__send__'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
~/.gem/truffleruby/2.4.4/bin/bundle:23:in `load'
~/.gem/truffleruby/2.4.4/bin/bundle:23:in `load'
~/.gem/truffleruby/2.4.4/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by aardvark179** [comment] 2019-02-25 15:40
It fails with the same error for me on MRI. This is caused by `version.rb` creating a `Net::SCP` module.

**Comment by aardvark179** [comment] 2019-02-25 16:00
Looking at their `.travis.yml` I don't think they use bundler for running their CI tests, which is probably why they haven't seen this problem. I'd suggest reporting a bug, or creating a PR, against `net-scp`.
Let me know if you're okay with me closing this issue.

**Comment by deepj** [comment] 2019-03-06 06:31
@aardvark179 yes, this was a mistake. My apology for this. This can be closed.

**Comment by aardvark179** [comment] 2019-03-08 15:27
Thanks, I'll close this.

**Closed by aardvark179** 2019-03-08 15:27 UTC
