### ISSUE TITLE
Rational() with string arg should raise ArgumentError

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2619] opened 2022-03-08 19:28 UTC
Ruby 3.0.2:

`Rational("bogus", 1) # => ArgumentError`

TruffleRuby 22.0.0.2:

`Rational("bogus", 1) # => (0/1)`

As to why it raises an ArgumentError instead of a TypeError, I don't remember, but it's probably why I originally tested for this.

**Comment by aardvark179** [comment] 2022-03-09 15:00
This is already fixed on master. This is a duplicate of #2566 .

**Closed by aardvark179** 2022-03-09 15:00 UTC
Labels: compatibility
