### ISSUE TITLE
Enumerator::Lazy is missing a few methods, leading to different behavior from MRI

### ISSUE THREAD

**Issue by ivoanjo** [oracle/truffleruby#2273] opened 2021-02-24 11:20 UTC
Hello there 👋 

I was trying out the `ddtrace` gem specs with TruffleRuby, and ran into a failure in [`chunker_spec.rb`](https://github.com/DataDog/dd-trace-rb/blob/master/spec/ddtrace/chunker_spec.rb).

This is caused by TruffleRuby not implementing the full set of methods on `Enumerator::Lazy`, which means that a few of the method implementations from `Enumerable` get used instead, which leads to lazy enumerables becoming non-lazy accidentally.

The specific example I ran into is the case of `slice_before`. Here's how it behaves on MRI:

```
[20] pry(main)> puts RUBY_DESCRIPTION
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
=> nil
[21] pry(main)> [1, 2, 3].lazy.slice_before { |n| n > 2 }
=> #<Enumerator::Lazy: ...>
```

and here's how it behaves on TruffleRuby:

```
[16] pry(main)> puts RUBY_DESCRIPTION
truffleruby 21.0.0.2, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
=> nil
[17] pry(main)> [1, 2, 3].lazy.slice_before { |n| n > 2 }
=> #<Enumerator: #<Enumerator::Generator:0x2618 @proc=#<Proc:0x2628 <internal:core> core/enumerable.rb:229>>:each>
```

Looking at the list of methods that `Enumerator::Lazy` has on MRI vs on TruffleRuby, it looks like this issue would apply to a few more:

```ruby
[24] pry(main)> puts RUBY_DESCRIPTION
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
=> nil
[25] pry(main)> example = [].lazy
=> #<Enumerator::Lazy: ...>
[26] pry(main)> ls example
Enumerable#methods:
  all?   cycle       each_slice  first     max      min_by     one?          sort     to_a
  any?   detect      entries     group_by  max_by   minmax     partition     sort_by  to_h
  chain  each_cons   find        include?  member?  minmax_by  reduce        sum      to_set
  count  each_entry  find_index  inject    min      none?      reverse_each  tally
Enumerator#methods:
  +     each_with_index   feed     next         peek         rewind  with_object
  each  each_with_object  inspect  next_values  peek_values  size
Enumerator::Lazy#methods:
  chunk           drop        filter      force   map          slice_before  to_enum
  chunk_while     drop_while  filter_map  grep    reject       slice_when    uniq
  collect         eager       find_all    grep_v  select       take          with_index
  collect_concat  enum_for    flat_map    lazy    slice_after  take_while    zip
```

vs TruffleRuby:

```ruby
[18] pry(main)> puts RUBY_DESCRIPTION
truffleruby 21.0.0.2, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
=> nil
[19] pry(main)> example = [].lazy
=> #<Enumerator::Lazy: #<Enumerator::Generator:0x26f8 @proc=#<Proc:0x2708 <internal:core> core/enumerator.rb:285>>:each>
[20] pry(main)> ls example
Enumerable#methods:
  all?         cycle       entries     force     max_by   minmax_by  reverse_each  sort_by  to_set
  any?         detect      filter_map  group_by  member?  none?      slice_after   sum
  chain        each_cons   find        include?  min      one?       slice_before  tally
  chunk_while  each_entry  find_index  inject    min_by   partition  slice_when    to_a
  count        each_slice  first       max       minmax   reduce     sort          to_h
Enumerator#methods:
  +     each_with_index   feed     next         peek         rewind  with_index
  each  each_with_object  inspect  next_values  peek_values  size    with_object
Enumerator::Lazy#methods:
  chunk           drop        enum_for  flat_map  lazy    select      to_enum
  collect         drop_while  filter    grep      map     take        uniq
  collect_concat  eager       find_all  grep_v    reject  take_while  zip
```

Let me know if I can provide any more information! :)

**Comment by eregon** [comment] 2021-02-24 11:49
Thanks for the report.

We actually have `Enumerator::Lazy#slice_before`:
```
$ ruby -ve 'p Enumerator::Lazy.instance_methods(false).grep(/slice/)'
truffleruby 21.0.0, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]
[:slice_before, :slice_when, :slice_after]
```
But it's the same as `Enumerator#slice_before` currently:
https://github.com/oracle/truffleruby/blob/2334c2b9de13d33da9151547ce4cd03ed3fd853d/src/main/ruby/truffleruby/core/enumerator.rb#L529
which interestingly affects `Method#owner` (and probably why `pry` hides it above):
```
jt ruby -e 'p [1, 2, 3].lazy.method(:slice_before).owner'
Enumerable
```
(maybe we should have a better way to copy methods from an ancestor)

We also have a list of extra and missing methods compared to CRuby:
https://github.com/oracle/truffleruby/blob/2334c2b9de13d33da9151547ce4cd03ed3fd853d/spec/tags/truffle/methods_tags.txt#L60-L61

---

It's not clear what's the problematic behavior here, could you share the error and/or a reproducer?
The `#inspect` being different is probably not the cause, right?

**Comment by ivoanjo** [comment] 2021-02-24 12:51
> It's not clear what's the problematic behavior here, could you share the error and/or a reproducer?
> The #inspect being different is probably not the cause, right?

Right! The failing test itself for me was https://github.com/DataDog/dd-trace-rb/blob/master/spec/ddtrace/chunker_spec.rb which is checking that the returned enumerator from that class is still lazy (aka it ends up being more of an accidental test case for core behavior than for anything we do).

But the core issue is: by not returning lazy enumerators from those methods as expected, it means that TruffleRuby silently switches from the user-requested lazy evaluation to eager evaluation. This is extra problematic if you try to do it with an infinite sequence such as:

```ruby
1.upto(Float::INFINITY).lazy.slice_before { |n| n % 10 == 0 }.map { |array| array.to_s }.take(5).to_a
```

The contract on MRI is (I believe) that calling `lazy` at the beginning means that every part of the chain will remain lazy evaluated.

**Comment by ivoanjo** [comment] 2021-02-24 15:22
Update: Found another example from our test suite -- at some point we call `force` on the result of the chunker, and it fails because `Enumerator` does not implement `force` -- only `Enumerator::Lazy` does.

So `[].lazy.slice_before { }.force` works on MRI but fails with ```NoMethodError: undefined method `force' for #<Enumerator:0x1858>``` on TruffleRuby.

**Comment by eregon** [comment] 2021-02-24 17:18
Thanks for the example, I think we should improve the specs and check MRI tests for this.
Notably the return value should be an Enumerator::Lazy and not an Enumerator for `Enumerator::Lazy#slice_before`.

**Comment by bjfish** [comment] 2021-02-26 22:23
@ivoanjo This is now fixed at: https://github.com/oracle/truffleruby/commit/cbb97d56017a10497925e062c87b55bdea545b19. Let us know if you see any more issues with this, thanks.

**Closed by bjfish** 2021-02-26 22:23 UTC
Labels: compatibility

**Comment by ivoanjo** [comment] 2021-02-27 11:18
Mega fast, thanks! Looking forward to that 21.1 release :)
