### ISSUE TITLE
Fresh install unable to run `gem` because dynamic linker can't find llvm lib

### ISSUE THREAD

**Issue by relistan** [oracle/truffleruby#3394] opened 2024-01-18 10:39 UTC
I did a fresh install with:

macOS Sonoma 14.1

`asdf install ruby truffleruby+graalvm-23.1.1`

Running `gem` at any path **outside** of `/Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/` results in:

```
<internal:core> core/kernel.rb:234:in `gem_original_require': dlopen(/Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/psych.bundle, 0x0002): Library not loaded: @rpath/libgraalvm-llvm.1.dylib (RuntimeError)
  Referenced from: <D7C051E5-2D35-3DB9-91A3-6DA4AA679139> /Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/psych.bundle
  Reason: tried: '/opt/homebrew/opt/libyaml/lib/libgraalvm-llvm.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libyaml/lib/libgraalvm-llvm.1.dylib' (no such file), '/opt/homebrew/opt/libyaml/lib/libgraalvm-llvm.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libyaml/lib/libgraalvm-llvm.1.dylib' (no such file)
	from <internal:/Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/psych.rb:13:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from <internal:/Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/rubygems.rb:608:in `load_yaml'
	from /Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/rubygems/config_file.rb:351:in `load_file'
	from /Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/rubygems/config_file.rb:194:in `initialize'
	from /Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/rubygems/gem_runner.rb:71:in `do_configuration'
	from /Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/rubygems/gem_runner.rb:33:in `run'
	from /Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/bin/gem:29:in `<main>'
```

The output of `otool -L` shows:

```
/Users/my_user/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/psych.bundle:
	@rpath/libgraalvm-llvm.1.dylib (compatibility version 0.0.0, current version 1.0.0)
	/opt/homebrew/opt/libyaml/lib/libyaml-0.2.dylib (compatibility version 3.0.0, current version 3.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)```
```

Looking at the `pysch.bundle` it seems to have `rpath` pointed weirdly:

```
$ otool -l /Users/kmatthias/.asdf/installs/ruby/truffleruby+graalvm-23.1.1/lib/mri/psych.bundle | grep LC_RPATH -A2
          cmd LC_RPATH
      cmdsize 48
         path /opt/homebrew/opt/libyaml/lib (offset 12)
```

This means it is unable to find the `@rpath/libgraalvm-llvm.1.dylib`

I looked at `post_install_hook.sh` and saw that it will recompile `psych` under certain circumstances. I ran that part of the post install by hand with this script extract:

```
root=`pwd`
function recompile() {
  ext="$1"
  cd "src/main/c/$ext"
  truffleruby -w extconf.rb
  if [ -z "$CORES" ]; then
    CORES=$(getconf _NPROCESSORS_ONLN || echo 1)
  fi
  make "--jobs=$CORES"
  cp "$ext.$(truffleruby -rrbconfig -e "print RbConfig::CONFIG['DLEXT']")" "$root/lib/mri"
  cd "$root"
  echo
}

recompile psych
```
Which I ran from inside the base directory. This recompiled... but the result was the same.

**Comment by relistan** [comment] 2024-01-18 10:45
If this should be opened on `asdf-ruby`, I'm happy to do that. It's not clear to me where to file this.

**Comment by eregon** [comment] 2024-01-18 11:48
Could you try 23.1.2 which was just released and has a fix for this macOS-specific issue?
See https://github.com/oracle/truffleruby/releases/tag/graal-23.1.2
That looks like a duplicate of #3283 & #3294.
I'm pretty sure that will fix it so I'll already close, but please comment if that doesn't fix it.

**Closed by eregon** 2024-01-18 11:48 UTC

**Comment by eregon** [comment] 2024-01-18 15:52
> and only comment back if for some reason that does not fix it.

Please let us know if it works too :)
Sorry, it was a bit of a "premature optimization" to already close this issue, my bad.

**Comment by relistan** [comment] 2024-01-18 19:25
> > and only comment back if for some reason that does not fix it.
> 
> Please let us know if it works too :) Sorry, it was a bit of a "premature optimization" to already close this issue, my bad.

All good, I appreciate you replying to the issue. 

Anyway, it works! Thanks. Appears that it was a more general Sonoma incompatibility fixed in that release.
