### ISSUE TITLE
Truffleruby-head CI started failing for rubygems

### ISSUE THREAD

**Issue by deivid-rodriguez** [oracle/truffleruby#2549] opened 2021-12-15 15:03 UTC
I didn't have time to investigate it but I thought I would at least report it!

Here's our daily CI page: https://github.com/rubygems/rubygems/actions/workflows/daily-rubygems.yml.

**Comment by eregon** [comment] 2021-12-15 15:28
https://github.com/rubygems/rubygems/runs/4527833024?check_suite_focus=true and
https://github.com/rubygems/rubygems/runs/4513709668?check_suite_focus=true seem cancelled, I guess externally so don't seem actual failures.

https://github.com/rubygems/rubygems/runs/4464537157?check_suite_focus=true is a failure, it looks like a transient:
```
 ===============================================================================
Failure: test_find_in_unresolved_tree_is_not_exponentiental(TestGemSpecification):
  <38.29162400000001> was expected to be
  <=
  <10>.
/home/runner/work/rubygems/rubygems/test/rubygems/test_gem_specification.rb:170:in `test_find_in_unresolved_tree_is_not_exponentiental'
     167:     tms = Benchmark.measure do
     168:       assert_raise(LoadError) { require 'no_such_file_foo' }
     169:     end
  => 170:     assert_operator tms.total, :<=, 10
     171:   end
     172: 
     173:   def test_self_activate_ambiguous_indirect
<internal:core> core/throw_catch.rb:36:in `catch'
<internal:core> core/throw_catch.rb:36:in `catch'
===============================================================================
```

I think we should either skip or allow a larger time for TruffleRuby for this test.
Given that the time might also include e.g. a GC in the middle and of course some or a large part of the code interpreted it might take longer than it does on CRuby.

**Comment by eregon** [comment] 2021-12-15 15:29
@bjfish Could you take a look and make a PR to rubygems so this no longer fails?

**Comment by deivid-rodriguez** [comment] 2021-12-15 16:12
But isn't it strange that it never failed before and it started failing consistently at a given point? I wonder if it could be some performance regression.

**Comment by eregon** [comment] 2021-12-15 16:16
Oh, I didn't notice the times, indeed these 2 seem cancelled because they took longer than 1 hour, that's definitely unexpected.

**Comment by eregon** [comment] 2021-12-15 17:53
I think those hangs are caused by a deadlock in Truffle during splitting. That's already fixed on graal master but the current graal import in truffleruby doesn't include it, I'll update it.

**Comment by eregon** [comment] 2021-12-20 17:37
The timeouts/deadlocks seem gone now: https://github.com/rubygems/rubygems/runs/4576911994?check_suite_focus=true
There is still that transient about using more than 10s, @bjfish will look at that.

**Comment by deivid-rodriguez** [comment] 2022-01-15 11:07
I think the deadlocks are still happening, just so you know.

**Comment by eregon** [comment] 2022-01-17 10:46
@bjfish and I are looking into it, it seems some of the tests trigger a large memory usage, and I guess that ends up swapping or being really slow hence the timeout.

It's also suboptimal that `rake test` keeps the `rake` process alive during the entire tests, maybe that's something we can fix in `rake`.

**Comment by bjfish** [comment] 2022-02-11 15:07
@deivid-rodriguez The build is passing now:
https://github.com/rubygems/rubygems/actions/runs/1826802635

The large memory usage appeared to have been the cause and was alleviated mostly by:
https://github.com/oracle/truffleruby/commit/92d8e8780d3710453e142c5a75ff6c79b4040f6d

**Closed by bjfish** 2022-02-11 15:07 UTC
Labels: bug
