### ISSUE TITLE
I think `Process.spawn(..., 3 => io)` is broken in TruffleRuby.

### ISSUE THREAD

**Issue by ioquatix** [oracle/truffleruby#1892] opened 2020-01-30 10:34 UTC
e.g. on 19.3.0

```
koyoko% irb                             
irb(main):001:0> options = {3 => $stderr}
=> {3=>#<IO:fd 2>}
irb(main):002:0> Process.spawn("echo", "cats", **options)
Traceback (most recent call last):
        2: from /home/samuel/.rbenv/versions/truffleruby-19.3.0/bin/irb:31:in `<main>'
        1: from (irb):2
TypeError (wrong argument type Integer (expected Symbol))
irb(main):003:0> Process.spawn("echo", "cats", 3 => $stderr)
cats
=> 576445
```

The option handling seems a bit messed up.

**Comment by eregon** [comment] 2020-01-30 10:53
That's an interesting behavior.
The source of difference here is that this options are no keyword arguments in the Ruby <= 2.6 sense because it contains non-Symbol keys.

So this works (both MRI and TruffleRuby):
```
ruby -e 'options={3=>$stderr}; p Process.spawn("echo", "cats", options)' 
```

In fact, the case with `**options` also fails on MRI 2.6.5:
```
$ ruby -ve 'options={3=>$stderr}; p Process.spawn("echo", "cats", **options)'
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
Traceback (most recent call last):
-e:1:in `<main>': hash key 3 is not a Symbol (TypeError)

$ truffleruby -ve 'options={3=>$stderr}; p Process.spawn("echo", "cats", **options)'
truffleruby 19.3.1, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]
-e:1:in `<main>': wrong argument type Integer (expected Symbol) (TypeError)
```

**Comment by eregon** [comment] 2020-01-30 10:56
On MRI 2.7.0 it works because keyword arguments hashes accept any key. But in 2.6.5 in before, they only accept Symbol keys. So the problem is `**options` itself raises:
```
$ ruby -ve 'def m(*args); args; end; options={3=>$stderr};  p m(**options)'
truffleruby 19.3.1, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]
-e:1:in `<main>': wrong argument type Integer (expected Symbol) (TypeError)
```

```

**Comment by eregon** [comment] 2020-01-30 10:59
TruffleRuby behaves like MRi 2.6.5 here as far as I can see, so I'll close this issue.
Thank you for reporting it though and digging into what goes wrong.

**Closed by eregon** 2020-01-30 10:59 UTC

**Comment by ioquatix** [comment] 2020-01-30 12:24
Thanks for your help.
