### ISSUE TITLE
Performance regression while calculating code coverage in 21.3.0-dev head builds

### ISSUE THREAD

**Issue by ivoanjo** [oracle/truffleruby#2407] opened 2021-07-23 11:40 UTC
Howdy 👋 

We've recently started to run a subset of the [`ddtrace` gem](https://github.com/DataDog/dd-trace-rb) test suite using [truffleruby-head](https://github.com/DataDog/dd-trace-rb/blob/master/.github/workflows/test-head.yaml).

In the past few days, our test suite has started to take really long to run on truffleruby-head, e.g. for instance on [this run](https://github.com/DataDog/dd-trace-rb/runs/3122211036?check_suite_focus=true). I was puzzled at first, as you could see that the test run finished pretty quickly in a handful of seconds, and then it looked like the ruby process just sat there for minutes or hours before it decided to finish.

I was able to "bisect" it to some issue that appeared between 710a1a2 ([good run with that version](https://github.com/DataDog/dd-trace-rb/runs/3085581569?check_suite_focus=true)), and e1c7078 (from the bad run I linked).

After some experimentation, and looking at the affected commit range for TruffleRuby, I suspect the issue may be in 6aaaa4689c49c9aaa1740ec6553d1c87a868aaf4 .

I can trivially reproduce it locally (lightly edited for readability):

```
$ git clone https://github.com/DataDog/dd-trace-rb.git
$ cd dd-trace-rb/
$ rvm use truffleruby-21.2.0
$ bundle install
$ rm -rf coverage; ruby -v
truffleruby 21.2.0, like ruby 2.7.3, GraalVM CE Native [x86_64-darwin]
$ SKIP_SIMPLECOV=0 time bundle exec rake spec:http
Randomized with seed 63516
...............................................................................

Finished in 3.63 seconds (files took 4.54 seconds to load)
79 examples, 0 failures

Randomized with seed 63516

       18.23 real        66.04 user         2.98 sys

$ rvm use truffleruby-head
$ rm -rf coverage; ruby -v
truffleruby 21.3.0-dev-a53236eb, like ruby 2.7.3, GraalVM CE Native [x86_64-darwin]
$ SKIP_SIMPLECOV=0 time bundle exec rake spec:http

Randomized with seed 29335
...............................................................................

Finished in 3.93 seconds (files took 4.56 seconds to load)
79 examples, 0 failures

Randomized with seed 29335

       69.83 real       109.55 user        25.69 sys
```

In our `Gemfile` we are using a fork of `simplecov` with an extra patch, but I've tried with upstream simplecov and the result is the same.

Setting `SKIP_SIMPLECOV=1` and re-running the test suite makes it be speedy again, so indeed the issue seems to be the post-running-specs process of calculating coverage.

Let me know if I can provide any more info! :)

**Comment by eregon** [comment] 2021-07-23 12:42
I can reproduce, thank you for the great issue report.

6aaaa4689c49c9aaa1740ec6553d1c87a868aaf4 seems unlikely because `language.contextIfSingleContext.isPresent()` should always be `true` when using RubyLauncher / `ruby`/`truffleruby` on the command line (currently).

**Comment by eregon** [comment] 2021-07-23 12:46
Looking with --cpusampler:

20.2.0:
```
 Kernel#gem_original_require                                                                                                                                                                                                                                  |       1930ms  25.9% |   5.9% ||        470ms   6.3% |  15.1% | resource:/truffleruby/core/kernel.rb~226-238:7092-7472 
 Truffle::RegexpOperations.match_in_region                                                                                                                                                                                                                    |        267ms   3.6% |  98.5% ||        237ms   3.2% |  98.3% | resource:/truffleruby/core/truffle/regexp_operations.rb~76-84:2556-2923 
 StringScanner#scan_internal                                                                                                                                                                                                                                  |        490ms   6.6% |  67.8% ||        163ms   2.2% |  36.2% | ../../.rubies/truffleruby-21.2.0/lib/truffle/strscan.rb~311-329:6967-7537 
 Truffle::FeatureLoader.find_file                                                                                                                                                                                                                             |        160ms   2.1% |  60.6% ||        147ms   2.0% |  63.3% | resource:/truffleruby/core/truffle/feature_loader.rb~75-78:2358-2501 
 Kernel#require_relative                                                                                                                                                                                                                                      |        818ms  11.0% |   0.0% ||        123ms   1.6% |   0.0% | resource:/truffleruby/core/kernel.rb~283-297:9145-9652 
 Kernel#caller_locations                                                                                                                                                                                                                                      |        105ms   1.4% |   0.0% ||        105ms   1.4% |   0.0% | resource:/truffleruby/core/kernel.rb~762-767:21280-21634 
 Truffle::RegexpOperations.match_onwards                                                                                                                                                                                                                      |        322ms   4.3% |  93.8% ||        105ms   1.4% |  86.7% | resource:/truffleruby/core/truffle/regexp_operations.rb~41-45:1435-1632 
 Thread#backtrace                                                                                                                                                                                                                                             |         87ms   1.2% |   0.0% ||         85ms   1.1% |   0.0% | resource:/truffleruby/core/thread.rb~291-294:9736-9921 
 Truffle::Coverage.disable                                                                                                                                                                                                                                    |         84ms   1.1% |   0.0% ||         84ms   1.1% |   0.0% | (core)~1:0 
 StringScanner#scan                                                                                                                                                                                                                                           |        482ms   6.5% |  68.5% ||         76ms   1.0% |  57.9% | ../../.rubies/truffleruby-21.2.0/lib/truffle/strscan.rb~242-244:5732-5800 
 Datadog::Profiling.try_loading_native_library                                                                                                                                                                                                                |        140ms   1.9% |   0.0% ||         70ms   0.9% |   0.0% | lib/ddtrace/profiling.rb~103-125:5092-6103 
 block in JSON::Pure::Generator::GeneratorMethods::Array#json_transform                                                                                                                                                                                       |         97ms   1.3% |  11.3% ||         65ms   0.9% |   9.2% | ../../.rubies/truffleruby-21.2.0/lib/json/lib/json/pure/generator.rb~345-353:11562-11890 
 Module#define_method                                                                                                                                                                                                                                         |         59ms   0.8% |  93.2% ||         59ms   0.8% |  93.2% | (core)~1:0 
 JSON::Pure::Parser#parse_array                                                                                                                                                                                                                               |        657ms   8.8% |  61.5% ||         53ms   0.7% |  37.7% | ../../.rubies/truffleruby-21.2.0/lib/json/lib/json/pure/parser.rb~240-270:8125-9103 
 String#encode!                                                                                                                                                                                                                                               |        138ms   1.9% |  73.2% ||         46ms   0.6% |  56.5% | resource:/truffleruby/core/string.rb~369-466:10023-12505 
```

e1c70780
```
 JSON::Pure::Parser#parse_array                                                                                                                                                                                                                                            |      16432ms  67.9% |  98.9% ||       5902ms  24.4% |  99.7% | ../../.rubies/truffleruby-dev/lib/json/lib/json/pure/parser.rb~240-270:8125-9103 
 StringScanner#scan_internal                                                                                                                                                                                                                                               |       6259ms  25.8% |  99.1% ||       5497ms  22.7% |  99.5% | ../../.rubies/truffleruby-dev/lib/truffle/strscan.rb~311-331:6976-7638 
 StringScanner#scan                                                                                                                                                                                                                                                        |       4586ms  18.9% |  98.6% ||       3092ms  12.8% |  99.6% | ../../.rubies/truffleruby-dev/lib/truffle/strscan.rb~242-244:5741-5809 
 StringScanner#skip                                                                                                                                                                                                                                                        |       1404ms   5.8% |  98.8% ||       1272ms   5.3% |  99.8% | ../../.rubies/truffleruby-dev/lib/truffle/strscan.rb~262-264:6147-6216 
 Truffle::RegexpOperations.match_in_region                                                                                                                                                                                                                                 |        906ms   3.7% |  86.2% ||        886ms   3.7% |  86.3% | resource:/truffleruby/core/truffle/regexp_operations.rb~64-72:2013-2397 
 Kernel#gem_original_require                                                                                                                                                                                                                                               |       2030ms   8.4% |   5.6% ||        492ms   2.0% |  15.9% | resource:/truffleruby/core/kernel.rb~226-238:7078-7458 
 JSON::Pure::Parser#parse_value                                                                                                                                                                                                                                            |      17023ms  70.3% |  99.3% ||        323ms   1.3% |  95.7% | ../../.rubies/truffleruby-dev/lib/json/lib/json/pure/parser.rb~197-238:7045-8122 
 Truffle::FeatureLoader.find_file                                                                                                                                                                                                                                          |        145ms   0.6% |  61.4% ||        136ms   0.6% |  61.8% | resource:/truffleruby/core/truffle/feature_loader.rb~75-78:2358-2501 
 Kernel#require_relative                                                                                                                                                                                                                                                   |        898ms   3.7% |   0.0% ||        118ms   0.5% |   0.0% | resource:/truffleruby/core/kernel.rb~283-297:9131-9638 
```

**Comment by eregon** [comment] 2021-07-23 13:54
It's due to e95ab5954739920f3200d1c3db66bc6d2263b5de.
It seems SimpleCov parses a pretty large JSON file at the end, and that uses StringScanner very heavily.
That seems be slower with TruffleRegex currently, likely due to not enough splitting (`scan_internal` is quite big and does not split).

**Comment by eregon** [comment] 2021-07-23 14:24
This is the JSON file being parsed: [resultset.zip](https://github.com/oracle/truffleruby/files/6869375/resultset.zip) (from `coverage/.resultset.json` from that run)
Can be reproduced with just:
```
time ruby --experimental-options --use-truffle-regex=true -rjson -e 'JSON.parse File.read "resultset.json"'
time ruby --experimental-options --use-truffle-regex=false -rjson -e 'JSON.parse File.read "resultset.json"'
```

**Comment by eregon** [comment] 2021-07-23 15:39
We got a fix, should be merged soon.

**Comment by ivoanjo** [comment] 2021-07-23 15:44
Interesting! I did briefly suspect the regex change, but since turning off simplecov made the issue go away I completely forgot about it.

Thanks for the mega-fast fix, as always 🙇 . We still don't run the full ddtrace CI test suite on TruffleRuby, but I hope to do that soon :)

**Closed** 2021-07-26 22:47 UTC
Labels: performance
