### ISSUE TITLE
Chrome inspector fails due to truffleruby-19.0.0/bin/bundle

### ISSUE THREAD

**Issue by Confusion** [oracle/truffleruby#1697] opened 2019-06-06 19:08 UTC
I followed the instructions in [tools.md](https://github.com/oracle/truffleruby/blob/master/doc/user/tools.md) to try and debug an issue, but after adding the breakpoint and pressing 'Resume script execution', the truffleruby process reports
```
$ truffleruby --inspect -S bundle exec puma
Debugger listening on port 9229.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/js_app.html?ws=127.0.0.1:9229/35ca6361-1eef8ca2e8e1
truffleruby: ~/.rvm/rubies/truffleruby-19.0.0/bin/bundle:5: `$(' is not allowed as a global variable name (SyntaxError)
```

That `bundle` file is as installed by installing truffleruby
Line 5 contains
```
SELF_PATH=$(cd "$(dirname "$0")" && pwd -P)/$(basename "$0")
```
and is part of the 'shell' part of the file.

**Comment by chrisseaton** [comment] 2019-06-07 00:05
Sorry I'm not currently able to reproduce this.

I wonder if it's something to do with how RVM interacts with these binaries. I guess it does work without the `--inspect`?

**Comment by Confusion** [comment] 2019-06-07 06:19
Ah, good point: no, it doesn't. 
```
$ truffleruby -S bundle exec puma
truffleruby: ~/.rvm/rubies/truffleruby-19.0.0/bin/bundle:5: `$(' is not allowed as a global variable name (SyntaxError)
```

Normally I start things using `bundle exec puma`, where `bundle` is resolved to 
```
$ which bundle
~/.rvm/rubies/truffleruby-19.0.0/bin/bundle
```
and that does work correctly. But because I now needed to pass the `--inspect`, I switched to the `-S` form.

So it seems rvm does nothing special here and it's truffleruby's `-S` that does something different in this case.

**Comment by eregon** [comment] 2019-06-07 09:46
@Confusion Could you post the entire contents of `~/.rvm/rubies/truffleruby-19.0.0/bin/bundle`? I think RVM does modify binaries unfortunately. `truffleruby -S bundle --version` works with `chruby`.

**Comment by Confusion** [comment] 2019-06-07 09:53
It looks like this:
```ruby
#!/usr/bin/env truffleruby_executable_hooks
# ignored by Ruby interpreter

# get the absolute path of the executable and resolve symlinks
SELF_PATH=$(cd "$(dirname "$0")" && pwd -P)/$(basename "$0")
while [ -h "$SELF_PATH" ]; do
  # 1) cd to directory of the symlink
  # 2) cd to the directory of where the symlink points
  # 3) get the pwd
  # 4) append the basename
  DIR=$(dirname "$SELF_PATH")
  SYM=$(readlink "$SELF_PATH")
  SELF_PATH=$(cd "$DIR" && cd "$(dirname "$SYM")" && pwd)/$(basename "$SYM")
done
exec "$(dirname $SELF_PATH)/ruby" "$SELF_PATH" "$@"

#!ruby
# ^ marks start of Ruby interpretation

# from libexec/bundler (not libexec/bundle)

# Exit cleanly from an early interrupt
Signal.trap("INT") do
  Bundler.ui.debug("\n#{caller.join("\n")}") if defined?(Bundler)
  exit 1
end

require "bundler"
# Check if an older version of bundler is installed
$LOAD_PATH.each do |path|
  next unless path =~ %r{/bundler-0\.(\d+)} && $1.to_i < 9
  err = String.new
  err << "Looks like you have a version of bundler that's older than 0.9.\n"
  err << "Please remove your old versions.\n"
  err << "An easy way to do this is by running `gem cleanup bundler`."
  abort(err)
end

require "bundler/friendly_errors"
Bundler.with_friendly_errors do
  require "bundler/cli"

  # Allow any command to use --help flag to show help for that command
  help_flags = %w[--help -h]
  help_flag_used = ARGV.any? {|a| help_flags.include? a }
  args = help_flag_used ? Bundler::CLI.reformatted_help_args(ARGV) : ARGV

  Bundler::CLI.start(args, :debug => true)
end
```

**Comment by eregon** [comment] 2019-06-07 10:09
@Confusion Thanks. It looks related to https://github.com/rvm/rvm/issues/4408.

The problem is the first line,
`#!/usr/bin/env truffleruby_executable_hooks` actually looks like a Ruby shebang line, because it contains `ruby`. And so the Ruby interpreter thinks the following lines are Ruby, while they are actually Bash.

MRI would fail the same way:
```
# Copy the contents above in mybundle
$ ruby -v -S mybundle --help
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
mybundle:5: `$(' is not allowed as a global variable name
mybundle:5: syntax error, unexpected end-of-input
SELF_PATH=$(cd "$(dirname "$0")" && pwd ...
zsh: exit 1     ruby -v -S mybundle --help
```
Could you check if `ruby -v -S mybundle --help` works for you with MRI in RVM?

The original file contains `#!/usr/bin/env bash` as first line, and that works fine for me.

As a workaround, using `TRUFFLERUBYOPT` should work, such as:
`TRUFFLERUBYOPT="--inspect" bundle exec puma`.

**Comment by chrisseaton** [comment] 2019-06-07 11:05
By the way when you do get it working in the inspector, it'll set a breakpoint on some internal code first. I'm fixing that.

**Comment by Confusion** [comment] 2019-06-07 11:42
> Could you check if ruby -v -S mybundle --help works for you with MRI in RVM?

It doesn't work and gives the same result you also observe.

**Comment by eregon** [comment] 2019-06-07 12:22
> It doesn't work and gives the same result you also observe.

OK, then I think it's a bug of https://github.com/rvm/executable-hooks which breaks `-S`.
One solution is not installing the RVM executable-hooks with TruffleRuby, so the original launcher keep working as with other Ruby managers, which would be a change in RVM.
It's also probably possible to fix RVM's `executable-hooks` to make this work, or TruffleRuby's launchers as mentioned in rvm/rvm#4408.
I'll think a bit and do one of these.

**Comment by eregon** [comment] 2019-08-24 10:59
`lib/cucumber/rake/task.rb` triggers this bug as well by using `path/to/ruby -S bundle ...` as found in https://github.com/asciidoctor/asciidoctor/pull/3305#issuecomment-524533456

**Comment by eregon** [comment] 2019-08-24 11:15
I filed a bug in RVM for this to understand better and figure out the best solution: https://github.com/rvm/rvm/issues/4765

**Comment by eregon** [comment] 2020-01-30 11:22
This should no longer be an issue as `rubygems-bundler` (the gem that RVM was automatically installing and causing this issue by modifying TruffleRuby launchers) is no longer installed by default for TruffleRuby: https://github.com/rvm/rvm/pull/4766
So I'll close this as I believe it's fixed.
We can reopen if it's found problematic again, or if someone intentionally wants to use the RVM `rubygems-bundler` gem with TruffleRuby.

**Closed by eregon** 2020-01-30 11:22 UTC
Labels: priority, rvm
