### ISSUE TITLE
truffleruby: Unexpected internal exception in at_exit on Sequel's CI

### ISSUE THREAD

**Issue by jeremyevans** [oracle/truffleruby#2550] opened 2021-12-15 22:27 UTC
The error message says this should be reported here: https://github.com/jeremyevans/sequel/runs/4540570171?check_suite_focus=true#step:7:14

```
Overriding module for static LexicalScope, old=InspectDataset@133b0fa, new=InspectDataset@55665413 (com.oracle.truffle.api.CompilerDirectives.ShouldNotReachHere)
	from com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:570)
	from com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:516)
	from org.truffleruby.language.LexicalScope.unsafeSetLiveModule(LexicalScope.java:54)
	from org.truffleruby.language.methods.ModuleBodyDefinitionNode.prepareLexicalScope(ModuleBodyDefinitionNode.java:86)
	from org.truffleruby.language.methods.ModuleBodyDefinitionNode.createMethod(ModuleBodyDefinitionNode.java:61)
	from org.truffleruby.language.objects.RunModuleDefinitionNode.execute(RunModuleDefinitionNode.java:37)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	from org.truffleruby.language.RubyProcRootNode.execute(RubyProcRootNode.java:55)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:655)
/home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest/spec.rb:188:in `block (2 levels) in <top (required)>'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest/spec.rb:188:in `instance_eval'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest/spec.rb:188:in `setup'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest/test.rb:96:in `block (3 levels) in run'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest/test.rb:195:in `capture_exceptions'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest/test.rb:95:in `block (2 levels) in run'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:38:in `block (2 levels) in time_it'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:31:in `around'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:37:in `block in time_it'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:281:in `time_it'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:36:in `time_it'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest/test.rb:94:in `block in run'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:376:in `on_signal'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest/test.rb:221:in `with_info_handler'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest/test.rb:93:in `run'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:1042:in `run_one_method'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:350:in `run_one_method'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:337:in `block (2 levels) in run'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:336:in `each'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:336:in `block in run'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:376:in `on_signal'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:363:in `with_info_handler'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:81:in `block in with_info_handler'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:26:in `around_all'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-hooks-1.5.0/lib/minitest/hooks/test.rb:70:in `with_info_handler'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:335:in `run'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:169:in `block in __run'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:169:in `map'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:169:in `__run'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:146:in `run'
	from /home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/minitest-5.15.0/lib/minitest.rb:73:in `block in autorun'

rake aborted!
Command failed with status (1): [/home/runner/.rubies/truffleruby-head/bin/...]
/home/runner/work/sequel/sequel/Rakefile:73:in `block in <top (required)>'
/home/runner/work/sequel/sequel/Rakefile:80:in `block (2 levels) in <top (required)>'
/home/runner/work/sequel/sequel/vendor/bundle/truffleruby/3.0.2.6/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
/home/runner/.rubies/truffleruby-head/bin/bundle:42:in `<main>'
Tasks: TOP => spec_ci => spec_core
(See full trace by running task with --trace)
```

**Comment by eregon** [comment] 2021-12-16 10:31
Thank you for the report. I'll look into it.

**Comment by bjfish** [comment] 2021-12-16 19:52
@eregon I think this may be a minimal reproduction case for this issue:
```
class Test
    def self.before _type = nil, &block
      define_method :setup do
        self.instance_eval(&block)
      end
    end

    def self.after _type = nil, &block
        define_method :teardown do
          self.instance_eval(&block)
        end
    end
  
    before do
      class ::A; end
    end

    after do
        Object.send(:remove_const, :A) if defined?(::A)
    end
end

t = Test.new
t.setup
t.teardown
t.setup
t.teardown
```
Result:
```
Overriding module for static LexicalScope, old=A@2b0b4d53, new=A@7068f7ca (com.oracle.truffle.api.CompilerDirectives.ShouldNotReachHere)
	from org.graalvm.truffle/com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:570)
	from org.graalvm.truffle/com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:516)
	from org.truffleruby.language.LexicalScope.unsafeSetLiveModule(LexicalScope.java:54)
	from org.truffleruby.language.methods.ModuleBodyDefinitionNode.prepareLexicalScope(ModuleBodyDefinitionNode.java:86)
	from org.truffleruby.language.methods.ModuleBodyDefinitionNode.createMethod(ModuleBodyDefinitionNode.java:61)
	from org.truffleruby.language.objects.RunModuleDefinitionNode.execute(RunModuleDefinitionNode.java:37)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	from org.truffleruby.language.RubyProcRootNode.execute(RubyProcRootNode.java:55)
	from org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
../../notes/sequel3.rb:4:in `block in <class:Test>'
	from ../../notes/sequel3.rb:4:in `instance_eval'
	from ../../notes/sequel3.rb:4:in `setup'
	from ../../notes/sequel3.rb:26:in `<main>'
```

**Comment by eregon** [comment] 2021-12-17 10:55
@bjfish Thanks, that's similar to the pattern in https://github.com/jeremyevans/sequel/blob/eb918d145900d9c8ba8da54b2aa38f78233d508e/spec/core/dataset_spec.rb#L3711-L3728.

A variant with `class A; end` which is actually equivalent works fine.
So it seems we're detecting `class ::Name` as a static lexical scope but it isn't necessirely if e.g. nested in blocks like in this example.

**Comment by eregon** [comment] 2021-12-17 11:10
I don't have a good solution for it currently, so I'll make a PR to Sequel to avoid the problematic pattern.
We'll need to address this at some point, but it requires a large refactoring of constant lookup.

Normally the "constant lexical scope" is always the same anywhere in Ruby code, except under `class << ...`.
But that can break if like in this example the module body under `class ::InspectDataset` (even though it's empty) actually gets executed with 2 different module values (since the constant is removed a new InspectDataset class is created).

**Comment by eregon** [comment] 2021-12-17 11:34
Unfortunately this pattern is used in many places in Sequel specs: https://github.com/jeremyevans/sequel/blob/78f1b62ef9ee567d544ade7f76b089987cf72478/spec/extensions/class_table_inheritance_spec.rb

**Comment by eregon** [comment] 2021-12-17 11:53
I found one solution, which is to use dynamic constant lookup for any `class/module` nested under a block, given that can mean that module body is executed multiple times, and possibly that module is removed/reassigned in between executions.
That does mean every constant lookup inside that module body, including any nested method or nested module body will be slower.
Hopefully that pattern is extremely rare in actual production code and mostly happens in tests.
I suspect this pattern is also bad for other Ruby implementations as basically it makes it quite difficult to have a proper inline cache for constants looked up under a dynamic constant scope.

**Closed** 2021-12-17 15:29 UTC
