### ISSUE TITLE
[interop] Foreign objects have no `object_id` and `__id__`

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#1881] opened 2020-01-07 22:38 UTC
Ruby objects are supposed to implement [`object_id`](https://ruby-doc.org/core-2.7.0/Object.html#method-i-object_id) (as well as `__id__`), but this does not seem to be the case with foreign objects. Consequently, a `NoMethodError` is thrown when the user tries to print a foreign object. I suggest to implement both using `Object#hashCode` for now.

#### Repro session
```
$ polyglot --jvm --shell
GraalVM MultiLanguage Shell 19.3.0
Copyright (c) 2013-2019, Oracle and/or its affiliates
  JavaScript version 19.3.0
  Ruby version 2.6.2
ruby> Polyglot.eval('js', '[]').object_id
Unknown identifier: object_id (NoMethodError)
        at <ruby> <top (required)>(resource:/truffleruby/core/truffle/boot.rb:16:15-49)
        at <ruby> parsing-request(Unknown)
ruby> Polyglot.eval('js', '[]').__id__
Unknown identifier: __id__ (NoMethodError)
        at <ruby> <top (required)>(resource:/truffleruby/core/truffle/boot.rb:16:15-46)
        at <ruby> parsing-request(Unknown)
ruby> puts Polyglot.eval('js', '[]')
Unknown identifier: object_id (NoMethodError)
        at <ruby> <top (required)>(resource:/truffleruby/core/truffle/boot.rb:16:15-44)
        at <ruby> parsing-request(Unknown)
```

/cc @chumer, @janehmueller, and @querenker.

**Comment by pitr-ch** [comment] 2020-01-08 09:35
Currently, the foreign object is intended to only have the polyglot API, it is truly foreign it is not required to have any of the Ruby standard methods. However, we are thinking about making it more user friendly.

**Comment by eregon** [comment] 2020-01-08 09:42
At least `puts Polyglot.eval('js', '[]')` (or for any foreign object) should work. I'm not sure why it calls `object_id`, that sounds like a bug.

**Comment by eregon** [comment] 2020-01-08 09:44
i.e., it should end up in `Truffle::Interop.foreign_to_s` which would then call `foreign_inspect`, which does not call `object_id`.

**Comment by fniephaus** [comment] 2020-01-08 10:54
> Currently, the foreign object is intended to only have the polyglot API, it is truly foreign it is not required to have any of the Ruby standard methods. However, we are thinking about making it more user friendly.

That'd be great. AFAIK, foreign objects should at least implement the object API of the corresponding language. Otherwise, users will have a hard time doing anything reasonable with them.

**Comment by pitr-ch** [comment] 2020-01-14 10:52
I've found the cause and fixed `puts Polyglot.eval('js', '[]')` case.

**Comment by fniephaus** [comment] 2020-01-14 11:00
@pitr-ch great! I'd be interested to see the patch :)

**Comment by pitr-ch** [comment] 2020-02-03 09:09
Fixed in https://github.com/oracle/truffleruby/commit/6778db38d249688a06f6462459e6dbfe2b54c35e. The object_id is added as well.

**Closed by pitr-ch** 2020-02-03 09:09 UTC
Labels: bug, polyglot

**Comment by fniephaus** [comment] 2020-02-03 09:42
Great, thanks!
