### ISSUE TITLE
performance degradation for bundle exec rake

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#2126] opened 2020-10-19 17:03 UTC
truffleruby 20.3.0-dev-ff47099e, like ruby 2.6.6, GraalVM CE Native [x86_64-linux]

There seems to have been a performance degradation running `bundle exec rake`

This can be seen from the following github workflow which compares head with different releases

https://github.com/petenorth/schools-experience/runs/1273889279?check_suite_focus=true

The two `Run docker build...` steps show the slow down.

`bundle exec rake assets:precompile` and `bundle exec rake assets:symlink_non_digested SECRET_KEY_BASE=stubbed SKIP_REDIS=true` take 5min vs 1-2min before.

**Comment by aardvark179** [comment] 2020-10-21 17:06
I can reproduce this locally and have narrowed it down to a TruffleRuby change rather than any of dependencies. I'll work to identify the precise cause of the decreased performance here. Have you been running the job against head for long, and if so do you have any idea when it started to regress?

**Comment by petenorth** [comment] 2020-10-21 17:51
https://github.com/petenorth/schools-experience/actions/runs/268120979

and

https://github.com/petenorth/schools-experience/actions/runs/268120979

these builds were 28 and 29 days ago respectively so between the 23rd and 24th of Sept .

**Comment by aardvark179** [comment] 2020-10-23 09:53
Thank you for bringing this to our attention. We've isolated the problem and are testing a PR to fix this internally.

**Comment by aardvark179** [comment] 2020-10-23 14:46
The change has now been merged in c65196d, so I'll close this bug.

**Closed by aardvark179** 2020-10-23 14:46 UTC
Labels: performance, priority

**Comment by petenorth** [comment] 2020-10-23 18:29
Yes  - that has fixed it and possibly improved it! It also seems to have improved the 'spin up' step which @eregon noted had slowed down.

**Comment by eregon** [comment] 2020-10-23 18:48
The issue was a copy-paste mistake that causes both the $LOAD_PATH and $LOADED_FEATURES caches to have a lot more misses.

There seems to be quite some gain, also on specs :smiley: 

https://github.com/petenorth/schools-experience/runs/1299494239?check_suite_focus=true
old run (from above): https://github.com/petenorth/schools-experience/runs/1273889279?check_suite_focus=true

step | 20.1 | 20.2 | head-fixed | head-before (old run)
--- | --- | --- | --- | ---
build docker image | 8m 24s | 8m 18s | 7m 38s | 7m 365
rake assets:precompile | 2m 31s | 2m 20s | 1m 34s | 5m 36s
rake assets:symlink_non_digested | 57s | 54s | 37s | 4m 12s
spin up | 2m 05s | 1m 54s | 1m 24s | 4m 46s
run specs | 14m 38s | 16m 54s | 8m 56s | 12m 41s
full workflow | 28m 39s | 30m 26s | 20m 14s | 34m 55s

@bjfish also noticed big improvements on `rails routes` and I noticed on `jt test fast` (99s->47s, 2x).

We added the `rails routes` in our benchmark infrastructure to better track over time rails startup and loading lots of code.

@petenorth Thanks again for this valuable report!
