### ISSUE TITLE
Process.euid=/Process.egid= don't accept strings

### ISSUE THREAD

**Issue by djberg96** [oracle/truffleruby#2615] opened 2022-03-05 02:42 UTC
Ruby 3.0.2 allows a string for Process.euid=, and will (I assume) do a user lookup in that case:

```ruby
# OS X
Process.euid = "test" # => can't find user for test (ArgumentError)
Process.euid = "dberger" # => "dberger"
```

But using Truffleruby 22.0.0.2:

```ruby
Process.euid = "test" # => undefined method `to_int' for "test":String
Process.euid = "dberger" # => undefined method `to_int' for "dberger":String
```

**Comment by chrisseaton** [comment] 2022-03-05 10:58
Seems an ancient feature.

https://github.com/ruby/ruby/commit/9bf9b3ef95e5a699b931435f482087c57439eda3

But it's never been properly specified - see here it specifies that it raises an error if not given an integer, but then also specifies that you can't set it to `root`, using the string, but in order to trigger an unrelated error.

https://github.com/ruby/spec/blob/a0f1a08f38d13cc6491cd1192958046bceceaf39/core/process/euid_spec.rb#L17-L45

Implementation would go here.

https://github.com/oracle/truffleruby/blob/0e730617b83d1007818ecc7452933e4a54a8832b/src/main/ruby/truffleruby/core/process.rb#L404-L430

Should be relatively easy to fix, could be a good beginner project. First thing would be specifications and then an implementation.

**Comment by eregon** [comment] 2022-03-05 12:06
Converting the user name to a uid can be done with `Etc.getpwnam(user).uid`, which is what fileutils does:
https://github.com/oracle/truffleruby/blob/0e730617b83d1007818ecc7452933e4a54a8832b/lib/mri/fileutils.rb#L1110-L1111

That means it needs `require 'etc'` but that seems fine since it's a rarely-used method.

**Comment by djberg96** [comment] 2022-03-05 14:04
Note that `Process.egid=` has the same issue.

**Comment by andrykonchin** [comment] 2022-07-06 17:04
Looks like the issue is fixed and the PR is merged.

**Closed** 2022-07-06 17:04 UTC
Labels: compatibility, good first issue
