### ISSUE TITLE
DateTime#to_time and Time#to_time don't preserve timezones

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1515] opened 2018-12-08 00:49 UTC
In old Ruby times this was an issue with the standard Date library. But it was fixed in Ruby 2.4

MRI (2.5.3)

```ruby
datetime = DateTime.strptime('2018-12-07 11:00:29 -06:00', '%Y-%m-%d %H:%M:%S %Z')
=> #<DateTime: 2018-12-07T11:00:29-06:00 ((2458460j,61229s,0n),-21600s,2299161j)>
datetime.to_time
=> 2018-12-07 11:00:29 -0600

time = Time.new(2018, 12, 7, 11, 00, 29, '-06:00')
=> 2018-12-07 11:00:29 -0600
time.to_time
=> 2018-12-07 11:00:29 -0600
```

TruffleRuby (1.0.0-rc10)

```ruby
datetime = DateTime.strptime('2018-12-07 11:00:29 -06:00', '%Y-%m-%d %H:%M:%S %Z')
=> #<DateTime: 2018-12-07T11:00:29-06:00 (212410962029/86400,-1/4,2299161)>
datetime.to_time
=> 2018-12-07 18:00:29 +0100

time = Time.new(2018, 12, 7, 11, 00, 29, '-06:00')
=> 2018-12-07 11:00:29 -0600
time.to_time
=> 2018-12-07 18:00:29 +0100
```

The results of TruffleRuby are wrong here.

**Comment by chrisseaton** [comment] 2019-01-30 21:32
I think there's tagged specs for the former but not the latter.

**Comment by deepj** [comment] 2020-06-08 05:34
Closed due to I'm not welcome anymore in Ruby community

**Comment by andrykonchin** [comment] 2022-06-20 11:19
I suppose we can close this issue.

I cannot reproduce the issue on the master branch:

```ruby
require 'date'
# => true
datetime = DateTime.strptime('2018-12-07 11:00:29 -06:00', '%Y-%m-%d %H:%M:%S %Z')
# => #<DateTime: 2018-12-07T11:00:29-06:00 ((2458460j,61229s,0n),-21600s,2299161j)>
datetime.to_time
# => 2018-12-07 11:00:29 -0600

time = Time.new(2018, 12, 7, 11, 00, 29, '-06:00')
# => 2018-12-07 11:00:29 -0600
time.to_time
# => 2018-12-07 11:00:29 -0600
```

**Closed** 2022-08-01 17:15 UTC
Labels: compatibility
