### ISSUE TITLE
[irb] Cursor / paste is slow

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#2274] opened 2021-02-24 11:56 UTC
Pasting and deleting is noticeably slower on TruffleRuby 21.0.0.2 compare with MRI:

https://user-images.githubusercontent.com/2368856/108996961-5aca0a00-769f-11eb-8b2e-aac2c113eafb.mp4

I'm not sure this has something to do with the Ruby version (the probably newer TruffleRuby console seems to syntax highlight?). But I'd assume that pasting into the latest irb has no noticeable delay like this.

**Comment by eregon** [comment] 2021-02-24 12:03
Duplicate of https://github.com/oracle/truffleruby/issues/2233, please follow that one.
In short, it's in good part an issue of the irb gem, it's been fixed upstream, but we're waiting for a release to update irb.

**Closed by eregon** 2021-02-24 12:03 UTC
Labels: duplicate

**Comment by eregon** [comment] 2021-02-24 12:10
@fniephaus Actually there was a release (see other issue).
Can you try if it works better with the latest irb/reline after `gem install irb reline`?

**Comment by fniephaus** [comment] 2021-02-24 12:12
pasting is faster, deleting is still slow. interesting :)

**Comment by eregon** [comment] 2021-02-24 12:15
Another workaround is to use `irb --readline`, as mentioned in the release notes:
https://github.com/oracle/truffleruby/blob/master/CHANGELOG.md#2100

**Comment by fniephaus** [comment] 2021-02-24 12:16
Much better, thanks!
