### ISSUE TITLE
Class#class_variable_get returns sometimes incorrect value

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1649] opened 2019-04-09 17:34 UTC
I'm not sure how to describe this (again) but I've noticed it in `Hanami::Utils` specs.

To reproduce:

```
git clone https://github.com/hanami/utils.git
cd utils
bundle
rspec
```

Error:

```
  4) Hanami::Utils::Json with MultiJson uses MultiJson engine
     Failure/Error: expect(Hanami::Utils::Json.class_variable_get(:@@engine)).to be_kind_of(Hanami::Utils::Json::MultiJsonAdapter)
       expected JSON to be a kind of Hanami::Utils::Json::MultiJsonAdapter
     # ./spec/isolation/hanami/utils/json/multi_json_spec.rb:10:in `block (3 levels) in <top (required)>'
```

The issue lies in the following construct

```ruby
Hanami::Utils::Json.class_variable_get(:@@engine)
```

But if I run the spec seperaly. All is passed.

```
rspec ./spec/isolation/hanami/utils/json/multi_json_spec.rb

Randomized with seed 19003

Hanami::Utils::Json
  with MultiJson
    uses MultiJson engine
    .parse
      raises error if given payload is malformed
      doesn't eval payload
      loads given payload
    .generate
      dumps given Hash

Deprecation Warnings:

Requiring `rspec/autorun` when running RSpec via the `rspec` command is deprecated. Called from ~/dev/bugs/truffleruby/hanami/utils/spec/support/isolation_spec_helper.rb:16:in `run'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Top 5 slowest examples (0.175 seconds, 63.6% of total time):
  Hanami::Utils::Json with MultiJson .parse raises error if given payload is malformed
    0.137 seconds ./spec/isolation/hanami/utils/json/multi_json_spec.rb:19
  Hanami::Utils::Json with MultiJson uses MultiJson engine
    0.013 seconds ./spec/isolation/hanami/utils/json/multi_json_spec.rb:9
  Hanami::Utils::Json with MultiJson .parse loads given payload
    0.011 seconds ./spec/isolation/hanami/utils/json/multi_json_spec.rb:14
  Hanami::Utils::Json with MultiJson .parse doesn't eval payload
    0.007 seconds ./spec/isolation/hanami/utils/json/multi_json_spec.rb:24
  Hanami::Utils::Json with MultiJson .generate dumps given Hash
    0.007 seconds ./spec/isolation/hanami/utils/json/multi_json_spec.rb:31

Finished in 0.275 seconds (files took 7.9 seconds to load)
5 examples, 0 failures

Randomized with seed 19003
```

**Comment by eregon** [comment] 2019-04-09 19:49
> My opinion:
> I wish people would stop using class variables, they almost never have the semantics people expect.

`@@engine` is probably set in a superclass, and based on load order and implementation, this could mean variables in subclasses are removed.

**Comment by deepj** [comment] 2020-06-08 05:06
Closed due to I'm not welcome anymore in Ruby community

**Comment by andrykonchin** [comment] 2022-07-06 11:46
I can confirm that the issue is reproduced on CRuby (3.0.3) so I suppose it isn't a TruffleRuby bug that should be fixed.

I suppose that specs in `spec/isolation/` should be run separately one by one. At least they are run this way on CI:

```sh

run_isolation_test() {
  # ...
  ruby $test --options spec/isolation/.rspec
}

run_isolation_tests() {
  local root="$pwd/spec/isolation"
  # ...

  for test in $(find $root -name '*_spec.rb')
  do
    run_isolation_test $test
    # ...
  done
}

# ...
run_unit_tests
run_isolation_tests
```

https://github.com/hanami/utils/blob/main/script/ci#L26-L51
https://github.com/hanami/utils/runs/6840998067?check_suite_focus=true

### Details

Running isolation tests
- https://github.com/hanami/utils/blob/main/spec/isolation/hanami/utils/json/multi_json_spec.rb
- https://github.com/hanami/utils/blob/main/spec/isolation/hanami/utils/json/json_spec.rb

in any order leads to the mentioned exception.

It seems obvious because each of them requires `hanami/utils/json` but the first one also requires `multi_json` gem. `Hanami::Utils::Json` during requiring initialises `@@engine` either with `MultiJsonAdapter` (if `multi_json` gem is available) or `JSON` otherwise.

If both test files are run together then the second file doesn't reload `hanami/utils/json` (it just requires so does nothing because `hanami/utils/json` was already required by the first test file) and `@@engine` is not re-assigned. It leads to the mentioned error because it's expected that `@@engine` is re-assigned.

**Closed** 2022-07-06 12:06 UTC
Labels: third-party-issue
