### ISSUE TITLE
Error when installing unf_ext

### ISSUE THREAD

**Issue by ianks** [oracle/truffleruby#1651] opened 2019-04-09 23:39 UTC
Hey there! Figured I would report an error I am getting when attempting to install the `unf_ext` gem:

```
    current directory: /home/ianks/.rbenv/versions/truffleruby-1.0.0-rc14/lib/ruby/gems/2.6.0/gems/unf_ext-0.0.7.5/ext/unf_ext
/home/ianks/.rbenv/versions/truffleruby-1.0.0-rc14/bin/truffleruby -I /home/ianks/.rbenv/versions/truffleruby-1.0.0-rc14/lib/mri -r ./siteconf20190409-3903-lt9cj3.rb extconf.rb
checking for -lstdc++... yes
creating Makefile

current directory: /home/ianks/.rbenv/versions/truffleruby-1.0.0-rc14/lib/ruby/gems/2.6.0/gems/unf_ext-0.0.7.5/ext/unf_ext
make "DESTDIR=" clean

current directory: /home/ianks/.rbenv/versions/truffleruby-1.0.0-rc14/lib/ruby/gems/2.6.0/gems/unf_ext-0.0.7.5/ext/unf_ext
make "DESTDIR="
compiling unf.cc
In file included from unf.cc:1:
./unf/normalizer.hh:4:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
make: *** [Makefile:182: unf.bc] Error 1

make failed, exit code 2
```

**Comment by chrisseaton** [comment] 2019-04-09 23:43
Hi thanks for the report!

I think this issue may be the same as this one #1648.

Can you see if https://github.com/oracle/truffleruby/blob/master/doc/user/installing-llvm.md helps?

**Comment by eregon** [comment] 2019-04-11 14:54
I'll optimistically close this as duplicate of #1648 with the solution being what @chrisseaton said above.
@ianks It would be great if you can confirm whether that solved it for you.

**Closed by eregon** 2019-04-11 14:54 UTC
Labels: cexts
