### ISSUE TITLE
sqlite3: org.truffleruby.language.control.RaiseException: Not a handle or a pointer (ArgumentError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1639] opened 2019-03-24 20:15 UTC
To reproduce:

```
git clone https://github.com/sparklemotion/sqlite3-ruby.git
cd sqlite3-ruby
bundle
bundle exec rake
```

Error:

```
mkdir -p tmp/x86_64-darwin/sqlite3_native/2.6.2
cd tmp/x86_64-darwin/sqlite3_native/2.6.2
~/.rubies/truffleruby-1.0.0-rc14/bin/truffleruby -I. ../../../../ext/sqlite3/extconf.rb
checking for sqlite3.h... yes
checking for pthread_create() in -lpthread... yes
checking for -ldl... yes
checking for dlopen()... yes
checking for dlclose()... yes
checking for dlsym()... yes
checking for sqlite3_libversion_number() in -lsqlite3... yes
checking for rb_proc_arity()... yes
checking for rb_integer_pack()... yes
checking for sqlite3_initialize()... yes
checking for sqlite3_backup_init()... yes
checking for sqlite3_column_database_name()... yes
checking for sqlite3_enable_load_extension()... yes
checking for sqlite3_load_extension()... yes
checking for sqlite3_open_v2()... yes
checking for sqlite3_prepare_v2()... yes
checking for sqlite3_int64 in sqlite3.h... yes
checking for sqlite3_uint64 in sqlite3.h... yes
creating Makefile
cd -
cd tmp/x86_64-darwin/sqlite3_native/2.6.2
/usr/bin/make
compiling ../../../../ext/sqlite3/aggregator.c
compiling ../../../../ext/sqlite3/backup.c
compiling ../../../../ext/sqlite3/database.c
compiling ../../../../ext/sqlite3/exception.c
compiling ../../../../ext/sqlite3/sqlite3.c
compiling ../../../../ext/sqlite3/statement.c
linking shared-object sqlite3/sqlite3_native.su
cd -
install -c tmp/x86_64-darwin/sqlite3_native/2.6.2/sqlite3_native.su lib/sqlite3/sqlite3_native.su
cp tmp/x86_64-darwin/sqlite3_native/2.6.2/sqlite3_native.su tmp/x86_64-darwin/stage/lib/sqlite3/sqlite3_native.su
~/.rubies/truffleruby-1.0.0-rc14/bin/truffleruby -w -I.:lib:bin:test:. -e 'require "rubygems"; gem "minitest"; require "minitest/autorun"; require "test/test_backup.rb"; require "test/test_collation.rb"; require "test/test_database.rb"; require "test/test_database_flags.rb"; require "test/test_database_readonly.rb"; require "test/test_database_readwrite.rb"; require "test/test_deprecated.rb"; require "test/test_encoding.rb"; require "test/test_integration.rb"; require "test/test_integration_aggregate.rb"; require "test/test_integration_open_close.rb"; require "test/test_integration_pending.rb"; require "test/test_integration_resultset.rb"; require "test/test_integration_statement.rb"; require "test/test_result_set.rb"; require "test/test_sqlite3.rb"; require "test/test_statement.rb"; require "test/test_statement_execute.rb"' --
~/.rubies/truffleruby-1.0.0-rc14/lib/mri/tmpdir.rb:87: warning: shadowing outer local variable - path
Run options: --seed 51960

# Running:

...............~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/resultset.rb:65:in `[]' is calling SQLite3::ResultSet::HashWithTypesAndFields#fields.  This method will be removed in
sqlite3 version 2.0.0, please call the `columns` method on the SQLite3::ResultSet
object that created this object
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/resultset.rb:65:in `[]' is calling SQLite3::ResultSet::HashWithTypesAndFields#fields.  This method will be removed in
sqlite3 version 2.0.0, please call the `columns` method on the SQLite3::ResultSet
object that created this object
................~/dev/bugs/truffleruby/sqlite3-ruby/test/test_database.rb:93:in `test_execute_with_type_translation_and_hash' is calling SQLite3::Database#type_translation=
SQLite3::Database#type_translation= is deprecated and will be removed
in version 2.0.0.
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:75:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:75:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:77:in `register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:78:in `register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:92:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:92:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:92:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:92:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:92:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:97:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:97:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:97:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:106:in `register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
...................~/dev/bugs/truffleruby/sqlite3-ruby/test/test_database.rb:87:in `test_get_first_row_with_type_translation_and_hash_results' is calling SQLite3::Database#type_translation=
SQLite3::Database#type_translation= is deprecated and will be removed
in version 2.0.0.
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:75:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:75:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:77:in `register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:78:in `register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:86:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:92:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:92:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:92:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:92:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:92:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:97:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:97:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:97:in `block in register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
~/dev/bugs/truffleruby/sqlite3-ruby/lib/sqlite3/translator.rb:106:in `register_default_translators' is calling `add_translator`.
Built in translators are deprecated and will be removed in version 2.0.0
....................................................................S.................~/dev/bugs/truffleruby/sqlite3-ruby/test/test_statement.rb:130:in `test_bind_blob' is calling SQLite3::ResultSet::ArrayWithTypesAndFields#types.  This method will be removed in
sqlite3 version 2.0.0, please call the `types` method on the SQLite3::ResultSet
object that created this object
.................................................................................................................F...org.truffleruby.language.control.RaiseException: Not a handle or a pointer (ArgumentError)
rake aborted!
Command failed with status (99): [~/.rubies/truffleruby-1.0.0-rc1...]
~/.gem/truffleruby/2.6.2/gems/hoe-3.17.1/lib/hoe/test.rb:83:in `block in define_test_tasks'
~/.rubies/truffleruby-1.0.0-rc14/bin/bundle:48:in `block in <main>'
~/.rubies/truffleruby-1.0.0-rc14/bin/bundle:40:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by aardvark179** [comment] 2019-03-25 12:40
I can't reproduce this on linux on `master`, I'll check on macos later.

**Comment by deepj** [comment] 2019-03-26 19:47
@aardvark179 Hello, have you gotten this issue on macOS? I'm just asking if I would add or re-try it again.

**Comment by aardvark179** [comment] 2019-04-01 18:20
Sorry for the slow reply. I have now managed to reproduce the issue, and have a fix I will put through CI shortly.

**Comment by aardvark179** [comment] 2019-04-02 18:38
The fix for this has been merged and should be in the next release.

**Closed by aardvark179** 2019-04-02 18:38 UTC
