### ISSUE TITLE
Support ActiveSupport gem.

### ISSUE THREAD

**Issue by phyllisstein** [oracle/truffleruby#1394] opened 2018-07-21 14:45 UTC
👋 Hey folks! I wanted to flag a glitch that I'm seeing with Rails' ActiveSupport gem. I know you've designated the project not quite ready for production, so it's a low-urgency problem, but I can't seem to get past it. Running TruffleRuby RC3, installed through RVM on macOS 10.14, any attempt to run a Rails command throws the following error:

```
~ ❯❯❯ rvm use truffleruby
Using /usr/local/rvm/gems/truffleruby-1.0.0-rc3

~ ❯❯❯ cd Desktop

~/Desktop ❯❯❯ rails new shuffle
Possibly unsupported Ruby implementation
/usr/local/rvm/gems/truffleruby-1.0.0-rc3/gems/activesupport-5.2.0/lib/active_support/core_ext/enumerable.rb:145:in `block (2 levels) in <top (required)>': undefined method `sum' for #<Module:0x120a> (NameError)
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/gems/activesupport-5.2.0/lib/active_support/core_ext/enumerable.rb:144:in `refine'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/gems/activesupport-5.2.0/lib/active_support/core_ext/enumerable.rb:144:in `block in <top (required)>'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/gems/activesupport-5.2.0/lib/active_support/core_ext/enumerable.rb:143:in `initialize'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/gems/activesupport-5.2.0/lib/active_support/core_ext/enumerable.rb:143:in `new'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/gems/activesupport-5.2.0/lib/active_support/core_ext/enumerable.rb:143:in `<top (required)>'
	from /usr/local/rvm/rubies/truffleruby-1.0.0-rc3/lib/mri/rubygems/core_ext/kernel_require.rb:68:in `gem_original_require'
	from /usr/local/rvm/rubies/truffleruby-1.0.0-rc3/lib/mri/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/gems/railties-5.2.0/lib/rails/command.rb:5:in `<top (required)>'
	from /usr/local/rvm/rubies/truffleruby-1.0.0-rc3/lib/mri/rubygems/core_ext/kernel_require.rb:68:in `gem_original_require'
	from /usr/local/rvm/rubies/truffleruby-1.0.0-rc3/lib/mri/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/gems/railties-5.2.0/lib/rails/cli.rb:12:in `<top (required)>'
	from /usr/local/rvm/rubies/truffleruby-1.0.0-rc3/lib/mri/rubygems/core_ext/kernel_require.rb:68:in `gem_original_require'
	from /usr/local/rvm/rubies/truffleruby-1.0.0-rc3/lib/mri/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/gems/railties-5.2.0/exe/rails:10:in `<top (required)>'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/bin/rails:23:in `load'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/bin/rails:23:in `load'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/bin/rails:23:in `<top (required)>'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/bin/truffleruby_executable_hooks:24:in `eval'
	from /usr/local/rvm/gems/truffleruby-1.0.0-rc3/bin/truffleruby_executable_hooks:24:in `<main>'
```

It looks like the problem chunk of code (<https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/enumerable.rb#L151-L156>) has been in ActiveSupport for some two years, so downgrading isn't really on the table. I can't quite reason out why TruffleRuby would be so confused about the scope of the refinement there, but maybe you have some insight.

Thanks in advance for your help, and good luck with what looks like a super exciting project!

**Comment by eregon** [comment] 2018-07-21 15:13
Hello, and thank you for the report!

Here is the relevant line in ActiveSupport 5.2.0:
https://github.com/rails/rails/blob/v5.2.0/activesupport/lib/active_support/core_ext/enumerable.rb#L145
Looks like `alias` doesn't find `Array#sum` for some reason.

@aardvark179 Could you take a look? I think it's related to the refinement module having a superclass in MRI: https://bugs.ruby-lang.org/issues/14744

**Comment by rsmything** [comment] 2018-07-24 23:00
the same problem with activesupport (6.0.0.alpha)

**Comment by aardvark179** [comment] 2018-07-25 18:37
This appears to now be working in `master`. There have been some changes recently around both method and constant lookup which might have fixed this, but I'm not sure which commit solved this particular issue.

**Comment by eregon** [comment] 2018-07-25 20:58
@aardvark179 Are you sure? I can reproduce the issue on master with just:
```ruby
using Module.new {
  refine Array do
    p self
    p self.ancestors
    alias :orig_sum :sum
  end
}
```

```
MRI:
#<refinement:Array@#<Module:0x000055b2f5b982c0>>
[#<refinement:Array@#<Module:0x000055b2f5b982c0>>, Array, Enumerable, Object, Kernel, BasicObject]

TruffleRuby:
#<refinement:Array@#<Module:0x8e>>
[#<refinement:Array@#<Module:0x8e>>]
ref.rb:5:in `block (2 levels) in <main>': undefined method `sum' for #<Module:0x94> (NameError)
```

I think this is what we talked about, refinement modules have a "superclass" in MRI and that's why `alias` works above for MRI but not for us. I [opened an issue](https://bugs.ruby-lang.org/issues/14744) and chatted about that with shugo and matz at RubyKaigi but there was no conclusion and I think it can't really change as now even Rails depends on this behavior.

**Comment by aardvark179** [comment] 2018-07-26 19:37
You're right, the library can be required, but that particular file was hidden behind a couple of `autoload`s.

At the moment we special case method definition inside a refinement module, and we'd need to refactor things like `alias` to do something similar. Sorting out method lookup or changing the ancestors won't be enough however as `include` and `prepend` also add methods to the refined class in MRI, and will need considerably more work to sort out in order for method resolution to work properly.

**Comment by aardvark179** [comment] 2018-08-07 09:55
A fix for this was merged in 6f1a4e94b9f568f4e3fcf5223956e4a9121e52b2.

**Comment by phyllisstein** [comment] 2018-08-07 13:43
How exciting, thanks for the update!

**Comment by eregon** [comment] 2018-08-25 15:55
This is now fixed, and `rails new myapp` succeeds.
`bundle exec rails s` doesn't work yet, but that is a different issue (currently `concurrent-ruby` fails to load, and I have another fix for `sass` being reviewed).
Therefore I will close this issue. This fix will be in the next release.
Thank you for the report!

**Closed by eregon** 2018-08-25 15:55 UTC
