### ISSUE TITLE
Unable to build bcrypt

### ISSUE THREAD

**Issue by kirs** [oracle/truffleruby#1734] opened 2019-08-16 20:31 UTC
I'm trying to install dependencies of a typical Rails app and `bundle install` failed on bcrypt:

```
jt ruby -Sgem install bcrypt -v '3.1.13'
Using Interpreted TruffleRuby: mxbuild/truffleruby-jvm
$ /Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/bin/ruby \
  --experimental-options \
  --core-load-path=/Users/kir/src/github.com/oracle/truffleruby/src/main/ruby/truffleruby \
  -Sgem \
  install \
  bcrypt \
  -v \
  3.1.13
Building native extensions. This could take a while...
ERROR:  Error installing bcrypt:
	ERROR: Failed to build gem native extension.

    current directory: /Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/bcrypt-3.1.13/ext/mri
/Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/bin/truffleruby -I /Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/mri -r ./siteconf20190816-37265-33vood.rb extconf.rb
creating Makefile

current directory: /Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/bcrypt-3.1.13/ext/mri
make "DESTDIR=" clean

current directory: /Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/bcrypt-3.1.13/ext/mri
make "DESTDIR="
compiling bcrypt_ext.c
compiling crypt_blowfish.c
compiling crypt_gensalt.c
compiling wrapper.c
linking shared-object bcrypt_ext.su
/usr/local/opt/llvm@4/bin/llvm-link: x86.bc: error: Could not open input file: No such file or directory
/usr/local/opt/llvm@4/bin/llvm-link: error loading file 'x86.bc'
/Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/cext/linker.rb:96:in `link_bitcode': Linker failed: ["/usr/local/opt/llvm@4/bin/llvm-link", "-o", "out.bc", "bcrypt_ext.bc", "crypt_blowfish.bc", "x86.bc", "crypt_gensalt.bc", "wrapper.bc"] (RuntimeError)
	from /Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/cext/linker.rb:27:in `main'
	from /Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/cext/linker.rb:150:in `<main>'
make: *** [bcrypt_ext.su] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/bcrypt-3.1.13 for inspection.
Results logged to /Users/kir/src/github.com/oracle/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/extensions/x86_64-darwin/19.3.0-dev-202f28ee/bcrypt-3.1.13/gem_make.out
```

I have truffle built from master (`202f28eea00ce1408108e5199830c857f2549d64`) on macOS `10.14.6`.

I'm able to `gem install bcrypt -v '3.1.13'` if I switch to MRI.

**Comment by chrisseaton** [comment] 2019-08-16 20:46
I'm sure we've run `bcrypt` in the past... but the issue is that it contains assembly code. We have an interpreter for C, some inline assembly, but not full assembly files. I'll take a better look later - maybe there is a C fallback for this assembly code we're not triggering for some reason - presumably there is in order to support non-Intel machines.

**Comment by chrisseaton** [comment] 2019-08-16 21:08
@aardvark179 knows most about C extensions at the moment - I've assigned to him.

**Comment by kirs** [comment] 2019-08-16 21:08
Thanks for a quick reply!
Hopefully this helps to make Truffle more ready for to run Rails :)

**Comment by aardvark179** [comment] 2019-08-18 13:06
Version 3.1.12 should work fine, 3.1.13 has changed to using some assembly code and a little customisation of the makefile which we'll need to fix.

**Comment by eregon** [comment] 2019-08-23 13:47
Note: we should add TruffleRuby in bcrypt's CI to avoid future regressions like this.

**Comment by eregon** [comment] 2019-10-22 15:43
With the new toolchain this seems to just work:
```
$ gem i bcrypt
Fetching bcrypt-3.1.13.gem
Building native extensions. This could take a while...
Successfully installed bcrypt-3.1.13
1 gem installed
$ ruby -rbcrypt -e 'p BCrypt::Password.create("secret").cost'
12
```

@aardvark179 Could you try adding truffleruby in BCrypt's CI and see if pass the tests?

**Comment by bjfish** [comment] 2020-03-31 15:46
This now works on the latest master: 20fe8661961ddcd56f5c9fc1d516429459bd8e81

I'll work on getting this on BCrypt CI.

**Closed by bjfish** 2020-03-31 15:46 UTC
Labels: cexts

**Comment by bjfish** [comment] 2020-03-31 16:20
PR to add to bcrypt CI: https://github.com/codahale/bcrypt-ruby/pull/223
