### ISSUE TITLE
compatability: floating point formatted differently by default

### ISSUE THREAD

**Issue by ntysdd** [oracle/truffleruby#1626] opened 2019-03-19 13:33 UTC
test code
`puts 1.0 / 7`

MRI
`0.14285714285714285`

TruffleRuby
`0.142857142857143`

this may prevent truffle ruby being a drop in replacement for MRI in some situation

**Comment by Maumagnaguagno** [comment] 2019-03-19 16:59
I was also surprised by this difference between MRI and TruffleRuby.
This difference should be stated in ``doc/user/compatibility.md`` or modified to match MRI behavior.

**Comment by chrisseaton** [comment] 2019-03-19 17:07
Thanks for the report! This is an unintended bug we'll fix - it's not intentionally different from MRI.

**Comment by chrisseaton** [comment] 2019-03-19 19:45
I can fix your specific test case, but it's a bit more complex making it exactly match MRI for all cases (and fixing yours caused others to break.)

MRI has custom floating-point formatting code, which doesn't match anything in C or Java. We may need to port their C code to Java.

JRuby has similar problems to us https://github.com/jruby/jruby/blob/5602787e537fe025c40abd785926e10cb34690b0/spec/tags/ruby/core/float/to_s_tags.txt.

**Comment by andrykonchin** [comment] 2022-08-01 17:31
Cannot reproduce the issue on TruffleRuby 22.2:

```
jt -q ruby -e "puts 1.0 / 7"
0.14285714285714285
```
I suppose it was fixed in https://github.com/oracle/truffleruby/commit/c99ec964fb51f8364c6919467e898db6969f4058.

Thank you for reporting.

**Comment by ntysdd** [comment] 2022-08-02 02:47
The Ruby rule for Float rounding indeed seems weird for programmers or IEEE 754 experts, and sometimes inconsistent.
https://bugs.ruby-lang.org/issues/12548

That said, I believe currently ruby intentionally choose this rounding mode to be friendly to common people in common cases. And that's because the underlying floats are actually binary floating points, while Ruby wants them to behave much like decimals (just like the method `round' implies).

A quick search in the ruby bug tracker reveal that quite a lot of bugs or regressions are about float rounding. The large number of bug reports show that quite a lot of existing code depends on that rounding behavior.

Ruby once choosed to change the rounding behavior in Ruby 2.4
https://github.com/ruby/spec/issues/294

And then got bug reports so they reverted the change.
https://bugs.ruby-lang.org/issues/12958


Ruby has RubySpec which explicitly specify the rounding behavior
https://github.com/ruby/spec/blob/master/core/float/round_spec.rb
https://github.com/ruby/spec/blob/master/core/kernel/shared/sprintf.rb

**Comment by ntysdd** [comment] 2022-08-02 02:48
The Ruby rule for Float rounding indeed seems weird for programmers or IEEE 754 experts, and sometimes inconsistent.
https://bugs.ruby-lang.org/issues/12548

That said, I believe currently ruby intentionally choose this rounding mode to be friendly to common people in common cases. And that's because the underlying floats are actually binary floating points, while Ruby wants them to behave much like decimals (just like the method `round' implies).

A quick search in the ruby bug tracker reveal that quite a lot of bugs or regressions are about float rounding. The large number of bug reports show that quite a lot of existing code depends on that rounding behavior.

Ruby once choosed to change the rounding behavior in Ruby 2.4
https://github.com/ruby/spec/issues/294

And then got bug reports so they reverted the change.
https://bugs.ruby-lang.org/issues/12958


Ruby has RubySpec which explicitly specify the rounding behavior
https://github.com/ruby/spec/blob/master/core/float/round_spec.rb
https://github.com/ruby/spec/blob/master/core/kernel/shared/sprintf.rb

**Comment by ntysdd** [comment] 2022-08-02 03:35
Currently truffleruby still gives different results for some values when using `sprintf", as can be seen in the commented out test cases https://github.com/oracle/truffleruby/commit/c99ec964fb51f8364c6919467e898db6969f4058 .

And indeed the MRI behavior is quite confusing, inconsistent with neither IEEE 754 nor Float.round(2, half: :even).

> It is inconsistent but fixing either way could cause problems. I vote for keeping as it is.
> Matz.

**Comment by andrykonchin** [comment] 2022-08-02 09:14
OK, so I keep this issue open as a reminder there is still a compatibility issue (mentioned on the commit):

Failed MRI tests:
```ruby
# test/mri/tests/ruby/test_sprintf.rb
assert_equal("5.02", sprintf("%.2f",5.015))
assert_equal("5.02", sprintf("%.2f",5.025))
```

**Comment by eregon** [comment] 2022-08-08 14:43
I think we are very close to CRuby behavior now and the original issue was fixed, hence I think we keep this closed.
TruffleRuby uses the same rounding behavior as CRuby now.
The remaining differences might even be CRuby bugs.

Is there an actual failing gem/app/software because of this? (if so a new issue would be better)

Because for these 2 cases it doesn't seem reasonable to round like that as https://github.com/oracle/truffleruby/commit/c99ec964fb51f8364c6919467e898db6969f4058#diff-e6b7eef2c84230530be3f22533ddfa9540b06866df07620195a970bef058c8ba explains.

**Closed by eregon** 2022-08-08 14:43 UTC
Labels: bug, compatibility
