### ISSUE TITLE
[Bug / Concurrency] CPU sampler during multi threaded operation yields error: Context cannot be entered on system threads

### ISSUE THREAD

**Issue by itarato** [oracle/truffleruby#3013] opened 2023-04-20 17:44 UTC
`cpusampler` is yielding threading errors a various runs. Example when running the thread spec tests:

```bash
jt test spec/ruby/optional/capi/thread_spec.rb -- --cpusampler
```

The output contains a few tens of:

```bash
[ruby] SEVERE: could not unblock thread inside blocking call in C extension because the context does not allow multithreading (Context cannot be entered on system threads.)
```

Another example is when running rails tests (not necessarily related to multithreading).

**Comment by eregon** [comment] 2023-04-21 12:27
Thanks for the report.

So this message comes from https://github.com/oracle/truffleruby/blob/a3d954350c96117cce3de561f2ce8fd0ebc33b39/src/main/java/org/truffleruby/core/thread/ThreadNodes.java#L694-L723

We need to execute the unblock function given to `rb_thread_call_without_gvl()`, so the thread inside the blocking function of `rb_thread_call_without_gvl()` can get out of it (e.g. out of a blocking syscall) and reach a Truffle safepoint, and then start its operation again.

What changed here is the CPUSampler now uses a system thread vs a embedder thread before, and system threads don't allow entering the context.

I don't know how to fix this, we need to execute the blocking function on some thread and that requires entering the context:
* We can't execute it on the current system thread due to system threads don't allow entering the context (this issue)
* We could use a Truffle safepoint/ThreadLocalAction, but to which thread? We can't use the Ruby main thread, maybe that's the one in `rb_thread_call_without_gvl()`. And we could have recursion problems if we use a ThreadLocalAction inside an Interrupter#interrupt.
* Obviously we can't use the thread in `rb_thread_call_without_gvl()`, that's the one stuck until we run the unblock function.
* I suppose we could create a new thread with Env#createThread, but that seems prohibitively expensive for every Interrupter#interrupt, i.e., every ThreadLocalAction affecting that thread while it's in `rb_thread_call_without_gvl()`.
* I suppose we could have an extra thread that we keep around for running that, but that is complicated and not working if there is any single-threaded language like JS/Python/etc. OTOH unblocking `rb_thread_call_without_gvl()` does require at least 2 parallel threads anyway (the thread blocked in it, the thread to run the unblock function), so maybe that thread could be created lazily the first time it is needed and not actually break polyglot. Also that thread will appear e.g. in Ruby's Thread.list which might be unexpected for user code.

We already have the `Timer nativeInterruptTimer` to send SIGVTALRM to interrupt NFI blocking syscalls. That's an embedder thread because there is no ThreadFactory for `java.util.Timer`. We don't control what it does so we can't reuse it for this. We also can't reuse the ReferenceProcessingThread because that's optional. My concern is we start to need a lot of threads to workaround Truffle limitations.

@chumer @jchalou What's is the envisioned solution here? Maybe tools should use embedder threads and not system threads to avoid this problem? It is a breaking change in CPUSampler from Ruby's POV.

**Comment by tzezula** [comment] 2023-04-21 12:42
@eregon Tools must use system threads to correctly work with Truffle isolates. The ordinary Java thread is not able to do a downcall to the host VM.

**Comment by eregon** [comment] 2023-04-21 12:49
@tzezula Why not? By `embedder thread` I mean `new java.lang.Thread()`.

**Comment by tzezula** [comment] 2023-04-21 13:13
The problem with `java.lang.Thread` in Truffle isolate is that it's not attached to host (HotSpot) JavaVM and has no host JNIEnv. When such a thread performs an operation that needs call to host, for example logging, it will fail.
The system threads created in the Truffle isolate are always attached to host in the enterpise implementation of [AbstractPolyglotImpl#createThreadScope()](https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.polyglot/src/org/graalvm/polyglot/impl/AbstractPolyglotImpl.java#L1185).

**Comment by chumer** [comment] 2023-04-21 13:40
@tzezula, we handle embedder threads in polyglot isolates. The problem is with threads created by the language that are not system or polyglot threads. They are unsupported now but will only fail if you use polyglot isolates.

No embedder threads are not the solution. Embedder threads are only intended for embedders, as the name suggests.

> What changed here is the CPUSampler now uses a system thread vs a embedder thread before, and system threads don't allow entering the context.

Why would you do anything on a CPU sampler thread? Sorry, I cannot yet see why system threads are problematic here. Can you elaborate?

**Comment by eregon** [comment] 2023-04-21 14:15
> Why would you do anything on a CPU sampler thread? Sorry, I cannot yet see why system threads are problematic here. > Can you elaborate?

So CPUSampler creates a samplerExecutionService system thread. And it `submitThreadLocal`. That then call the various `Interrupter`s on the current thread, including the Interrupter we care about it here to call the unblocking function of a thread in `rb_thread_call_without_gvl()`.

**Comment by tzezula** [comment] 2023-04-21 14:46
@chumer Right, we handle embedder threads in Truffle isolate. Embedder threads originated in the host VM and are always attached to it. But @eregon uses the term "embedder thread" for ordinary Java thread (neither system nor polyglot) created in the isolate.

**Comment by eregon** [comment] 2024-01-08 11:07
This is still an issue, @chumer @tzezula could you recommend a solution?

**Comment by eregon** [comment] 2024-01-08 11:34
One idea is if unblock functions do not need Sulong and do not need a Truffle context, we could execute the native function (via JNI, not NFI which needs the context) directly on the "system thread of CPUSampler", without needing to enter the Truffle context.
But https://github.com/oracle/truffleruby/blob/7c5bef1358b704a5cfa67ff17c4c763d567ff9e0/lib/cext/include/ruby/thread.h#L94-L131 and https://github.com/oracle/truffleruby/blob/master/lib/cext/include/ruby/internal/intern/thread.h#L330-L343
do not specify whether the unblock functions of `rb_thread_call_without_gvl*` can call `rb_*` or so, which would be a problem as those need to be entered in the context as almost all of them end up running some Sulong or Ruby code.
It might hold though.

self-note: some cleanup at `bd/system-thread-cext-interrupter`. I can try if that'd work after https://github.com/oracle/truffleruby/pull/3356 is merged

**Comment by eregon** [comment] 2024-01-09 15:43
I chatted with @chumer.
There is no perfect solution right now, so we have to use an extra thread or use JNI and then expect the unblock function will not call back to the Ruby C API (if so we need to test how it fails when that does not hold).
Longer-term there might be some kind of async-profiler for Truffle or the functionality to read the gust stacktrace of another thread without needing to run code on that thread, i.e., also working when that thread is in a blocking native call.

**Comment by eregon** [comment] 2024-01-09 18:06
I also tried just calling the unblock function via JNI (which would avoid the overhead of an extra thread and communicating with it for each sampling ThreadLocalAction).
That seems to work for `spec/ruby/optional/capi/thread_spec.rb`, but the spec also fails as a side-effect with `wakeup` raising `ThreadError: killed thread` since the unblock already ran and so the thread already terminated.
Which means CPUSampler has that side effect, unless the blocking function automatically retries after checking interrupts.
Obviously, not great but not sure there is a solution.
Also not clear to me if it's safe to call the unblock function multiple times, but it probably needs to be e.g. if the blocking function retries after checking interrupts (= `rb_thread_check_ints()`).

It'd be good to look at real-world usages of rb_thread_call_with_gvl and see how it behaves after being interrupted.
Ideally they would just retry after checking interrupts, but not sure that's what they do.

**Comment by eregon** [comment] 2024-01-10 14:18
Some more thoughts here:
* Maybe it would make sense to leaveAndEnter() for calling the blocking function. But since that may use `rb_thread_call_with_gvl()` and leaveAndEnter() does not support nested enter (IIRC) it's not an option. It would also of course not account the blocking functions at all which is not great.
* Maybe we could check if the CPUSampler is active and if so eagerly capture the guest stacktrace for that thread before executing the blocking function. It would have more overhead if there is 0 samples during that blocking function though (i.e., if it runs for less than 10ms).
* The old CPUSampler with ShadowStack would work well for that case and effectively provide the ability to query another thread stack at any time without any synchronization with it or running any code on it. OTOH it added an overhead for every CallTarget call (in call mode). IMO it would be valuable to add it again as an option, we still have the ShadowStack impl anyway for other tools.
* Obviously if there was a JVMCI API to get the guest stacktrace of another thread without needing to run code on it that'd be ideal, but it might take a while.

**Comment by nirvdrum** [comment] 2024-01-10 21:31
Ideally, I don't think we'd have to deal with the unblock function at all. I suppose that's what you mean with an analog to async_profiler. I don't want collecting a profile to affect the behavior of running code beyond performance overhead. Interrupting a blocking call that would naturally unblock is not ideal.

With that said, I'd settle for whatever we can do. I'm finding the sampling profiler doesn't work with a real world Rails application. There's a lot of thread calls going on without the GVL in the database driver, OpenSSL, ZLib, and others.

**Comment by eregon** [comment] 2024-01-11 13:13
> Ideally, I don't think we'd have to deal with the unblock function at all. I suppose that's what you mean with an analog to async_profiler. I don't want collecting a profile to affect the behavior of running code beyond performance overhead. Interrupting a blocking call that would naturally unblock is not ideal.

Yes, exactly, ideally we wouldn't need to, but currently the only way to get a guest stacktrace of another thread is to run `TruffleRuntime#iterateFrames` on that thread, which means using TruffleSafepoint and reaching a guest safepoint reasonably quickly.

> With that said, I'd settle for whatever we can do. I'm finding the sampling profiler doesn't work with a real world Rails application. There's a lot of thread calls going on without the GVL in the database driver, OpenSSL, ZLib, and others.

Note that many calls to `rb_thread_call_without_gvl()` use `RUBY_UBF_IO` as the unblock "function", which is sending SIGVTALRM to interrupt it and we already do this with JNI so that should work fine, except of course it also has the side effect of interrupting that blocking call (for every sample while in it) while it would not be interrupted in CRuby.

Ideally when such a blocking call is interrupted it would check interrupts (`rb_thread_check_ints()`) and then retry (e.g. until it doesn't get EINTR when using `RUBY_UBF_IO`).
So for example it should not abort and not retry if the unblock function is called.
But I'm not sure all calls to `rb_thread_call_without_gvl()` do this correctly.
They should though because CRuby uses the unblock function e.g. to run a Ruby-defined signal handler on the main Ruby thread and that can happen multiple times and should have side effects on the program besides what the signal handler does.

**Comment by eregon** [comment] 2024-01-12 15:37
Fix in https://github.com/oracle/truffleruby/pull/3385.
I verified that with the fix truffleruby succeeds in capturing samples while a thread is inside `rb_thread_call_without_gvl()` with a custom unblock function.
The profile for that thread is mostly attributed to rb_thread_check_ints()/rb_thread_call_with_gvl() because that's where the guest safepoint poll happens, which makes sense and is expected although the actual time is mostly spent in the blocking function but that itself can't be polled so that's expected safepoint bias. We still see those are above the `rb_thread_call_without_gvl()` in the flamegraph so it's rather clear.

**Comment by eregon** [comment] 2024-01-12 15:41
Here is the flamegraph from the new spec for `rb_thread_call_without_gvl()` with a custom unblock function that I'm talking about above:
![flamegraph](https://github.com/oracle/truffleruby/assets/168854/6095b1e7-7690-44e0-82d2-9529b5d4df14)

**Closed** 2024-01-15 20:09 UTC
Labels: bug, cexts, tooling
