### ISSUE TITLE
--engine.Mode=latency is three times faster than throughput when running rspecs

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#1985] opened 2020-04-03 18:59 UTC
I have a sample project where I run rspec tests , they are set up to run the rspec ruby process and the rails application ruby process with the following combinations

`--engine.Mode=latency` and `-engine.Mode=latency`
`--engine.Mode=latency` and `-engine.Mode=throughput`
`--engine.Mode=throughput` and `-engine.Mode=latency`
`--engine.Mode=throughput` and `-engine.Mode=throughput`

https://github.com/petenorth/schools-experience/actions/runs/69590250 (look for the run specs task)

What seems to be apparent is that running rspec in latency mode is 2-3 times faster (~15 mins vs 35-40mins)
 
Note that I think fix for https://github.com/oracle/truffleruby/issues/1977 resulted in an improvement for the rails application running in throughput mode but nothing was discernable for the rspec process or the rails running in latency mode.

**Comment by eregon** [comment] 2020-04-03 22:38
Thanks for creating the issue and setting this up in CI.
I think we should investigate why there is 3x difference, which seems higher than I expected.

Maybe we split too much for the specs, so we should try e.g. if disabling splitting and other flags helps.

**Comment by eregon** [comment] 2020-04-04 13:07
`ruby --help:internal --help:languages | grep clone` has some options to control splitting. I suspect `--ruby.call-with-block-always-clone` and `--ruby.yield-always-clone` might be too aggressive, we should experiment with setting them to `false`.

**Comment by eregon** [comment] 2020-04-07 10:31
I've started some runs in various configurations in https://github.com/eregon/schools-experience/runs/567227144?check_suite_focus=true

**Comment by eregon** [comment] 2020-04-07 12:00
Results of that run (there might be some noise, but the results seem fairly consistent):

| Options | Time to run specs |
| ---- | ---- |
| `--engine.Mode=latency` | 13min37s  |
| `--engine.Mode=default` | 43min05s |
| `--call-with-block-always-clone=false --yield-always-clone=false` | 36min41s |
| `--engine.Splitting=false` | 32min07s |
| `--engine.Inlining=false` | 16min11s |
| `--engine.Splitting=false --engine.Inlining=false` | 15min54s |

Disabling Inlining seems to have the most effect here: 43min ->  16min.
Disabling Splitting or splitting less has some effect too, but not nearly as much.

**Comment by petenorth** [comment] 2020-04-07 12:02
The option which I was surprised to see not being available in TruffleRuby was the max inlining caller size, seems to be associated with

https://github.com/oracle/truffleruby/blob/957d71d8c2856926754c255197145b496a2eac44/src/main/java/org/truffleruby/RubyContext.java#L193

**Comment by eregon** [comment] 2020-04-07 12:05
@petenorth That option has been renamed to `--engine.InliningNodeBudget=...` (it used to be `-Dgraal.TruffleInliningMaxCallerSize=...`).

**Comment by eregon** [comment] 2020-04-07 12:15
We should remove that line, since it enforces a minimum for that option value. We need to evaluate the impact on performance before though of course. The new not-yet-default inlining (`--engine.LanguageAgnosticInlining`) doesn't use that option.

**Comment by mukel** [comment] 2020-04-07 12:24
This is expected behavior for serial code e.g. unit tests, if compilation time is halved, then it's more likely for the compiled code to be used. It's a race between the compiler and the interpreter; you really want the compiler to win and still have something left to run. Even without inlining, compiled code will be much faster than the interpreter.

In a sibling project, we experienced this in the most unexpected way: making the interpreter slower can actually substantially speed up serial code.

**Comment by eregon** [comment] 2020-04-07 15:43
Also trying with the new inlining:

| Options | Time to run specs |
| ---- | ---- |
| `--engine.Mode=latency` | 16min22s  |
| `--engine.Mode=default` | 42min16s |
| `--call-with-block-always-clone=false --yield-always-clone=false` | 32min14s |
| `--engine.Splitting=false` | 34min22s |
| `--engine.Inlining=false` | 15min10s |
| `--engine.Splitting=false --engine.Inlining=false` | 15min19s |
| `--engine.LanguageAgnosticInlining` | 49min13s |
| `--engine.LanguageAgnosticInlining --engine.Splitting=false` | 36min13s |

**Comment by petenorth** [comment] 2021-04-06 15:44
Focusing on the run rspec step of

https://github.com/petenorth/schools-experience/actions/workflows/ruby-rspec-truffleruby.yml

The difference between `--engine.Mode=latency` and `--engine.Mode=throughput` is now very roughly 20%-25%.

`--engine.Mode=multitier` is better than `--engine.Mode=throughput`

Options (rspec, app=latency) |  Run Rspec (6/4/2021) | Run Rspec (5/4/2021) | Run Rspec (4/4/2021) | Run Rspec (3/4/2021)
------------ | -------------|-------------|-------------|-------------|
`latency`  | 9m 43s | 9m 22s | 10m 0s | 11m 1s
`throughput` | 12m 37s | 12m 17s | 12 m 43s | 12m 12s
`multitier` | 9m 48s | 13m 19s | 11m 59s | 11m 34 s

**Comment by eregon** [comment] 2021-04-07 13:32
Thank you for the numbers.
Note that MultiTier is enabled by default now, so it probably applied to all those 12 runs.
And the default `--engine.Mode` is `default` but it's the same as `throughput`.
`Mode=latency` is default mode + disabling splitting + disabling inlining.
Disabling inlining is a bit strange with MultiTier because then we will compile in tier 1 and tier 2 without inlining and very similarly. Mode=latency & MultiTier=false might be a bit faster, because then tier 1 is skipped and call counts are not compiled in at all (they are part of tier 1 compilations).

So here we see 20-25% between latency and default=throughput mode, when MultiTier is enabled for both, which seems reasonable.

I think we can close this because MultiTier is now default, and the time with the default config seems reasonable, and not far from --engine.Mode=latency.

**Closed by eregon** 2021-04-07 13:32 UTC
Labels: performance
