### ISSUE TITLE
bundle install: several issues on macOS

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1635] opened 2019-03-23 23:34 UTC
Today I've got several issues when bundle install

```
undle
Warning: the running version of Bundler (1.17.2) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from http://rubygems.org/.
Retrying fetcher due to error (2/4): RuntimeError <no message> (ConcurrentModificationException)
	from java.util.ArrayList.forEach(ArrayList.java:1260)
	from com.oracle.truffle.llvm.parser.metadata.MetadataValueList.consumeLocals(MetadataValueList.java:141)
	from com.oracle.truffle.llvm.parser.metadata.debuginfo.DebugInfoFunctionProcessor.process(DebugInfoFunctionProcessor.java:100)
	from com.oracle.truffle.llvm.parser.model.functions.LazyFunctionParser.parse(LazyFunctionParser.java:59)
	from com.oracle.truffle.llvm.parser.LazyToTruffleConverterImpl.generateCallTarget(LazyToTruffleConverterImpl.java:102)
	from com.oracle.truffle.llvm.parser.LazyToTruffleConverterImpl.convert(LazyToTruffleConverterImpl.java:94)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$LazyLLVMIRFunction.resolve(LLVMFunctionDescriptor.java:198)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor.getLLVMIRFunction(LLVMFunctionDescriptor.java:364)
	from com.oracle.truffle.llvm.runtime.interop.LLVMForeignCallNode.getCallTarget(LLVMForeignCallNode.java:199)
	from com.oracle.truffle.llvm.runtime.interop.LLVMForeignCallNodeGen.executeAndSpecialize(LLVMForeignCallNodeGen.java:79)
Translated to internal error.
Retrying fetcher due to error (3/4): RuntimeError Index 10 out of bounds for length 5 (ArrayIndexOutOfBoundsException)
	from com.oracle.truffle.llvm.runtime.types.StructureType.getElementType(StructureType.java:93)
	from com.oracle.truffle.llvm.parser.listeners.Function.getElementPointerType(Function.java:1083)
	from com.oracle.truffle.llvm.parser.listeners.Function.createGetElementPointer(Function.java:890)
	from com.oracle.truffle.llvm.parser.listeners.Function.record(Function.java:335)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.passRecordToParser(LLVMScanner.java:485)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.abbreviatedRecord(LLVMScanner.java:293)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanToOffset(LLVMScanner.java:280)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.access$700(LLVMScanner.java:54)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner$LazyScanner.scanBlock(LLVMScanner.java:527)
	from com.oracle.truffle.llvm.parser.model.functions.LazyFunctionParser.parse(LazyFunctionParser.java:58)
Translated to internal error.
Retrying fetcher due to error (4/4): RuntimeError Cannot index type: i32 (LLVMParserException)
Translated to internal error..
Your bundle is locked to cane (3.0.0), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the
author of cane (3.0.0) has removed it. You'll need to update your bundle to a version other than cane (3.0.0) that hasn't been removed in order to install.
```

**Comment by deepj** [comment] 2019-03-23 23:34
I haven't seen any with these issues yet

**Comment by eregon** [comment] 2019-03-24 10:05
Thanks for the report.

> I haven't seen any with these issues yet

What do you mean?

This is very likely a duplicate of https://github.com/oracle/truffleruby/issues/1565, so I'll close in favor of that issue.

**Closed by eregon** 2019-03-24 10:05 UTC

**Comment by deepj** [comment] 2019-03-24 15:58
@eregon 

I meant

```
RuntimeError <no message> (ConcurrentModificationException)
RuntimeError Cannot index type: i32 (LLVMParserException)
```

These errors I don't see in #1565

**Comment by eregon** [comment] 2019-03-24 17:12
@deepj Right, but it has the same source (`com.oracle.truffle.llvm.parser` in the backtrace): parsing bitcode was not thread-safe in Sulong and it should be fixed now.
