### ISSUE TITLE
pg_query :`process_args': Unknown argument: -exported_symbols_list (RuntimeError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1641] opened 2019-03-28 09:26 UTC
`pg_query` is a de/parser of PostgreSQL's queries. I don't use it directly, I just was curious if I can install it in TruffleRuby.

To reproduce:

```
gem install pg_query
```

Error:

```
Fetching pg_query-1.1.0.gem
Building native extensions. This could take a while...
	ERROR:  Error installing pg_query:
	ERROR: Failed to build gem native extension.

    current directory: ~/.gem/truffleruby/2.6.2/gems/pg_query-1.1.0/ext/pg_query
~/.rubies/truffleruby-1.0.0-rc14/bin/truffleruby -I ~/.rubies/truffleruby-1.0.0-rc14/lib/mri -r ./siteconf20190328-3317-4553dt.rb extconf.rb
compiling src/pg_query.c
compiling src/pg_query_fingerprint.c
compiling src/pg_query_json.c
compiling src/pg_query_json_plpgsql.c
compiling src/pg_query_normalize.c
compiling src/pg_query_parse.c
compiling src/pg_query_parse_plpgsql.c
compiling src/postgres/contrib_pgcrypto_sha1.c
compiling src/postgres/src_backend_catalog_namespace.c
compiling src/postgres/src_backend_catalog_pg_proc.c
compiling src/postgres/src_backend_lib_stringinfo.c
compiling src/postgres/src_backend_libpq_pqcomm.c
compiling src/postgres/src_backend_nodes_bitmapset.c
compiling src/postgres/src_backend_nodes_copyfuncs.c
compiling src/postgres/src_backend_nodes_equalfuncs.c
compiling src/postgres/src_backend_nodes_extensible.c
compiling src/postgres/src_backend_nodes_list.c
compiling src/postgres/src_backend_nodes_makefuncs.c
compiling src/postgres/src_backend_nodes_nodeFuncs.c
compiling src/postgres/src_backend_nodes_value.c
compiling src/postgres/src_backend_parser_gram.c
compiling src/postgres/src_backend_parser_parse_expr.c
compiling src/postgres/src_backend_parser_parser.c
compiling src/postgres/src_backend_parser_scan.c
compiling src/postgres/src_backend_parser_scansup.c
compiling src/postgres/src_backend_postmaster_postmaster.c
compiling src/postgres/src_backend_storage_ipc_ipc.c
compiling src/postgres/src_backend_storage_lmgr_s_lock.c
compiling src/postgres/src_backend_tcop_postgres.c
compiling src/postgres/src_backend_utils_adt_datum.c
compiling src/postgres/src_backend_utils_adt_expandeddatum.c
compiling src/postgres/src_backend_utils_adt_format_type.c
compiling src/postgres/src_backend_utils_adt_ruleutils.c
compiling src/postgres/src_backend_utils_error_assert.c
compiling src/postgres/src_backend_utils_error_elog.c
compiling src/postgres/src_backend_utils_hash_dynahash.c
compiling src/postgres/src_backend_utils_init_globals.c
compiling src/postgres/src_backend_utils_mb_encnames.c
compiling src/postgres/src_backend_utils_mb_mbutils.c
compiling src/postgres/src_backend_utils_mb_wchar.c
compiling src/postgres/src_backend_utils_misc_guc.c
compiling src/postgres/src_backend_utils_mmgr_aset.c
compiling src/postgres/src_backend_utils_mmgr_mcxt.c
compiling src/postgres/src_common_keywords.c
compiling src/postgres/src_common_psprintf.c
compiling src/postgres/src_pl_plpgsql_src_pl_comp.c
compiling src/postgres/src_pl_plpgsql_src_pl_funcs.c
compiling src/postgres/src_pl_plpgsql_src_pl_gram.c
compiling src/postgres/src_pl_plpgsql_src_pl_handler.c
compiling src/postgres/src_pl_plpgsql_src_pl_scanner.c
compiling src/postgres/src_port_erand48.c
compiling src/postgres/src_port_pgsleep.c
compiling src/postgres/src_port_qsort.c
compiling src/postgres/src_port_random.c
ar: creating archive libpg_query.a
cp: directory ~/.gem/truffleruby/2.6.2/gems/pg_query-1.1.0/ext/pg_query/../../spec/files does not exist
creating Makefile

current directory: ~/.gem/truffleruby/2.6.2/gems/pg_query-1.1.0/ext/pg_query
make "DESTDIR=" clean

current directory: ~/.gem/truffleruby/2.6.2/gems/pg_query-1.1.0/ext/pg_query
make "DESTDIR="
compiling pg_query_ruby.c
linking shared-object pg_query/pg_query.su
~/.rubies/truffleruby-1.0.0-rc14/lib/cext/linker.rb:67:in `process_args': Unknown argument: -exported_symbols_list (RuntimeError)
	from ~/.rubies/truffleruby-1.0.0-rc14/lib/cext/linker.rb:62:in `process_args'
	from ~/.rubies/truffleruby-1.0.0-rc14/lib/cext/linker.rb:21:in `main'
	from ~/.rubies/truffleruby-1.0.0-rc14/lib/cext/linker.rb:150:in `<main>'
make: *** [pg_query.su] Error 1

make failed, exit code 2

Gem files will remain installed in ~/.gem/truffleruby/2.6.2/gems/pg_query-1.1.0 for inspection.
Results logged to ~/.gem/truffleruby/2.6.2/extensions/x86_64-darwin/2.6.0/pg_query-1.1.0/gem_make.out
```

**Comment by aardvark179** [comment] 2019-04-02 14:53
This appears to be a duplicate of #1642 (different gem and command line option, but same problem). I'll close this one.

**Closed by aardvark179** 2019-04-02 14:53 UTC

**Comment by deepj** [comment] 2019-04-02 20:20
Hm, but this has been reported sooner. So the other issue is a duplicate...
