### ISSUE TITLE
bundle install is sometime terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1578] opened 2019-02-08 11:08 UTC
```
git clone https://github.com/rails/rails.git
cd rails
git checkout v5.2.2
bundle
```

Example (TruffleRuby 1.0.0 RC12):

```
activesupport git:(94b5cd3a20) bundle
Fetching https://github.com/matthewd/websocket-client-simple.git
Fetching https://github.com/rafaelfranca/queue_classic.git
Fetching https://github.com/matthewd/rb-inotify.git
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies....................................................................................................................................
Fetching rake 12.3.1
Installing rake 12.3.1
Fetching concurrent-ruby 1.0.5
Installing concurrent-ruby 1.0.5
Fetching i18n 1.1.1
Installing i18n 1.1.1
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.2 from source at `.`
Using builder 3.2.3
Fetching erubi 1.7.1
Installing erubi 1.7.1
Fetching mini_portile2 2.3.0
Installing mini_portile2 2.3.0
Fetching nokogiri 1.8.2
Installing nokogiri 1.8.2 with native extensions
Using rails-dom-testing 2.0.3
Using crass 1.0.4
Using loofah 2.2.3
Using rails-html-sanitizer 1.0.4
Using actionview 5.2.2 from source at `.`
Fetching rack 2.0.5
Installing rack 2.0.5
Fetching rack-test 1.0.0
Installing rack-test 1.0.0
fish: 'bundle' terminated by signal SIGSEGV (Address boundary error)
```

This happens exceptionally when I have open many apps on my machine (macOS Mojave and 8 GB RAM).

**Comment by deepj** [comment] 2019-02-08 17:52
Hm, I can reproduce it using Rails Gemfile (with several uncommented gems)

**Comment by deepj** [comment] 2019-02-08 19:51
Another fact, this happens only when many gems are needed to be installed.

**Comment by nirvdrum** [comment] 2019-02-08 20:12
I'm fairly certain this is a duplicate of #1490. If you don't mind, I'm going to close this out and move discussion over there.

**Closed by nirvdrum** 2019-02-08 20:12 UTC
