### ISSUE TITLE
numo-narray: codegen error

### ISSUE THREAD

**Issue by norswap** [oracle/truffleruby#1989] opened 2020-04-22 16:34 UTC
The `RBasic->flags` fix was merged in b9a3868f1077e3f4f91f7fad15fc536fb138747f.

It now fails with a different error from last time (though using a more recent Graal commit than configured in the repo):

```
ERROR:  Error installing numo-narray:
	ERROR: Failed to build gem native extension.

    current directory: /Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray
/Users/norswap/work/ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/bin/truffleruby -I /Users/norswap/work/ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/mri -r ./siteconf20200422-33968-meq99e.rb extconf.rb
checking for stdbool.h... yes
checking for stdint.h... yes
checking for bool in stdbool.h... yes
checking for u_int8_t in stdint.h... yes
checking for u_int16_t in stdint.h... yes
checking for int32_t in stdint.h... yes
checking for u_int32_t in stdint.h... yes
checking for int64_t in stdint.h... yes
checking for u_int64_t in stdint.h... yes
checking for exp10()... no
checking for rb_arithmetic_sequence_extract()... no
checking for rb_cComplex... yes
creating /Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/numo/extconf.h
creating Makefile

current directory: /Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray
make "DESTDIR=" clean

current directory: /Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray
make "DESTDIR="
compiling narray.c
compiling array.c
compiling step.c
compiling index.c
compiling ndloop.c
compiling data.c
ruby /Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_bit.c /Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/bit.rb
compiling t_bit.c
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:65:26: error: expected expression
                    y = *
                         ^
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:65:26: error: expected '}'
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:64:28: note: to match this '{'
                if (o2==0) {
                           ^
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:65:26: error: expected '}'
                    y = *
                         ^
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:55:34: note: to match this '{'
            for (; n>=NB; n-=NB) {
                                 ^
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:65:26: error: expected '}'
                    y = *
                         ^
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:54:16: note: to match this '{'
        } else {
               ^
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:65:26: error: expected '}'
                    y = *
                         ^
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:24:12: note: to match this '{'
    } else {
           ^
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:65:26: error: expected '}'
                    y = *
                         ^
/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c:4:1: note: to match this '{'
{
^
6 errors generated.
make: *** [t_bit.o] Error 1

make failed, exit code 2
```

_Originally posted by @norswap in https://github.com/oracle/truffleruby/issues/1891#issuecomment-617837974_

**Comment by norswap** [comment] 2020-04-22 16:35
cc @https://github.com/deepj

**Comment by eregon** [comment] 2020-04-22 17:58
On Linux it compiled fine for me:
```
Fetching numo-narray-0.9.1.6.gem
Building native extensions. This could take a while...
Successfully installed numo-narray-0.9.1.6
1 gem installed
```

Maybe you're simply missing a dependency? Does it work on MRI?

**Comment by norswap** [comment] 2020-04-23 12:07
That's interesting. Yes, it does work with MRI.

**Comment by eregon** [comment] 2020-04-23 12:35
Could you post what `/Users/norswap/.gem/truffleruby-jvm/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/tmpl_bit/binary.c` looks like? Sounds like the generation code goes wrong for some reason.

**Comment by norswap** [comment] 2020-04-23 12:51
There it is: https://pastebin.com/RHcvS33V

Haven't looked into this at all except for 5 minutes right now, but the file looks fine. What causes the errors? The C compiler? (but why would we pass a template to the compiler?) Also you'd expect a C compiler to choke on the ERB tags, and the error doesn't make any sense (it wants `y = * }`).

So I guess codegen? That is done by `cogen.rb` in the same directory, which uses `DefLib` from here: https://github.com/ruby-numo/numo-narray/blob/master/ext/numo/narray/gen/erbpp2.rb

**Comment by norswap** [comment] 2020-04-29 16:25
pebcak

**Comment by deepj** [comment] 2020-05-01 05:38
I guess this is not resolved. Tested todat with

```
truffleruby 20.2.0-dev-aa9d75a3, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

The same issue as above

**Comment by eregon** [comment] 2020-05-01 11:21
It installed for @norswap and Brandon on macOS, one issue might have been that `GEM_HOME` was set.

@deepj Does it install with MRI for you? Is GEM_HOME set in your case?

**Comment by deepj** [comment] 2020-05-01 12:03
@eregon 

Hm, chruby set `GEM_HOME` automatically what I remember. In both cases it's set (TruffleRuby and MRI 2.7)

MRI 2.7
```
$ gem install numo-narray
Building native extensions. This could take a while...
Successfully installed numo-narray-0.9.1.6
1 gem installed
```

**Comment by eregon** [comment] 2020-05-01 13:12
@deepj Just to be sure I would try to remove the `gems/numo-narray-0.9.1.6` directory entirely and then try to install again, maybe there are some leftover files that cause this failure.

If that still fails, could you share your `ext/numo/narray/gen/tmpl_bit/binary.c` or even better an archive of `gems/numo-narray-0.9.1.6` when it fails to install?

I'm trying to get a PR to `chruby` so it doesn't set `GEM_HOME` in https://github.com/postmodern/chruby/pull/431.
It's actually quite unsafe to share the same `GEM_HOME` for multiple TruffleRuby installations, which happens with the current release of `chruby` (`~/.gem/truffleruby/2.6.5` is used for many different versions of TruffleRuby).

Until that's merged and released, a workaround is to use my `do-no-set-gem-home` branch of chruby: https://github.com/eregon/chruby/tree/do-no-set-gem-home

**Comment by deepj** [comment] 2020-05-01 13:42
@eregon 

removing `gems/numo-narray-0.9.1.6` didn't help

Here is the archive of `gems/numo-narray-0.9.1.6`
[numo-narray-0.9.1.6.zip](https://github.com/oracle/truffleruby/files/4564437/numo-narray-0.9.1.6.zip)

**Comment by bjfish** [comment] 2020-05-01 16:23
I have a minimal reproduction case for the error:
```
s = "a" * 98792
s += "end"
require "fileutils"
file = "example.out"
open(file,"w").write(s)
p File.size(file)
```
Expected:
```
98795
```
Actual:
```
98304
```

**Comment by deepj** [comment] 2020-05-01 17:15
@bjfish Ee, what? Can you explain more why the above is related to this bug, please?

**Comment by bjfish** [comment] 2020-05-01 17:18
@deepj When I open the file `t_bit.c` I see that it stops abruptly as follows:
```
....
    rb_define_alias(cT, "count_1", "count_true");
    rb_define_alias(cT, "count", "count_true");
    rb_define_method(cT, "count_false", bit_count_false, -1);
    rb_define_alias(cT, "count_0", "count_false");
    rb_define_method(cT, "all?", bit_all_p, -1);
    rb_define_method(cT, "any?", bit_any_p, -1);
    rb_define_meth
```
This appears to be due to the file not writing all the bytes.  Do you have a similar `t_bit.c` file?

**Comment by deepj** [comment] 2020-05-01 17:22
In my case, it's cut on this place

<img width="453" alt="Screenshot 2020-05-01 at 19 21 23" src="https://user-images.githubusercontent.com/33736/80825584-382aaa00-8bd0-11ea-8ea3-6bbb35482971.png">

**Comment by bjfish** [comment] 2020-05-01 17:27
@deepj I have a similar but different cut off at line 3285 when I run with `gem install`.

**Comment by eregon** [comment] 2020-05-01 17:29
Good find!
`open(file,"w").write(s)` is unsafe and gives no guarantee to flush, we should fix it upstream to `close` explicitly or at least `flush`.
On MRI I guess it "works" due to running the finalizer (calling `close`) on exit, but that's very brittle.

**Comment by norswap** [comment] 2020-05-01 17:45
Do we run the finalizers? Shouldn't we make this work as-is? Feels like there are probably a lot of bombs like this waiting to happen.

**Comment by eregon** [comment] 2020-05-01 17:52
Relying on the finalizer for this is IMHO asking for trouble. It will keep the file descriptor open longer than expected, which might lead to fd leaks and eventually running out of file descriptors.

We tried to run finalizers on exit and we discovered they fail non-deterministically probably due to the order in which they are run. So it also seems hard to implement. There are also non-trivial interaction with `exit!` IIRC.
We also don't have a finalizer on IO instances at all currently, we expect Rubyists to use the block form of `open` or e.g., `File.write`, which is idiomatic and safer anyway.

So unless there is a valid use-case for it or these are very frequent issues, I think we should fix the bug upstream (it's a resource leak and potential race condition).

**Comment by bjfish** [comment] 2020-05-01 19:03
For reference, the `open` usage is here: 
https://github.com/ruby-numo/numo-narray/blob/3409fbf4f481c4d0275d8f6b724ac6412fa2acea/ext/numo/narray/gen/cogen.rb#L69

**Comment by eregon** [comment] 2020-05-01 19:35
@bjfish Could you make a PR and change that line to use `File.write`? (`$output` is always a filename)

**Comment by bjfish** [comment] 2020-05-01 20:26
@eregon Yes, I've created a PR here: https://github.com/ruby-numo/numo-narray/pull/159

**Comment by deepj** [comment] 2020-05-07 11:56
@eregon This can be closed. The fix was silently released https://github.com/ruby-numo/numo-narray/releases

I can compile it. Though, it takes a lot of time :( + There is another problem. I'll report it

**Closed** 2020-05-07 12:01 UTC
