### ISSUE TITLE
Invalid ElementType of Vector: VariableBitWidthType (java.lang.AssertionError)

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2364] opened 2021-05-28 15:35 UTC
My "truffleruby on docker" CI builds are [failing again](https://gitlab.com/honeyryderchuck/httpx/-/jobs/1301837287):

```

truffleruby: an internal exception escaped out of the interpreter,
please report it to https://github.com/oracle/truffleruby/issues.

```
Invalid ElementType of Vector: VariableBitWidthType (java.lang.AssertionError)
        from com.oracle.truffle.llvm.runtime.types.VectorType.setElementType(VectorType.java:80)
        from com.oracle.truffle.llvm.parser.listeners.Types.setType(Types.java:246)
        from com.oracle.truffle.llvm.parser.listeners.Types.record(Types.java:171)
        from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.passRecordToParser(LLVMScanner.java:434)
        from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.unabbreviatedRecord(LLVMScanner.java:450)
        from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanToOffset(LLVMScanner.java:164)
        from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanToEnd(LLVMScanner.java:143)
        from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.parseBitcode(LLVMScanner.java:102)
        from com.oracle.truffle.llvm.ParserDriver.parseBinary(ParserDriver.java:344)
        from com.oracle.truffle.llvm.ParserDriver.parseLibraryWithSource(ParserDriver.java:434)
        from com.oracle.truffle.llvm.ParserDriver.parseWithDependencies(ParserDriver.java:146)
        from com.oracle.truffle.llvm.ParserDriver.parseWithDependencies(ParserDriver.java:132)
        from com.oracle.truffle.llvm.ParserDriver.parse(ParserDriver.java:103)
        from com.oracle.truffle.llvm.DefaultLoader.load(DefaultLoader.java:45)
        from com.oracle.truffle.llvm.runtime.LLVMLanguage.parse(LLVMLanguage.java:508)
        from com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:854)
        from com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1508)
        from com.oracle.truffle.api.LanguageAccessor$LanguageImpl.parse(LanguageAccessor.java:311)
        from com.oracle.truffle.polyglot.PolyglotSourceCache.parseImpl(PolyglotSourceCache.java:94)
        from com.oracle.truffle.polyglot.PolyglotSourceCache.access$300(PolyglotSourceCache.java:56)
        from com.oracle.truffle.polyglot.PolyglotSourceCache$WeakCache.lookup(PolyglotSourceCache.java:223)
        from com.oracle.truffle.polyglot.PolyglotSourceCache.parseCached(PolyglotSourceCache.java:80)
        from com.oracle.truffle.polyglot.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:371)
        from com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.parseForLanguage(EngineAccessor.java:245)

**Comment by bjfish** [comment] 2021-05-28 15:42
From the CI logs:
```
	from /home/vendor/truffleruby/21.1.0/gems/grpc-1.38.0/src/ruby/lib/grpc/grpc.rb:22:in `<top (required)>'
```

This appears to be the same issue/error as the GRPC error:
https://github.com/oracle/truffleruby/issues/2247

**Comment by eregon** [comment] 2021-05-28 16:28
Yes, it's the same as #2247.
https://github.com/grpc/grpc/pull/24632 solves this but the gprc maintainers did not merge it yet (feel free to comment there).

I'll close as duplicate of https://github.com/oracle/truffleruby/issues/2247, you can follow that issue.

If this error did not happen before, I guess maybe grpc was added as a new dependency?

**Closed by eregon** 2021-05-28 16:28 UTC
Labels: duplicate, sulong-issue

**Comment by HoneyryderChuck** [comment] 2021-05-28 17:08
Thx for the pointers everyone. I did browse through the issues, but didn't find a mention for this specific error.

>  I guess maybe grpc was added as a new dependency?

Yes indeed, I've recently added a [grpc plugin to httpx](https://honeyryderchuck.gitlab.io/httpx/wiki/GRPC), and `grpc` is a test dependency.

**Comment by eregon** [comment] 2021-05-31 11:14
@HoneyryderChuck Do you think you could skip the grpc-related tests on TruffleRuby for the time being? (and also in the Gemfile, using `platforms: [:mri]`)

**Comment by HoneyryderChuck** [comment] 2021-05-31 11:35
sounds reasonable. will do.
