### ISSUE TITLE
grpc gem errors with LoadError when attempting to load c extension 

### ISSUE THREAD

**Issue by shidel-dev** [oracle/truffleruby#1837] opened 2019-11-30 23:35 UTC
## Environment
- truffleruby-19.3.0
- native mode
- OSX
- grpc-1.21.0

## Issue

When requiring the grpc gem, it attempts to load a native extension. See https://github.com/grpc/grpc/blob/master/src/ruby/lib/grpc/grpc.rb#L20

The compiled code exists on my machine at `$HOME/.rvm/gems/truffleruby-19.3.0/gems/grpc-1.21.0-universal-darwin/src/ruby/lib/grpc/2.6/grpc_c.bundle`.

I added a break point to the line number linked above, and I can confirm that the variable `distrib_lib_dir` equals `$HOME/.rvm/gems/truffleruby-19.3.0/gems/grpc-1.21.0-universal-darwin/src/ruby/lib/grpc/2.6`

**Comment by shidel-dev** [comment] 2019-11-30 23:57
Same issue for `google/protobuf`. It also builds a `.bundle` file. Maybe this is the issue? It seems like `.bundle` is osx specific?

**Comment by shidel-dev** [comment] 2019-12-01 00:09
this comment seems relevant https://github.com/oracle/truffleruby/issues/1819#issuecomment-557649759

**Comment by eregon** [comment] 2019-12-01 11:59
Thank you for the bug report.

Currently we use `.dylib` for C extensions on macOS, but it seems multiple gems hardcode `.bundle` (instead of using `RbConfig::CONFIG['DLEXT']`), so we'll try to change to that to avoid incompatibility. As a result we also look for `.rb` and `.dylib` on macOS but not for `.bundle`.

This is only part of the story though.
[grpc](https://rubygems.org/gems/grpc/versions) and [google-protobuf](https://rubygems.org/gems/google-protobuf/versions) both have binary (precompiled) gems:
```
$ ruby -v
truffleruby 19.3.0, like ruby 2.6.2, GraalVM CE Native [x86_64-linux]
$ gem i grpc
Fetching googleapis-common-protos-types-1.0.4.gem
Fetching google-protobuf-3.11.0-x86_64-linux.gem
Fetching grpc-1.25.0-x86_64-linux.gem
Successfully installed google-protobuf-3.11.0-x86_64-linux
Successfully installed googleapis-common-protos-types-1.0.4
Successfully installed grpc-1.25.0-x86_64-linux
3 gems installed
```

However these precompiled gems will not work on TruffleRuby, because the ABI and C extension implementation is different.
In fact on Linux the extension file is found but shows this ABI incompatibility:
```
$ ruby -rgrpc -e 'puts $"' 
/home/eregon/.rubies/truffleruby-19.3.0/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require':
The file 'grpc_c.so' is not a bitcode file nor an ELF or Mach-O object file with an embedded bitcode section. (LLVMParserException) (RuntimeError)
Translated to internal error
	from /home/eregon/.rubies/truffleruby-19.3.0/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/eregon/.rubies/truffleruby-19.3.0/lib/gems/gems/grpc-1.25.0-x86_64-linux/src/ruby/lib/grpc/grpc.rb:20:in `<top (required)>'
	from /home/eregon/.rubies/truffleruby-19.3.0/lib/gems/gems/grpc-1.25.0-x86_64-linux/src/ruby/lib/grpc.rb:19:in `require_relative'
	from /home/eregon/.rubies/truffleruby-19.3.0/lib/gems/gems/grpc-1.25.0-x86_64-linux/src/ruby/lib/grpc.rb:19:in `<top (required)>'
	from /home/eregon/.rubies/truffleruby-19.3.0/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
	from /home/eregon/.rubies/truffleruby-19.3.0/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
	from -e:1:in `require'
	from -e:1:in `<main>'
```

So we need to find out how to tell RubyGems to not use precompiled gems, or somehow communicate to RubyGems that different Ruby engines might have different ABIs.

**Comment by eregon** [comment] 2019-12-01 12:05
A potential workaround until then would be to force compilation for source, to not use the precompiled gem, which can be done with:
```
$ gem install --platform ruby MYGEM
```

**Comment by eregon** [comment] 2019-12-01 12:15
However, that currently fails for `google-protobuf`, because of a `switch` on `VALUE`:
```
repeated_field.c:131:7: error: statement requires expression of integer type ('VALUE' (aka 'void *') invalid)
      switch (rb_range_beg_len(arg, &beg, &len, self->size, 0)) {
      ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
https://github.com/protocolbuffers/protobuf/blob/e6c5a3b57d20384775950c4f85310e82a4f7a69b/ruby/ext/google/protobuf_c/repeated_field.c#L131-L138

That is a current limitation we hope to solve soon:
https://github.com/oracle/truffleruby/blob/master/doc/user/compatibility.md#value-is-a-pointer

There are also quite a few warnings (those seem harmless though) because `google-protobuf`'s `extconf.rb` forces C90:
https://github.com/protocolbuffers/protobuf/blob/e6c5a3b57d20384775950c4f85310e82a4f7a69b/ruby/ext/google/protobuf_c/extconf.rb#L5-L9
and our C extension implementation uses more recent features.

**Comment by shidel-dev** [comment] 2019-12-08 18:53
@eregon I am experimenting with things a bit, and when I try and compile without the switch statement, I run into a different error.

```
duplicate symbol '_rb_nativethread_lock_lock' in:
    protobuf.o
    defs.o
duplicate symbol '_rb_nativethread_lock_destroy' in:
    protobuf.o
    defs.o
duplicate symbol '_rb_nativethread_lock_initialize' in:
    protobuf.o
    defs.o
duplicate symbol '_rb_tr_gc_guard' in:
    protobuf.o
    defs.o
duplicate symbol '_rb_nativethread_lock_unlock' in:
    protobuf.o
    defs.o
duplicate symbol '_rb_string_value' in:
    protobuf.o
    defs.o
duplicate symbol '_rb_string_value_ptr' in:
    protobuf.o
    defs.o
duplicate symbol '_rb_string_value_cstr' in:
    protobuf.o
    defs.o
duplicate symbol '_rb_tr_scan_args' in:
    protobuf.o
    defs.o
duplicate symbol '_rb_nativethread_lock_destroy' in:
    protobuf.o
    message.o
duplicate symbol '_rb_nativethread_lock_initialize' in:
    protobuf.o
    message.o
duplicate symbol '_rb_nativethread_lock_lock' in:
    protobuf.o
    message.o
duplicate symbol '_rb_tr_gc_guard' in:
    protobuf.o
    message.o
duplicate symbol '_rb_nativethread_lock_unlock' in:
    protobuf.o
    message.o
duplicate symbol '_rb_string_value' in:
    protobuf.o
    message.o
duplicate symbol '_rb_string_value_ptr' in:
    protobuf.o
    message.o
duplicate symbol '_rb_string_value_cstr' in:
    protobuf.o
    message.o
duplicate symbol '_rb_tr_scan_args' in:
    protobuf.o
    message.o
duplicate symbol '_rb_nativethread_lock_initialize' in:
    protobuf.o
    map.o
duplicate symbol '_rb_nativethread_lock_lock' in:
    protobuf.o
    map.o
duplicate symbol '_rb_tr_gc_guard' in:
    protobuf.o
    map.o
duplicate symbol '_rb_nativethread_lock_destroy' in:
    protobuf.o
    map.o
duplicate symbol '_rb_nativethread_lock_initialize' in:
    protobuf.o
    storage.o
duplicate symbol '_rb_nativethread_lock_lock' in:
    protobuf.o
    storage.o
duplicate symbol '_rb_nativethread_lock_unlock' in:
    protobuf.o
    storage.o
duplicate symbol '_rb_tr_gc_guard' in:
    protobuf.o
    storage.o
duplicate symbol '_rb_nativethread_lock_unlock' in:
    protobuf.o
    map.o
duplicate symbol '_rb_string_value' in:
    protobuf.o
    map.o
duplicate symbol '_rb_string_value_ptr' in:
    protobuf.o
    map.o
duplicate symbol '_rb_string_value_cstr' in:
    protobuf.o
    map.o
duplicate symbol '_rb_tr_scan_args' in:
    protobuf.o
    map.o
duplicate symbol '_rb_nativethread_lock_destroy' in:
    protobuf.o
    storage.o
duplicate symbol '_rb_string_value' in:
    protobuf.o
    storage.o
duplicate symbol '_rb_string_value_ptr' in:
    protobuf.o
    storage.o
duplicate symbol '_rb_string_value_cstr' in:
    protobuf.o
    storage.o
duplicate symbol '_rb_tr_scan_args' in:
    protobuf.o
    storage.o
duplicate symbol '_rb_nativethread_lock_destroy' in:
    protobuf.o
    repeated_field.o
duplicate symbol '_rb_nativethread_lock_initialize' in:
    protobuf.o
    repeated_field.o
duplicate symbol '_rb_nativethread_lock_lock' in:
    protobuf.o
    repeated_field.o
duplicate symbol '_rb_tr_gc_guard' in:
    protobuf.o
    repeated_field.o
duplicate symbol '_rb_nativethread_lock_unlock' in:
    protobuf.o
    repeated_field.o
duplicate symbol '_rb_string_value' in:
    protobuf.o
    repeated_field.o
duplicate symbol '_rb_string_value_ptr' in:
    protobuf.o
    repeated_field.o
duplicate symbol '_rb_string_value_cstr' in:
    protobuf.o
    repeated_field.o
duplicate symbol '_rb_tr_scan_args' in:
    protobuf.o
    repeated_field.o
duplicate symbol '_rb_nativethread_lock_lock' in:
    protobuf.o
    encode_decode.o
duplicate symbol '_rb_tr_gc_guard' in:
    protobuf.o
    encode_decode.o
duplicate symbol '_rb_nativethread_lock_initialize' in:
    protobuf.o
    encode_decode.o
duplicate symbol '_rb_nativethread_lock_destroy' in:
    protobuf.o
    encode_decode.o
duplicate symbol '_rb_nativethread_lock_unlock' in:
    protobuf.o
    encode_decode.o
duplicate symbol '_rb_string_value' in:
    protobuf.o
    encode_decode.o
duplicate symbol '_rb_string_value_ptr' in:
    protobuf.o
    encode_decode.o
duplicate symbol '_rb_string_value_cstr' in:
    protobuf.o
    encode_decode.o
duplicate symbol '_rb_tr_scan_args' in:
    protobuf.o
    encode_decode.o
ld: 54 duplicate symbols for architecture x86_64
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [protobuf_c.dylib] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/make...]
```

This does not occur when building with ruby 2.6.5

**Comment by eregon** [comment] 2019-12-15 10:21
I switched to using `.bundle` (instead of `.dylib` before) for C extensions on Darwin, like MRI: 783d5295838cb9b5c129a33a7e1a5cff2df3f7df.
So at least the extension file should be found on macOS too now.

We still need to find a way to avoid using extensions precompiled for MRI and instead always compile from source. cc @chrisseaton

**Comment by shidel-dev** [comment] 2019-12-20 04:43
i'll have another stab at this when the next release is cut.

**Comment by eregon** [comment] 2020-01-16 14:00
OK, I also see these duplicate symbols, which is also reported as #1879.

**Comment by eregon** [comment] 2020-01-16 15:04
These duplicate symbol warnings seem to be caused by `-std=gnu90` in
https://github.com/protocolbuffers/protobuf/blob/f4b6e4a561480fa6727e9d9a4537c404c23ff5f6/ruby/ext/google/protobuf_c/extconf.rb#L6
which apparently [inverts](https://en.wikipedia.org/wiki/Inline_function#gnu89) the meaning of `inline` and `extern inline`.

Removing `-std=gnu90` lets it link, but the real fix is to annotate our "inline" functions in a portable way (which is tricky with dialects of C giving it different meanings).

**Comment by eregon** [comment] 2020-01-16 16:03
I have a proper fix for linking, now with changing the `switch` to `if/else`, the gem compiles and `require` succeeds. Tests don't pass yet.

**Comment by rafaelfranca** [comment] 2020-01-16 20:06
This issue is related https://github.com/rubygems/rubygems/issues/2945

**Comment by eregon** [comment] 2020-02-01 11:29
Not reusing MRI-precompiled gems on TruffleRuby is fixed with https://github.com/oracle/truffleruby/commit/6da9d7c2acf4adcd6bda5c49c2a76027ed02feb6.

`switch (VALUE)` is not specific to this issue but a docuemented incompatibility which we plan to try to fix soon, so I'd like to close this issue.

**Closed by eregon** 2020-02-01 11:29 UTC
Labels: cexts, priority
