### ISSUE TITLE
Strings in a Range

### ISSUE THREAD

**Issue by rickhull** [oracle/truffleruby#2183] opened 2020-12-08 22:42 UTC
~~test case: `[*1..3, *8..10] #=> [1, 2, 3, 8, 9, 10]`~~

~~That shows the expected result.  I am not certain of the actual result in truffleruby.  I can't easily test against truffleruby directly.  I discovered this issue via a GitHub Actions testing matrix on one of my projects.  I am testing the result for `Array#size`, and on truffleruby and truffleruby-head, I get 2, instead of the expected number (24 for my specific case).~~

~~jruby and MRI > 2.4 give the expected result.  I believe that enclosing the range in parens will yield the expected result on truffleruby, e.g. `[*(1..3), *(8..10)] #=> [1, 2, 3, 8, 9, 10]`~~

Here is the actual output for my test failure: https://github.com/rickhull/compsci/runs/1520244260?check_suite_focus=true  Note, there are 2 errors in that output, neither of which are errors for jruby.  I will file a separate error for the RubyBignum issue.  I presented this info in the truffleruby slack channel and was told to file an issue here.

**Comment by bjfish** [comment] 2020-12-08 22:45
For the names failure, I can reproduce the issue with this example:
 ruby -e "a = [*'Α'..'Ρ', *'Σ'..'Ω']; p a.size"

 Expected
 `24`

 Actual
 `2`

**Comment by chrisseaton** [comment] 2020-12-08 22:45
TruffleRuby `master`:

```
irb(main):001:0> a = [*1..3, *8..10]
=> [1, 2, 3, 8, 9, 10]
irb(main):002:0> a.size
=> 6
```

MRI compatible:

```
irb(main):001:0> a = [*1..3, *8..10]
=> [1, 2, 3, 8, 9, 10]
irb(main):002:0> a.size
=> 6
```

Both of these look like bad specialisations?

**Comment by rickhull** [comment] 2020-12-08 22:48
Ah, then perhaps it is something with unicode?  I apologize if the test case was misleading.  I didn't have a way to actually try on truffleruby without manipulating the GH action CI.

**Comment by eregon** [comment] 2020-12-09 13:26
> I didn't have a way to actually try on truffleruby without manipulating the GH action CI.

Is there any issue to install TruffleRuby on your system?
It should be fairly easy if you use a Ruby installer/manager.

**Comment by rickhull** [comment] 2020-12-09 13:31
At the moment, I am using a single Linux VM with limited drive space, running NixOS.  It is near capacity as it stands.  This is a solveable problem but not near the top of my stack at the moment.  I'm happy to SSH somewhere or use a web REPL to test snippets in the meantime.

**Comment by eregon** [comment] 2020-12-09 14:34
Simple reproducer:
```
$ ruby -e "p ('Α'..'Ρ').to_a"
["Α", "Β", "Γ", "Δ", "Ε", "Ζ", "Η", "Θ", "Ι", "Κ", "Λ", "Μ", "Ν", "Ξ", "Ο", "Π", "Ρ"]
$ truffleruby -e "p ('Α'..'Ρ').to_a"
["Î"]
```
Looks like some issues with handling Strings in Range.
`truffleruby -e "p 'Α'.succ.succ"` #=> "Γ" is fine, so it seems we should iterate with `succ` for Strings in a Range.

**Comment by eregon** [comment] 2020-12-12 12:53
Might be related:
https://bugs.ruby-lang.org/issues/5607
https://bugs.ruby-lang.org/issues/13663

So it seems `<=>` cannot be used for a Range of Strings, as it's inconsistent with `String#succ`.

**Comment by rickhull** [comment] 2020-12-12 14:23
I see some history here :D

> Updated by Eregon (Benoit Daloze) about 9 years ago

**Comment by eregon** [comment] 2020-12-14 12:10
@bjfish Could you take a look at this?

**Comment by rickhull** [comment] 2020-12-15 18:11
I see https://bugs.ruby-lang.org/issues/13663#note-4

> At the December 2020 development meeting, matz (Yukihiro Matsumoto) agreed the current behavior is expected and this is not a bug.

If I may restate the issue in MRI:

```
# z sorts *after* aa
"z" <=> "aa"
#=> 1

# yet aa succs *after* z
"z".succ
#=> "aa"
```

MRI is just going to live with this seeming inconsistency.  I'm not sure how it affects TruffleRuby for the issue I discovered.

**Comment by bjfish** [comment] 2020-12-16 15:38
This is now fixed at https://github.com/oracle/truffleruby/commit/06d3f3da4c06dd3154d838d30697d72f8234e927.

**Closed by bjfish** 2020-12-16 15:38 UTC
Labels: bug
