### ISSUE TITLE
tilt: [ruby] WARNING: negative line number utf8.erb:-8 not supported in #class/module_eval - will be reported as starting at 1

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1481] opened 2018-11-24 15:16 UTC
I see this issue in many cases, in Sinatra or Capybara specs. No issue under MRI.

**utf8.erb**

```erb
<h1><%= value %></h1>
Ingen vill veta var du köpt din tröja.
```

To reproduce:

```ruby
require 'tilt'
require 'erb'

template = Tilt.new('utf8.erb')
puts template.render(nil, value: 'something')
```

Warning:

```
[ruby] WARNING: negative line number utf8.erb:-8 not supported in #class/module_eval - will be reported as starting at 1
```

**Comment by deepj** [comment] 2018-11-25 22:37
I got it. But the problem with is, this generates a lot of theses messages in quite a lot cases. Not only tilt, but many others.

**Comment by chrisseaton** [comment] 2018-11-26 09:55
Closing as a dupe of #1482 as it's the same problem.

**Closed by chrisseaton** 2018-11-26 09:55 UTC
