### ISSUE TITLE
hiredis-client cannot load such file -- redis_client/hiredis_connection.so

### ISSUE THREAD

**Issue by skirushkin** [oracle/truffleruby#3318] opened 2023-11-15 14:56 UTC
Hi! Thank you for an amazing work!

I'm trying to migrate my current project to truffleruby 
It use hiredis-client from https://github.com/redis-rb/redis-client for better redis socket implementation.
But on load it gives me an error
```
[2] pry(main)> require "redis_client/hiredis_connection"
LoadError: cannot load such file -- redis_client/hiredis_connection.so
from <internal:core> core/kernel.rb:236:in `gem_original_require'
```
I did't try it to run in docker yet. 
I'm using mackbook m1 and latest truffleruby-dev from rbenv.

**Comment by eregon** [comment] 2023-11-15 18:15
Thanks for the report.
This reproduces it and shows the backtrace unlike pry:
```
$ gem install hiredis-client
$ ruby -e 'require "redis_client/hiredis_connection"'
<internal:core> core/kernel.rb:236:in `gem_original_require': cannot load such file -- redis_client/hiredis_connection.so (LoadError)
	from <internal:/home/eregon/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/hiredis-client-0.18.0/lib/redis_client/hiredis_connection.rb:4:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from <internal:/home/eregon/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb>:159:in `require'
	from <internal:core> core/unbound_method.rb:18:in `bind_call'
	from <internal:core> core/kernel.rb:272:in `require'
	from -e:1:in `<main>'
<internal:core> core/kernel.rb:236:in `gem_original_require': cannot load such file -- redis_client/hiredis_connection (LoadError)
	from <internal:/home/eregon/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:core> core/unbound_method.rb:18:in `bind_call'
	from <internal:core> core/kernel.rb:272:in `require'
	from -e:1:in `<main>'
```

**Comment by eregon** [comment] 2023-11-15 18:17
It's due to https://github.com/redis-rb/redis-client/blob/ba8848b195404ab337daa94647f600b1a4506f0f/hiredis-client/ext/redis_client/hiredis/extconf.rb#L11

**Comment by eregon** [comment] 2023-11-15 18:25
I'll try changing the condition and adding truffleruby in CI, WIP at https://github.com/redis-rb/redis-client/compare/master...eregon:redis-client:truffleruby

**Comment by eregon** [comment] 2023-11-15 18:27
A workaround until then is to use `redis-client` instead of `hiredis-client`.

**Comment by eregon** [comment] 2023-11-15 18:31
So the way this is supposed to work is users should not require `redis_client/hiredis_connection` (which is gem internals) but instead they should require `hiredis-client`.
And that works fine on TruffleRuby.
So I think it's fine to close this then, as that seems to just work.
PR to add truffleruby in redis-client CI: https://github.com/redis-rb/redis-client/pull/152

**Closed by eregon** 2023-11-15 18:31 UTC
Labels: cexts, third-party-issue

**Comment by byroot** [comment] 2023-11-15 21:38
Also I'd question whether hiredis-client is really faster than redis-client on TruffleRuby.

It may not be worth using it at all.
