### ISSUE TITLE
[truffle] opt fail         Truffle::CExt#rb_data_typed_object_wrap (1.0.0-rc6)

### ISSUE THREAD

**Issue by sbellware** [oracle/truffleruby#1422] opened 2018-09-05 21:35 UTC
I see this error intermittently while installing gems, and sometimes when running code.

I'm not sure if this is significant, but thought I'd share it.

This happens under 1.0.0-rc6 when installing the [test_bench](https://github.com/ntl/test-bench) gem ([https://rubygems.org/gems/test_bench](https://rubygems.org/gems/test_bench)) under bundler:

```
Installing test_bench 1.3.4
[truffle] opt fail         Truffle::CExt#rb_data_typed_object_wrap /Users/sbellware/.rubies/truffleruby-1.0.0-rc6/lib/truffle/truffle/cext.rb:1341|Reason org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation()
org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation()
	at org.truffleruby.core.module.ModuleOperations.includesModule(ModuleOperations.java:42)
	at org.truffleruby.core.module.ModuleOperations.assignableTo(ModuleOperations.java:56)
	at org.truffleruby.core.module.ModuleOperations.canBindMethodTo(ModuleOperations.java:71)
	at org.truffleruby.language.methods.CanBindMethodToModuleNode.canBindMethodTo(CanBindMethodToModuleNode.java:48)
	at org.truffleruby.language.methods.CanBindMethodToModuleNode.canBindMethodToUncached(CanBindMethodToModuleNode.java:44)
	at org.truffleruby.language.methods.CanBindMethodToModuleNodeGen.executeCanBindMethodToModule(CanBindMethodToModuleNodeGen.java:47)
	at org.truffleruby.core.method.UnboundMethodNodes$BindNode.bind(UnboundMethodNodes.java:79)
	at org.truffleruby.core.method.UnboundMethodNodesFactory$BindNodeFactory$BindNodeGen.execute(UnboundMethodNodesFactory.java:328)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:226)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:86)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:70)
	at org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:190)
	at org.truffleruby.language.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:94)
	at org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:43)
	at org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:108)
	at org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:99)
	at org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:79)
	at org.truffleruby.language.locals.WriteLocalVariableNode.execute(WriteLocalVariableNode.java:36)
	at org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:39)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:31)
	at org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:38)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:258)

[truffle] opt fail         rb_data_typed_object_wrap                                   |Reason org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation()
org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation()
	at org.truffleruby.core.module.ModuleOperations.includesModule(ModuleOperations.java:42)
	at org.truffleruby.core.module.ModuleOperations.assignableTo(ModuleOperations.java:56)
	at org.truffleruby.core.module.ModuleOperations.canBindMethodTo(ModuleOperations.java:71)
	at org.truffleruby.language.methods.CanBindMethodToModuleNode.canBindMethodTo(CanBindMethodToModuleNode.java:48)
	at org.truffleruby.language.methods.CanBindMethodToModuleNode.canBindMethodToUncached(CanBindMethodToModuleNode.java:44)
	at org.truffleruby.language.methods.CanBindMethodToModuleNodeGen.executeCanBindMethodToModule(CanBindMethodToModuleNodeGen.java:47)
	at org.truffleruby.core.method.UnboundMethodNodes$BindNode.bind(UnboundMethodNodes.java:79)
	at org.truffleruby.core.method.UnboundMethodNodesFactory$BindNodeFactory$BindNodeGen.execute(UnboundMethodNodesFactory.java:328)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:226)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:86)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:70)
	at org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:190)
	at org.truffleruby.language.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:94)
	at org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:43)
	at org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:108)
	at org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:99)
	at org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:79)
	at org.truffleruby.language.locals.WriteLocalVariableNode.execute(WriteLocalVariableNode.java:36)
	at org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:39)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:31)
	at org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:38)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:226)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:86)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:70)
	at org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:190)
	at org.truffleruby.language.dispatch.CachedSingletonDispatchNode.executeDispatch(CachedSingletonDispatchNode.java:93)
	at org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:43)
	at org.truffleruby.language.dispatch.CallDispatchHeadNode.call(CallDispatchHeadNode.java:41)
	at org.truffleruby.interop.RubyMessageResolution$ForeignInvokeNode.access(RubyMessageResolution.java:351)
	at org.truffleruby.interop.RubyMessageResolutionForeign$ForeignInvokeSubNode.accessWithTarget(RubyMessageResolutionForeign.java:254)
	at org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignInvokeSubNodeGen.executeWithTarget(RubyMessageResolutionForeignFactory.java:235)
	at org.truffleruby.interop.RubyMessageResolutionForeign$ForeignInvokeSubNode$INVOKERootNode.execute(RubyMessageResolutionForeign.java:277)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:226)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:86)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:70)
	at com.oracle.truffle.api.interop.InteropAccessNode.doCached(InteropAccessNode.java:186)
	at com.oracle.truffle.api.interop.InteropAccessNodeGen.executeImpl(InteropAccessNodeGen.java:35)
	at com.oracle.truffle.api.interop.InteropAccessNode.execute(InteropAccessNode.java:82)
	at com.oracle.truffle.api.interop.ForeignAccess.sendInvoke(ForeignAccess.java:496)
	at com.oracle.truffle.llvm.nodes.intrinsics.interop.LLVMTruffleInvoke.doInvoke(LLVMTruffleInvoke.java:102)
	at com.oracle.truffle.llvm.nodes.intrinsics.interop.LLVMTruffleInvoke.cachedId(LLVMTruffleInvoke.java:119)
	at com.oracle.truffle.llvm.nodes.intrinsics.interop.LLVMTruffleInvokeNodeGen.executeGeneric(LLVMTruffleInvokeNodeGen.java:50)
	at com.oracle.truffle.llvm.nodes.intrinsics.llvm.LLVMIntrinsicRootNodeFactory$LLVMIntrinsicExpressionNodeGen.execute(LLVMIntrinsicRootNodeFactory.java:36)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:226)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:86)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:70)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNode.doDirectIntrinsic(LLVMDispatchNode.java:122)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:64)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNode.doDirectCached(LLVMLookupDispatchNode.java:78)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeDispatch(LLVMLookupDispatchNodeGen.java:56)
	at com.oracle.truffle.llvm.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:75)
	at com.oracle.truffle.llvm.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric_generic1(LLVMValueProfilingNodeFactory.java:396)
	at com.oracle.truffle.llvm.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric(LLVMValueProfilingNodeFactory.java:380)
	at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute_generic1(LLVMWriteNodeFactory.java:980)
	at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute(LLVMWriteNodeFactory.java:961)
	at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.execute(LLVMBasicBlockNode.java:80)
	at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:99)
	at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:75)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:258)
```

**Comment by sbellware** [comment] 2018-09-05 21:51
If it's of any use in any investigation, this can be reproduced by installing the gem dependencies of the following repo: https://github.com/eventide-project/message-store-postgres.

There is a branch named `pin-pg-to-v1` that circumvents other installation problems due to #1421, and allows this error to be induced.

The gem dependencies can be installed by running the `install-gems.sh` script in that project's root (which effectively does: `bundle install --standalone --path=./gems`).

Again, this isn't pressing or obstructing any progress on my part. Just thought it might be helpful, useful, or interesting.

**Comment by nirvdrum** [comment] 2018-09-05 21:56
Thanks for the detailed report! We already have [a fix for this in master](https://github.com/oracle/truffleruby/commit/c322c2112014ee30b6935678dd32ee0d4add08d4). Unfortunately, it missed the release window for the 1.0.0 RC 6 release. But it will ship in the next release.

As you've discovered, the issue is not fatal, but it is annoying. If you're happy to just ignore it until our next release, you don't have anything to worry about.

**Closed by nirvdrum** 2018-09-05 21:56 UTC

**Comment by sbellware** [comment] 2018-09-05 21:58
@nirvdrum Awesome!! I'm happy to wait. The only problem we experience by waiting is the excitement building without relief of seeing our project work on TruffleRuby for the first time :)

**Comment by nirvdrum** [comment] 2018-09-05 22:04
@sbellware Your project should still work. What you're seeing here is roughly equivalent to an internal exception being logged, but being recovered from gracefully.

If your project doesn't work, it shouldn't be related to the messages you're seeing above. In that case, please do file an issue and we'll work to get whatever problems resolved.
