### ISSUE TITLE
Minitest + turn gem broken on TruffleRuby

### ISSUE THREAD

**Issue by ivoanjo** [oracle/truffleruby#1377] opened 2018-06-23 14:24 UTC
Hello there!

* TruffleRuby version: `truffleruby 1.0.0-rc2, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]`
* Linux version: `Linux maruhime 4.13.0-45-generic #50-Ubuntu SMP Wed May 30 08:23:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* OS version: `Ubuntu 17.10`

While trying to run the [hyperclient](https://github.com/codegram/hyperclient) gem test suite on TruffleRuby, I ran into a problem when loading the test suite.

I was able to reduce it down to this testcase:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'minitest', '< 5'
  gem 'turn', '0.9.7'
end

require 'minitest/autorun'
```

Output on MRI Ruby:

```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
Loaded Suite 

Started at 2018-06-23 15:23:09 +0100 w/ seed 48523.

Finished in 0.000213 seconds.

0 tests, 0 passed, 0 failures, 0 errors, 0 skips, 0 assertions
```

Output on TruffleRuby:

```
truffleruby 1.0.0-rc2, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]
.rvm/gems/truffleruby-1.0.0-rc2/gems/turn-0.9.7/lib/turn/runners/minirunner.rb:49:in `_run_suites': cannot load such file -- test/unit (LoadError)
        from .rvm/gems/truffleruby-1.0.0-rc2/gems/minitest-4.7.5/lib/minitest/unit.rb:877:in `_run_anything'
        from .rvm/gems/truffleruby-1.0.0-rc2/gems/minitest-4.7.5/lib/minitest/unit.rb:1085:in `run_tests'
        from .rvm/gems/truffleruby-1.0.0-rc2/gems/minitest-4.7.5/lib/minitest/unit.rb:1072:in `send'
        from .rvm/gems/truffleruby-1.0.0-rc2/gems/minitest-4.7.5/lib/minitest/unit.rb:1072:in `block in _run'
        from .rvm/gems/truffleruby-1.0.0-rc2/gems/minitest-4.7.5/lib/minitest/unit.rb:1071:in `each'
        from .rvm/gems/truffleruby-1.0.0-rc2/gems/minitest-4.7.5/lib/minitest/unit.rb:1071:in `_run'
        from .rvm/gems/truffleruby-1.0.0-rc2/gems/minitest-4.7.5/lib/minitest/unit.rb:1059:in `run'
        from .rvm/gems/truffleruby-1.0.0-rc2/gems/minitest-4.7.5/lib/minitest/unit.rb:795:in `block in autorun'
```

**Comment by nirvdrum** [comment] 2018-06-29 21:42
Thanks for the small, easy-to-reproduce case!

I tracked this down to a bug in our handling of `autoload`. The `turn` gem has the following:

```
autoload "Test",     'test/unit'
```

Elsewhere, it checks if `Test::Unit::TestCase` has been loaded yet by using `defined?`:

```
defined?(Test::Unit::TestCase)
```

On TruffleRuby, this is triggering a fault of the autoload and then it fails because `'test/case'` can't be loaded. On MRI, no attempt at autoloading is made and `nil` is returned instead.

**Comment by nirvdrum** [comment] 2018-06-29 22:48
I take that back. MRI does appear to perform the autoload, but it swallows the exception.

**Comment by nirvdrum** [comment] 2018-07-03 20:55
Thanks again for filing the issue. The fix is available in c09da57999352e8bdd72703df844923a03f846d8 and will be included in the next release (1.0.0 RC4?). Autoloading is really tricky to get right and using `defined?` complicates it further. I added a few Ruby specs so we don't regress and to help others out as well.

**Closed by nirvdrum** 2018-07-03 20:55 UTC

**Comment by ivoanjo** [comment] 2018-07-03 22:08
Thanks for the fix! 🎉

**Comment by nirvdrum** [comment] 2018-08-04 20:15
No problem. In case you hadn't seen, 1.0.0 RC5 has been released. If you get a chance, I'd love to verify that this issue has truly been fixed for you.

**Comment by ivoanjo** [comment] 2018-08-11 17:02
Yes, I can confirm that the whole test suite for the hyperclient gem is green on 1.0.0-rc5, awesome! :tada:
