### ISSUE TITLE
NameError: uninitialized constant Digest::MD5

### ISSUE THREAD

**Issue by dogweather** [oracle/truffleruby#2596] opened 2022-02-05 05:47 UTC
I get that error with **22.0.0.2** and Rails 6.1.4.4 when trying to run `bundle install`.

```
NameError: uninitialized constant Digest::MD5
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/digest-3.1.0/lib/digest.rb:114:in `block in Digest'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/digest-3.1.0/lib/digest.rb:112:in `synchronize'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/digest-3.1.0/lib/digest.rb:112:in `Digest'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/shared_helpers.rb:194:in `digest'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/source/rubygems/remote.rb:31:in `cache_slug'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/fetcher/compact_index.rb:117:in `cache_path'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/fetcher/compact_index.rb:85:in `compact_index_client'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/fetcher/compact_index.rb:70:in `available?'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/fetcher/compact_index.rb:16:in `available?'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/fetcher.rb:158:in `use_api'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/source/rubygems.rb:427:in `block in api_fetchers'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/source/rubygems.rb:427:in `select'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/source/rubygems.rb:427:in `api_fetchers'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/source/rubygems.rb:432:in `block in remote_specs'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/index.rb:9:in `build'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/source/rubygems.rb:431:in `remote_specs'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/source/rubygems.rb:131:in `specs'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/resolver.rb:167:in `index_for'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/resolver.rb:175:in `results_for'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/resolver.rb:112:in `search_for'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/resolver.rb:255:in `block in verify_gemfile_dependencies_are_found!'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/resolver.rb:252:in `map!'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/resolver.rb:252:in `verify_gemfile_dependencies_are_found!'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/resolver.rb:48:in `start'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/resolver.rb:23:in `resolve'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/definition.rb:269:in `resolve'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/definition.rb:180:in `resolve_remotely!'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/installer.rb:280:in `resolve_if_needed'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/installer.rb:82:in `block in run'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/process_lock.rb:12:in `block in lock'
  <internal:core> core/io.rb:695:in `open'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/process_lock.rb:9:in `lock'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/installer.rb:71:in `run'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/installer.rb:23:in `install'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/cli/update.rb:78:in `run'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:303:in `block in update'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/settings.rb:131:in `temporary'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:302:in `update'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in `dispatch'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in `start'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/lib/gems/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
  <internal:core> core/kernel.rb:376:in `load'
  <internal:core> core/kernel.rb:376:in `load'
  /Users/robb/.rbenv/versions/truffleruby-22.0.0.2/bin/bundle:23:in `<main>'
```

**Comment by eregon** [comment] 2022-02-07 14:07
Duplicate of #2577 and already fixed, it should work fine in `-dev` builds (see README)

**Closed by eregon** 2022-02-07 14:07 UTC
Labels: compatibility, duplicate
