### ISSUE TITLE
invalid group reference 0

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2746] opened 2022-09-28 14:34 UTC
### How to reproduce
```
ruby -e '"(AV:A/AC:M/Au:S/C:P/I:P/A:P/E:POC/RL:TF/RC:UC/CDP:L/TD:M/CR:M/IR:M/AR:M)".scan(/\((?>[^)(]+|\g<0>)*\)/)'
```
### Exception
```
<internal:core> core/truffle/regexp_operations.rb:29:in `Truffle::RegexpOperations.match_in_region': invalid group reference 0 (Polyglot::ForeignException)
	from <internal:core> core/truffle/regexp_operations.rb:29:in `Truffle::RegexpOperations.search_region'
	from <internal:core> core/truffle/regexp_operations.rb:62:in `Truffle::RegexpOperations.match_from'
	from <internal:core> core/string.rb:243:in `String#scan'
	from -e:1:in `<main>'
```

**Comment by eregon** [comment] 2022-09-30 15:21
@jirkamarsik Could you look into this? It sounds like a TRegex exception.

**Comment by jirkamarsik** [comment] 2022-10-01 08:05
@gogainda , thanks for the report! I think I know the cause of this issue and will fix it soon.

**Comment by eregon** [comment] 2022-10-07 10:12
Fixed in https://github.com/oracle/graal/commit/89cb274b45a7c97d546b64aedf02db807fec0031, needs a graal update which should be merged next week.

**Closed by eregon** 2022-10-07 10:12 UTC
