### ISSUE TITLE
msgpack: Global variable rb_tr_true is declared but not defined

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1729] opened 2019-07-21 13:24 UTC
See https://travis-ci.com/socketry/falcon/jobs/217858985

**Comment by eregon** [comment] 2019-07-22 08:30
@deepj Thanks for the report.
This is a duplicate of #1715, which will be fixed in the next release, and can be worked around until then by removing the cache in TravisCI.

**Closed by eregon** 2019-07-22 08:30 UTC

**Comment by eregon** [comment] 2019-07-22 08:31
@ioquatix Could you clear the cache on TravisCI for `falcon`?

**Comment by ioquatix** [comment] 2019-07-22 10:17
Sure

**Comment by ioquatix** [comment] 2019-07-22 10:24
Cleared cache and running it again: https://travis-ci.com/socketry/falcon/jobs/218052935

**Comment by eregon** [comment] 2019-08-23 19:26
TruffleRuby 19.2.0 was release and fixes this bug, please try it.
