### ISSUE TITLE
ROM: ROM::AttributeAlreadyDefinedError: Attribute * already defined

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1657] opened 2019-04-15 07:48 UTC
I'm not sure why this is an issue in TruffleRuby. But this is a major issue to run ROM/Hanami in TruffleRuby. I thought this would be fixed by various fixes reported by me but it seems not. At least not in the recent master.

To reproduce

```ruby
require 'rom/core'
require 'rom/memory'

Class.new(ROM::Relation[:memory]) do
  schema do
    attribute :title, ROM::Types::String
  end
end.new([])
```

Alternatively
```
git clone https://github.com/rom-rb/rom.git
git checkout truffleruby
bundle
rake spec
```

Error:

```
Traceback (most recent call last):
       15: from ~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/bin/irb:31:in `<main>'
       14: from (irb):4
       13: from ~/.gem/truffleruby/2.6.2/gems/rom-core-4.2.1/lib/rom/support/memoizable.rb:13:in `new'
       12: from ~/.gem/truffleruby/2.6.2/gems/rom-core-4.2.1/lib/rom/support/memoizable.rb:13:in `new'
       11: from ~/.gem/truffleruby/2.6.2/gems/dry-initializer-2.5.0/lib/dry/initializer/mixin/root.rb:7:in `initialize'
       10: from (eval):8:in `__dry_initializer_initialize__'
        9: from (eval):8:in `instance_exec'
        8: from ~/.gem/truffleruby/2.6.2/gems/rom-core-4.2.1/lib/rom/relation.rb:142:in `block in Relation'
        7: from ~/.gem/truffleruby/2.6.2/gems/rom-core-4.2.1/lib/rom/relation/class_interface.rb:302:in `default_schema'
        6: from ~/.gem/truffleruby/2.6.2/gems/rom-core-4.2.1/lib/rom/relation/class_interface.rb:302:in `call'
        5: from ~/.gem/truffleruby/2.6.2/gems/rom-core-4.2.1/lib/rom/relation/class_interface.rb:106:in `block in schema'
        4: from ~/.gem/truffleruby/2.6.2/gems/rom-core-4.2.1/lib/rom/schema/dsl.rb:157:in `call'
        3: from ~/.gem/truffleruby/2.6.2/gems/rom-core-4.2.1/lib/rom/schema/dsl.rb:157:in `instance_exec'
        2: from (irb):6:in `block (2 levels) in irb_binding'
        1: from ~/.gem/truffleruby/2.6.2/gems/rom-core-4.2.1/lib/rom/schema/dsl.rb:71:in `attribute'
ROM::AttributeAlreadyDefinedError (Attribute :title already defined)
```

**Comment by aardvark179** [comment] 2019-04-23 17:23
Okay, this appears to be due to us picking up the wrong block argument(s) in `class_interface.rb`, for some reason in the proc defined in `ClassInterface#schema` both `&block` and `&inner_block` are being resolved to `&block`.

The issue can be reproduced with
```
def foo(&block)
  proc do |*args, &inner_block|
    args.each &block if block
    args.each &inner_block if inner_block
  end
end

foo do |x|
  puts "Found #{x}"
end.call(1, 2, 3)
```

**Comment by aardvark179** [comment] 2019-04-23 17:45
Oh, I see why it's happening. I need to write some specs to characterise exactly what MRI does with implicit and explicit block arguments in blocks before I fix this, the whole area feels a little delicate.

**Comment by deepj** [comment] 2019-05-10 02:16
@aardvark179 any progress in this? It might fix some failing spec `dry-monads`

**Comment by aardvark179** [comment] 2019-05-10 10:14
I've got a PR internally to fix this, and we're starting to clear the backlog now the release is out.

**Comment by aardvark179** [comment] 2019-05-22 08:52
The fix for this has now been merged.

**Closed by aardvark179** 2019-05-22 08:52 UTC
Labels: compatibility, priority
