### ISSUE TITLE
multiple assignment in conditional (SyntaxError)

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1912] opened 2020-02-15 11:48 UTC
```
$ ruby -e 'if (a,b=[1,2.even?]); p a; end'
1

$ truffleruby -e 'if (a,b=[1,2.even?]); p a; end'
truffleruby: -e:1: multiple assignment in conditional (SyntaxError)
```

This pattern is used in Discourse:
https://github.com/discourse/discourse/blob/cd5b7109d04722df5c39b2ded9fa4ead6c290ce4/lib/stylesheet/importer.rb#L210

**Comment by deepj** [comment] 2020-02-18 03:12
@eregon this is a duplicate of https://github.com/oracle/truffleruby/issues/1513

**Closed** 2020-02-18 12:59 UTC
Labels: compatibility, duplicate
