### ISSUE TITLE
Unexpected CI failures on TruffleRuby (using Appraisal)

### ISSUE THREAD

**Issue by halostatue** [oracle/truffleruby#2441] opened 2021-09-09 02:21 UTC
I’m not entirely sure why this particular run failed except that I’m using Appraisal.

https://github.com/KineticCafe/marlowe/pull/10/checks?check_run_id=3551437592

At the moment I only use TruffleRuby in CI, but I want to make sure that people who use my gems can use TruffleRuby.

**Comment by halostatue** [comment] 2021-09-09 02:46
This only appears to fail under the current released version available via Github Actions.

**Comment by eregon** [comment] 2021-09-09 09:45
Thanks for the report.

I think the problem here might be:
```
Run bundle exec ruby -S appraisal install
>> Reinstall Bundler into /home/runner/work/marlowe/marlowe/vendor/bundle/truffleruby/2.7.3.21.2.0
Successfully installed bundler-2.2.27
1 gem installed
```

Do you know why appraisal reinstalls bundler, or if there is a way to disable that?

In the backtrace we see bundler files loaded from different places, which feels wrong (although they have the same bundler version):
```
	from /home/runner/.rubies/truffleruby-21.2.0.1/lib/gems/gems/bundler-2.2.27/lib/bundler.rb:85:in `ui'
	from /home/runner/work/marlowe/marlowe/vendor/bundle/truffleruby/2.7.3.21.2.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:64:in `request_issue_report_for'
```

Maybe it would help to use `bundler: none` for `setup-ruby`, so the default bundler is used, and there would be only 2 bundler versions, not 3.

**Comment by eregon** [comment] 2021-09-09 09:47
Given the failing line is:
```ruby
https://github.com/rubygems/rubygems/blob/bundler-v2.2.27/bundler/lib/bundler/vendor/thor/lib/thor/command.rb#L2
```
Which dynamically generates the superclass on every execution.

That seems to clearly indicate Bundler is loaded twice.

**Comment by eregon** [comment] 2021-09-09 09:51
> This only appears to fail under the current released version available via Github Actions.

Do you mean it works with `truffleruby-head`, or locally?

**Comment by halostatue** [comment] 2021-09-09 13:15
I mean it works with `truffleruby-head`. Only `truffleruby` fails on Ubuntu and MacOS both.

**Comment by eregon** [comment] 2021-09-09 13:33
Interesting, for `truffleruby-head` I see
https://github.com/KineticCafe/marlowe/runs/3551721464?check_suite_focus=true
There is no `Reinstall Bundler into /home/runner/work/marlowe/marlowe/vendor/bundle/truffleruby/2.7.3.21.2.0`.
And the Bundler shipped with TruffleRuby 2.1.4 is used for everything including appraisal.
That's partly because setup-ruby doesn't `gem install bundler` on `-head` versions.

It would most likely work on 21.2.0 if there is no `gem install bundler` before.

We'll try to reproduce locally, at least it works on CRuby 2.7 with `Reinstall Bundler into ...`.

**Comment by eregon** [comment] 2021-09-09 13:33
@bjfish Could you look into this? Probably the $LOAD_PATH is not correct at some point, maybe related to `-I` options or something else.

**Comment by eregon** [comment] 2021-10-13 11:37
This was fixed by @bjfish in https://github.com/oracle/truffleruby/commit/54ccd51818c34648acfafeb87e0a2a7474961361

**Closed by eregon** 2021-10-13 11:37 UTC
Labels: compatibility
