### ISSUE TITLE
rb_gc_register_mark_object not implemented in json 2.3.0

### ISSUE THREAD

**Issue by Mogztter** [oracle/truffleruby#1857] opened 2019-12-14 10:30 UTC
We are using the `json` gem in Asciidoctor and the following error is thrown when running the test suite (with coverage):

```
$ bundle exec rake coverage test:all
```

```
ruby.c:2903:in `rb_tr_error': rb_gc_register_mark_object not implemented (RuntimeError)
	from ruby.c:4676:in `rb_gc_register_mark_object'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/json-2.3.0/ext/json/ext/parser/parser.rl:852:in `Init_parser'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/json-2.3.0/lib/json/ext.rb:7:in `require'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/json-2.3.0/lib/json/ext.rb:7:in `Ext'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/json-2.3.0/lib/json/ext.rb:6:in `JSON'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/json-2.3.0/lib/json/ext.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/json-2.3.0/lib/json.rb:59:in `require'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/json-2.3.0/lib/json.rb:59:in `JSON'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/json-2.3.0/lib/json.rb:55:in `<top (required)>'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/simplecov-0.16.1/lib/simplecov/last_run.rb:3:in `require'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/simplecov-0.16.1/lib/simplecov/last_run.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/simplecov-0.16.1/lib/simplecov.rb:270:in `require'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/simplecov-0.16.1/lib/simplecov.rb:270:in `<top (required)>'
	from /home/travis/build/asciidoctor/asciidoctor/test/test_helper.rb:5:in `require'
	from /home/travis/build/asciidoctor/asciidoctor/test/test_helper.rb:5:in `<top (required)>'
	from /home/travis/build/asciidoctor/asciidoctor/test/api_test.rb:2:in `require_relative'
	from /home/travis/build/asciidoctor/asciidoctor/test/api_test.rb:2:in `<top (required)>'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/rake-12.3.3/lib/rake/rake_test_loader.rb:17:in `require'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/rake-12.3.3/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/rake-12.3.3/lib/rake/rake_test_loader.rb:5:in `select'
	from /home/travis/.rvm/gems/truffleruby-19.2.0/gems/rake-12.3.3/lib/rake/rake_test_loader.rb:5:in `<main>'
```

https://travis-ci.org/asciidoctor/asciidoctor/jobs/624746943?utm_medium=notification&utm_source=github_status

Please note that we cannot reproduce this issue with json 2.2.0.
The `rb_gc_register_mark_object` calls were indeed added in json 2.3.0:

https://github.com/flori/json/compare/v2.2.0...v2.3.0#diff-b24ca9830076d9fdf8877cc16664960dR1402-R1403

I wonder if TruffleRuby should issue a warning instead of throwing an exception?

https://github.com/oracle/truffleruby/blob/123bc59cf505c09a9943eb3d0360f639709d6029/src/main/c/cext/ruby.c#L4717-L4719

**Comment by eregon** [comment] 2019-12-14 12:00
Thank you for the report, and sorry that it broke in your CI.

JSON 2.3.0 was released a few days ago (https://rubygems.org/gems/json) with those `rb_gc_register_mark_object` calls.

#1856 is a PR by @chrisseaton to fix this.

For the 19.3.0 TruffleRuby release I can advice to use the `json` bundled in the standard library, or to use json 2.2.0 as a workaround.

To avoid this in the future I'll try to add TruffleRuby in `json`'s CI.

I'll see if we can do something in the `json` gem to avoid this problem.
Those `rb_gc_register_mark_object` seem all useless to me, because they are already referenced as classes/modules.

**Comment by eregon** [comment] 2019-12-14 12:09
This seems related to @tenderlove changes in https://github.com/ruby/ruby/commit/79ead821dd4880725c9c6bb9645b3fad71715c5b and https://github.com/ruby/ruby/commit/91793b8967e0531bd1159a8ff0cc7e50739c7620

So this seems indeed needed for `GC.compact` in MRI.

This is a fairly different use than what the documentation states:
https://github.com/ruby/ruby/blob/master/doc/extension.rdoc#defining-global-variables
```
void rb_gc_register_mark_object(VALUE object) ::

  Tells GC to protect the +object+, which may not be referenced anywhere.
```

@tenderlove Could you update the documentation about that?

Might such `rb_gc_register_mark_object` calls also be needed in other C extensions, is there a guide about how to make C extensions compatible with GC.compact?

**Comment by Mogztter** [comment] 2019-12-14 13:10
@eregon I was looking for an issue on GitHub so I missed the related pull request. Anyway thanks for the pointer!
I'm glad this issue is already worked one :rocket:

**Comment by eregon** [comment] 2019-12-17 09:13
https://github.com/oracle/truffleruby/pull/1856 got merged, it will be in the next release.

**Comment by tenderlove** [comment] 2019-12-17 20:45
@eregon I'm not sure what to say that will better document it.  The problem is that JSON was stashing Ruby objects in static variables.  Those objects could get collected, so they may indeed "not be referenced anywhere".

For example:

## Library code

```ruby
module Foo
  class Bar
  end
end
```

```c
static VALUE ref;

void Init_ext() {
  ref = rb_const_get(mFoo, "Bar");
}
```

## User Code

```ruby
Foo.send :remove_const, :Bar
GC.start
# Now `static VALUE ref` points at a GC'd object
```end

**Comment by chrisseaton** [comment] 2019-12-17 20:48
Why do you want to protect the object, rather than the variable, though? In other words, why `rb_gc_register_mark_object` and not `rb_global_variable`? Doesn't `rb_gc_register_mark_object` mean that the object could not be referenceable by any code, but still kept alive?

(It's not a problem for TruffleRuby, and I've implemented `rb_gc_register_mark_object` now, but just wondering about the intent in the difference.)

**Comment by eregon** [comment] 2019-12-18 09:22
@tenderlove Thanks for the explanation. From the commit message of https://github.com/ruby/ruby/commit/79ead821dd4880725c9c6bb9645b3fad71715c5b :
> Add NaN / Infinity / MinusInfinity to mark list
> This prevents the constants from moving.

I thought that meant `rb_gc_register_mark_object` is a way to pin objects so they are not moved by `GC.compact`.

Indeed, `remove_const` would be a way to have C pointing to GC'd objects.

**Comment by tenderlove** [comment] 2019-12-18 17:40
> Why do you want to protect the object, rather than the variable, though? In other words, why rb_gc_register_mark_object and not rb_global_variable? Doesn't rb_gc_register_mark_object mean that the object could not be referenceable by any code, but still kept alive?

We could use either.  I've seen both used to mark C statics in the wild, so I made the GC prevent objects marked with either of those functions from moving.  I think you're right, we probably want to use `rb_global_variable` since I guess the value could change (though in this case it doesn't).

> I thought that meant `rb_gc_register_mark_object` is a way to pin objects so they are not moved by `GC.compact`.

Yes, it's a side-effect of the function.  Since the GC can't update `static` variables, and `rb_gc_register_mark_object` is used to mark them (typically), the GC will not let them move.

**Comment by eregon** [comment] 2019-12-20 16:04
This will be in the 19.3.1 release, [scheduled](https://www.graalvm.org/docs/release-notes/version-roadmap/) for January 14.
Considering that, I think we can wait for that and don't need a workaround in JSON for now.

**Closed by eregon** 2019-12-20 16:04 UTC
Labels: cexts
