### ISSUE TITLE
official docker image:  can't install nokogiri

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2350] opened 2021-05-18 13:12 UTC
Just had this while installing gems inside the docker image:

```
bash-4.4# gem install nokogiri -v '1.11.4'
Fetching mini_portile2-2.5.1.gem
Fetching nokogiri-1.11.4.gem
Successfully installed mini_portile2-2.5.1
ERROR:  Error installing nokogiri:
        invalid gem: package is corrupt, exception while verifying: invalid byte sequence in US-ASCII (ArgumentError) in /opt/truffleruby-21.1.0-linux-amd64/lib/gems/cache/nokogiri-1.11.4.gem
```

**Comment by eregon** [comment] 2021-05-18 13:22
I can reproduce, and:
```
bash-4.4# tar tf /opt/truffleruby-21.1.0-linux-amd64/lib/gems/cache/nokogiri-1.11.4.gem
metadata.gz
data.tar.gz
checksums.yaml.gz
bash-4.4# ruby -v
truffleruby 21.1.0, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]

bash-4.4# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
So the archive itself seems fine. And the value of `$LANG` is good.
`locale` emits some errors though.

Also:
```
$ ruby -e 'p Encoding.find "locale"'  
docker: #<Encoding:US-ASCII>
locally: #<Encoding:UTF-8>
```
Which I would guess is the cause of this.

**Comment by eregon** [comment] 2021-05-18 13:28
It seems the same issue as https://github.com/graalvm/container/issues/9
See the workaround there.
I think we should potentially warn when we don't find a proper locale encoding, as it can lead to confusing issues such as this one.

**Comment by abdelhaira** [comment] 2021-05-18 16:19
@eregon the encoding fix corrected the issue, but i'm getting another error when reproducing installing nokogiri(full log [truffleruby-log.txt](https://github.com/oracle/truffleruby/files/6502805/truffleruby-log.txt))

`To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/truffleruby-21.1.0-linux-amd64/lib/gems/extensions/x86_64-linux/21.1.0/nokogiri-1.11.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/truffleruby-21.1.0-linux-amd64/lib/gems/gems/nokogiri-1.11.4 for inspection.
Results logged to /opt/truffleruby-21.1.0-linux-amd64/lib/gems/extensions/x86_64-linux/21.1.0/nokogiri-1.11.4/gem_make.out`

**Comment by HoneyryderChuck** [comment] 2021-05-18 16:38
thx, it worked.

should I still leave this open? I'd say that should come bundled in by default.

**Comment by eregon** [comment] 2021-05-18 16:59
@abdelhaira The error is:
> /opt/truffleruby-21.1.0-linux-amd64/lib/gems/gems/mini_portile2-2.5.1/lib/mini_portile2/mini_portile.rb:94:in `apply_patch': Failed to complete patch task; patch(1) or git(1) is required. (RuntimeError)

So you need to install one of them, and then it works.

@HoneyryderChuck Agreed, installing `glibc-langpack-en` is enough, so I think that should be part of all graalvm Docker images (https://github.com/graalvm/container/issues/9) and then we can close this (otherwise many locale-related things are broken).

**Comment by abdelhaira** [comment] 2021-05-18 18:28
This has been fixed [here](https://github.com/graalvm/container/pull/15), truffleruby-21.1.0 containers have been updated, closing this

**Closed** 2021-05-18 19:12 UTC
Labels: bug

**Comment by eregon** [comment] 2021-06-17 21:18
There is now a warning when the locale is not set properly: https://github.com/oracle/truffleruby/commit/6b03a11d685c4ce58855628ebfef5bafbfa211af
