### ISSUE TITLE
Temporary Slowdown/Deoptimization very late into the process in Rubykon benchmark

### ISSUE THREAD

**Issue by PragTob** [oracle/truffleruby#2070] opened 2020-08-10 07:32 UTC
:wave: 

Hi everyone and first of all thanks for your work :)

I've been running rubykon benchmarks again, namely [mcts_avg](https://github.com/PragTob/rubykon/blob/main/benchmark/mcts_avg.rb). What I noticed with truffleruby in various configurations was that after it had seemingly reached peak performance it would do rather drastic slow downs fairly late into the process. It reaches peak performance again but it's somewhat baffling. Benchmarks were done with 5 minutes of warmup, 2 minutes of measurement time.

Of course, Rubykon does random playouts so it might be in the nature of it that some weird edge case that wasn't reached before is suddenly reached and causes the slowdown. Be that as it may, I still wanted to report it :)

So, here are some examples (times are raw run times in seconds recorded, first array is warmup time, second one run time):

**truffleruby 20.1.0, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]**:

[39.013, 15.597, 3.42, 4.025, 9.776, 4.341, 2.8609999999999998, 2.887, 2.906, 2.893, 2.91, 2.855, 2.848, 2.907, 2.881, 2.901, 2.868, 2.831, 2.886, 2.852, 2.859, 7.989, 3.066, 2.851, 2.782, 2.84, 2.839, 2.862, 2.788, 2.839, 2.795, 2.8360000000000003, 2.844, 2.8, 2.828, 2.862, 2.807, 2.8520000000000003, 2.802, 2.817, 2.796, 2.844, 2.7880000000000003, 2.83, 2.835, 2.847, 2.802, 2.845, 2.847, 2.798, 2.846, 2.795, 2.828, 2.842, 2.795, 2.839, 2.792, 2.831, 2.835, 2.84, 2.7960000000000003, 2.839, 2.855, 2.809, 2.756, 2.8200000000000003, 2.83, 2.84, 2.791, 2.819, 2.844, 2.859, 2.8, 2.837, 2.78, 2.815, 2.84, 2.792, 2.827, 2.844, 2.863, 2.793, 2.858, 2.806]
[2.852, 2.804, 2.849, 2.808, 2.8520000000000003, 2.801, 2.832, 2.864, 2.787, 2.845, 2.7960000000000003, 2.852, 2.798, 2.824, 2.845, 2.829, 7.806, 3.011, 2.876, 2.894, 2.832, 2.876, 2.832, 2.83, 2.906, 2.798, 2.868, 2.868, 2.833, 2.866, 2.821, 2.844, 2.855, 2.87, 2.881, 2.834, 2.8689999999999998, 2.876, 2.838, 2.788, 2.848]

It hits ~2.8 relatively quickly, jumps up to `7.989` (still caught in the warmup) but later also does another jump to `7.806`

**truffleruby 20.1.0, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]** sounds the same as above, but this time it's graalvm install with installed ruby "plugin":

[30.983858, 16.297791, 3.615629, 4.176306, 4.927614, 3.193502, 3.131202, 8.458244, 7.914813, 3.234492, 3.072843, 3.034222, 3.036073, 3.011155, 3.028176, 3.016708, 3.097388, 3.046096, 2.948119, 3.072179, 3.014152, 3.042776, 3.0381869999999997, 3.049676, 2.977254, 3.059626, 3.043145, 2.980067, 3.062206, 2.917943, 3.029653, 2.931029, 3.067554, 2.891372, 3.067622, 2.933528, 2.982602, 2.981059, 2.970536, 2.965429, 3.022221, 2.926975, 2.977493, 3.020401, 2.921641, 3.02614, 8.601536, 4.203804, 3.012836, 2.981562, 3.007788, 3.001549, 3.087057, 2.941903, 3.086291, 2.948888, 3.074049, 3.038931, 2.977055, 2.968258, 2.967472, 3.027601, 3.056108, 2.995811, 2.935901, 2.979335, 3.044281, 2.944737, 3.041155, 2.979783, 3.094664, 2.995909, 3.006382, 2.969464, 3.060175, 2.949667, 2.96824, 3.037369, 2.992188]
[3.060795, 3.037202, 2.942327, 2.987264, 3.024627, 3.078009, 3.000189, 2.95938, 3.053702, 3.036351, 2.978454, 2.995184, 3.061541, 2.94288, 3.033715, 2.93285, 3.040602, 2.920935, 3.049107, 2.943919, 3.059457, 2.929068, 3.056512, 3.020345, 3.030002, 2.947515, 3.059934, 3.022135, 2.975954, 3.0554129999999997, 3.02751, 3.038616, 2.979568, 2.966623, 3.041841, 2.952218, 3.074563, 2.987172, 2.920624, 3.046479]

After reaching peak performance for a while it jumps to `8.601536`. This time run time measurements are unaffected though.

**truffleruby 20.1.0, like ruby 2.6.5, GraalVM CE JVM [x86_64-linux]** (jvm mode this time):

[28.731268, 17.790974, 20.403481, 11.252657, 7.885554, 7.841373, 6.289241, 4.170636, 1.959966, 1.964468, 2.278793, 6.002114, 4.341315, 3.074623, 3.03663, 2.96244, 2.541933, 2.421661, 2.354883, 2.356453, 2.355754, 2.405301, 2.278617, 1.907133, 1.670882, 1.679808, 1.683283, 1.683941, 1.681858, 1.668084, 1.6838090000000001, 1.68539, 1.675429, 1.6850749999999999, 1.695294, 1.703954, 1.7144759999999999, 1.673667, 1.681426, 1.675211, 1.693061, 1.693483, 1.6832950000000002, 1.665366, 1.686907, 1.677872, 1.682541, 1.694142, 1.6804830000000002, 1.694078, 1.692561, 1.684781, 1.695526, 1.682804, 1.685105, 1.6900979999999999, 1.703598, 1.688802, 1.6987, 1.694845, 1.705333, 1.709088, 1.679375, 1.678766, 1.667812, 1.677179, 1.684794, 1.679287, 1.678937, 1.674857, 1.674557, 1.695606, 1.669709, 1.677682, 1.6878389999999999, 1.689886, 1.689414, 1.6925880000000002, 1.6938119999999999, 1.688948, 1.676711, 1.693323, 1.679232, 1.6858710000000001, 1.677157, 1.676614, 1.685597, 1.686417, 1.684725, 1.697902, 1.697009, 1.6961439999999999, 1.68811, 1.692567, 1.6923249999999999, 1.701442, 1.7033740000000002, 1.694986, 1.69125, 1.6797650000000002, 1.678326, 1.687023, 1.664787, 1.669764, 1.678496, 1.6775250000000002, 1.691109, 1.6947109999999999, 1.6938689999999998, 1.693985, 1.684854, 1.701347, 1.682417, 1.701229]
[1.7040739999999999, 5.744561, 6.727143, 6.661216, 6.753205, 1.911123, 1.693888, 1.675875, 1.670088, 1.685009, 1.688002, 1.677262, 1.686827, 1.7016499999999999, 1.687225, 1.694171, 1.696442, 1.696454, 1.711303, 1.706913, 1.699687, 1.694405, 1.692496, 1.692413, 1.705191, 1.698966, 1.6869429999999999, 1.701725, 1.702909, 1.69667, 1.69493, 1.696324, 1.682036, 1.682361, 1.67886, 1.698082, 1.686297, 1.676594, 1.68829, 1.69374, 1.7057120000000001, 1.690121, 1.699076, 1.690116, 1.687866, 2.049559, 2.928114, 2.868949, 2.844205, 2.857996, 2.788039, 2.129209, 1.834408, 1.687905, 1.703189, 1.697745]

Here it was really "bad luck" as it seems to run at sub 1.7s quite steadily but jumps to ~6s for 4 measurements right at the start of run time measurements and later in also gets slower for a longer time at `2.928114` etc.
All those slowdowns push the average to 2.16 (ha, more reasons for median!) instead of ~1.7 which it would be "capable" of.
Was still the fastest in the benchmark, though.

As for the environment, my desktop is fairly old by now (5y+). It's [this cpu](https://ark.intel.com/content/www/us/en/ark/products/80806/intel-core-i7-4790-processor-8m-cache-up-to-4-00-ghz.html) and I'm running Linux Mint 19.3 (Based on Ubuntu 18.04).

Benchmark was run without the UI and most other background programs running to minimize interference. A similar slowdown could not be observed in any of the other measurements I took, so I'm pretty sure it's GraalVM/TruffleRuby specific.

That's it, thanks a lot for your work! :+1:

**Comment by eregon** [comment] 2020-08-10 08:24
Thanks a lot for the report!

Indeed, this sounds worth investigating.
Usually this kind of late deoptimizations can be traced with `--engine.TraceTransferToInterpreter`.
`--engine.BackgroundCompilation=false` can help to debug this by using blocking foregound compilation (then early performance will be slow, so not good for benchmarking, but more predictable when debugging since compilation happens synchronously).
That should show both the Ruby and Java stacktraces where the deoptimization happens.
(for instance on OptCarrot I noticed with this that there are some late deopts in the APU due to overflowing the range of `int`)

There are more details in https://github.com/oracle/graal/blob/master/truffle/docs/Optimizing.md, `--engine.TraceAssumptions`/`--vm.XX:+TraceDeoptimization` might be useful too if `--engine.TraceTransferToInterpreter` doesn't show anything.

`--vm.XX:+PrintGC` / `--vm.verbose:gc` can be used to trace GC activity.

We'll try to take a look, but also feel to try these flags and see if it reports anything interesting.
You'll probably want to output timings to the console so it's easier to correlate.

> (ha, more reasons for median!)

Yes, I would recommend robust estimators like the median, and some measurement of the error (stddev (but not robust), median absolute deviation, a boxplot, etc).
For instance, if the slowdown was caused by a long GC, the average seems rather unrepresentative of most results.

**Comment by PragTob** [comment] 2020-08-10 12:22
@eregon thanks! 

Yeah, I got stddev of course. In Ruby here I don't do median & friends (yet). I do those in [benchee](https://github.com/bencheeorg/benchee) but that's elixir, that has got median, all the percentiles you want, mode, min, max, boxplots and probably stuff I'm forgetting.

It's one of my long term projects to make that more reusable for other languages/implement it in such a way as I poured a lot of work into it. 

But... that's an aside :) I'll see to run it with the first 2 flags you mentioned printing out measurement results inbetween, see if anything shows up and then make a gist for you. Hopefully in the coming days.

Thanks!

**Comment by PragTob** [comment] 2020-08-11 18:20
So I did run it, could reproduce it and I have a likely candidate!

Full gist: https://gist.github.com/PragTob/32af2b74d96131c6b7130120245e6fe1

What I did:

```
tobi@speedy:~/github/rubykon(main)$ ruby --jvm -v
truffleruby 20.1.0, like ruby 2.6.5, GraalVM CE JVM [x86_64-linux]
tobi@speedy:~/github/rubykon(main)$ ruby --jvm --experimental-options --engine.TraceTransferToInterpreter --engine.BackgroundCompilation=false benchmark/mcts_avg.rb
```

To give enough warmup with the increased compile times (the first iteration alone takes ~300s) I configured even more extensive times:

```ruby
  benchmark.config warmup: 1_000, time: 300
```

The likely candidate is:

```
[engine] transferToInterpreter at
  Hash#map((core):1) <split-2cc03cd1>
    Rubykon::GroupTracker#neighboring_groups_of(lib/rubykon/group_tracker.rb:111)
    Rubykon::GroupTracker#regain_liberties_from_capture(lib/rubykon/group_tracker.rb:105) <split-4e17913b>
    Rubykon::GroupTracker#remove(lib/rubykon/group_tracker.rb:86) <split-149c3204>
    block in Rubykon::GroupTracker#remove_caught_groups(lib/rubykon/group_tracker.rb:80) <split-64f16277>
    Enumerable#inject(resource:/truffleruby/core/enumerable.rb:449) <split-497aec8c>
    Rubykon::GroupTracker#remove_caught_groups(lib/rubykon/group_tracker.rb:79) <split-3b9632d1>
....
```

That snippet happens a total of 12 times.

It's also the last one that happens (before printing the results):

```
----------------------------------------------
------------------------------------------------

Sample time: 1.6916799999999999

----------------------------------------------
------------------------------------------------

Sample time: 1.7040220000000001

----------------------------------------------
------------------------------------------------

Sample time: 1.705987

----------------------------------------------
------------------------------------------------

Sample time: 1.71381

----------------------------------------------
------------------------------------------------

Sample time: 1.696979

----------------------------------------------
[engine] transferToInterpreter at
  Hash#map((core):1) <split-2cc03cd1>
    Rubykon::GroupTracker#neighboring_groups_of(lib/rubykon/group_tracker.rb:111)
    Rubykon::GroupTracker#regain_liberties_from_capture(lib/rubykon/group_tracker.rb:105) <split-4e17913b>
    Rubykon::GroupTracker#remove(lib/rubykon/group_tracker.rb:86) <split-149c3204>
    block in Rubykon::GroupTracker#remove_caught_groups(lib/rubykon/group_tracker.rb:80) <split-64f16277>
    Enumerable#inject(resource:/truffleruby/core/enumerable.rb:449) <split-497aec8c>
    Rubykon::GroupTracker#remove_caught_groups(lib/rubykon/group_tracker.rb:79) <split-3b9632d1>
    Rubykon::GroupTracker#take_liberties_of_enemies(lib/rubykon/group_tracker.rb:61) <split-71d8cfe7>
    Rubykon::GroupTracker#assign(lib/rubykon/group_tracker.rb:16) <opt> <split-1e530163>
    Rubykon::Game#set_move(lib/rubykon/game.rb:101) <split-14d8444b>
    Rubykon::Game#set_valid_move(lib/rubykon/game.rb:55) <opt> <split-71466383>
    Rubykon::GameState#set_move(lib/rubykon/game_state.rb:25) <opt> <split-46d63dbb>
    MCTS::Playout#playout(lib/mcts/playout.rb:18) <opt>
    MCTS::Playout#play(lib/mcts/playout.rb:12) <opt>
    MCTS::Node#rollout(lib/mcts/node.rb:44) <opt>
    MCTS::Root#explore_tree(lib/mcts/root.rb:26) <split-22fbea95>
    block in MCTS::MCTS#start(lib/mcts/mcts.rb:7) <opt> <split-3093f75f>
    Integer#times(resource:/truffleruby/core/integer.rb:134) <opt> <split-65482336>
    MCTS::MCTS#start(lib/mcts/mcts.rb:6) <split-2fea3289>
    block (2 levels) in Object#<main>(benchmark/mcts_avg.rb:11) <split-6db27836>
    ...
  org.graalvm.truffle/com.oracle.truffle.api.CompilerDirectives.transferToInterpreterAndInvalidate(CompilerDirectives.java:90)
    org.truffleruby.core.array.ArrayBuilderNode$StartNode.start(ArrayBuilderNode.java:174)
    org.truffleruby.core.array.ArrayBuilderNode$ArrayBuilderProxyNode.start(ArrayBuilderNode.java:74)
    org.truffleruby.core.hash.HashNodes$MapNode.mapBuckets(HashNodes.java:695)
    org.truffleruby.core.hash.HashNodesFactory$MapNodeFactory$MapNodeGen.execute(HashNodesFactory.java:1946)
    org.truffleruby.builtins.EnumeratorSizeNode.execute(EnumeratorSizeNode.java:56)
    org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
    org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
    org.truffleruby.language.LazyRubyNode.execute(LazyRubyNode.java:41)
    org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
    jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:505)
    jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.inlinedPERoot(OptimizedCallTarget.java:414)
    jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:421)
    jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:68)
    org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:132)
    org.truffleruby.language.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:96)
    org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:44)
    org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:117)
    org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:105)
    org.truffleruby.language.control.FrameOnStackNode.execute(FrameOnStackNode.java:37)
    ...
------------------------------------------------

Sample time: 17.845152

----------------------------------------------
------------------------------------------------

Sample time: 1.693458

----------------------------------------------
------------------------------------------------

Sample time: 1.6879309999999998

----------------------------------------------
------------------------------------------------

Sample time: 1.6774390000000001

----------------------------------------------
```

There are also some around `Hash#[]` that happen around the group tracking code.

To look where warmup stops just search for `||||`

Hope this helps!

**Comment by rubyFeedback** [comment] 2021-12-20 15:49
This is now +1 year. Can someone update this with the recent changes and newer ruby releases? Not sure if PragTob wants to re-do them but it would be interesting to see any progress here.

**Comment by eregon** [comment] 2021-12-20 15:57
@rubyFeedback FWIW I plan to publish a blog post benchmarking many Rubies soon.

**Comment by eregon** [comment] 2022-01-06 19:52
@rubyFeedback this is the blog post: https://eregon.me/blog/2022/01/06/benchmarking-cruby-mjit-yjit-jruby-truffleruby.html

**Comment by PragTob** [comment] 2022-01-10 19:32
@eregon thanks! :green_heart: 

@rubyFeedback I have persistent arm problems for almost 11 months... they got better so that today is the first time in ~11 months that I look at my github notifications. Time to new blog post is still a while off, but I might :) It'll likely be months but the numbers from Benoit's benchmark look great.

**Comment by PragTob** [comment] 2022-01-10 19:33
@eregon did you encounter deoptimization late into the process when doing the benchmark? If not we might be able to close this one or shall I keep it open?

**Comment by eregon** [comment] 2022-01-11 11:48
@PragTob Here are the numbers for my run, yjit-bench seems to use the same setup: https://github.com/Shopify/yjit-bench/blob/1751916ceb/benchmarks/rubykon/benchmark.rb vs https://github.com/PragTob/rubykon/blob/main/benchmark/mcts_avg.rb
The numbers are time per iteration, it seems a textbook warmup only getting faster and quickly stabilizing.
I ran it for less long than you did, summing all iteration times it's 87.9s.
Still, it looks like the warmup issue no longer happens so I'll close this.

Happy to learn your arm is getting better :)
```
truffleruby 22.0.0-dev-9bdb2dfc, like ruby 3.0.2, GraalVM EE JVM [x86_64-linux]
7.503300616999695
3.6769749820014113
2.1896049329989182
1.9571757550002076
1.9358344029988075
1.796008379000341
1.4689699789996666
1.4486894959991332
1.3860798539990355
1.3786517770004139
1.3961126489994058
1.3568171040005836
1.3382041750010103
1.3314902189995337
1.3666134039995086
1.2962859620001836
1.3286160269999527
1.3078264270006912
1.2884026780011482
1.2956251220002741
1.310238752001169
1.2865471309996792
1.2894111829991743
1.2758604970003944
1.2745510679997096
1.2775672520001535
1.2771585150003375
1.278548365999086
1.276761439999973
1.28056439500142
1.286910066000928
1.2831522720007342
1.2791569949986297
1.2804920640010096
1.2727734230011265
1.2802479309993942
1.2729694249992463
1.2799983360000624
1.2769419030009885
1.2669015080009558
1.2736655759999849
1.285315922999871
1.2671090309995634
1.2744432069994218
1.277132965000419
1.273861247998866
1.282890888998736
1.266397441000663
1.2681466659996659
1.2767365300005622
1.279843254998923
1.2827898979994643
1.2777610949997324
1.2799708999991708
1.2768370350004261
1.2818740170005185
1.2791409980000026
1.2724017099990306
1.2796547449997888
```

**Closed by eregon** 2022-01-11 11:48 UTC
Labels: performance

**Comment by PragTob** [comment] 2022-01-11 18:30
:+1: 

in case I do another run and I find these again I'll reopen. Thanks!
