### ISSUE TITLE
ArrayIndexOutOfBoundsException while running "rake test"

### ISSUE THREAD

**Issue by thbar** [oracle/truffleruby#1374] opened 2018-06-18 18:40 UTC
I installed truffleruby 1.0.0-rc2 via RVM master today (great work!).

I then cloned https://github.com/thbar/kiba, ran `gem install bundler`, `bundle install`, and finally `bundle exec rake` to launch the default task (test).

I got the following error:

```
spawn_setup: close_others not yet implemented
/Users/thbar/.rvm/gems/truffleruby-1.0.0-rc2/gems/rake-12.2.1/lib/rake/rake_test_loader.rb:5:in `select': Index 5 out of bounds for length 5 (ArrayIndexOutOfBoundsException) (RuntimeError)
	from org.truffleruby.core.array.ObjectArrayMirror.get(ObjectArrayMirror.java:27)
	from org.truffleruby.core.array.ArrayNodes$SelectNode.selectOther(ArrayNodes.java:1877)
	from org.truffleruby.core.array.ArrayNodesFactory$SelectNodeFactory$SelectNodeGen.executeAndSpecialize(ArrayNodesFactory.java:7026)
	from org.truffleruby.core.array.ArrayNodesFactory$SelectNodeFactory$SelectNodeGen.execute(ArrayNodesFactory.java:6987)
	from org.truffleruby.builtins.EnumeratorSizeNode.execute(EnumeratorSizeNode.java:50)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:50)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:262)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:251)
Translated to internal error
	from /Users/thbar/.rvm/gems/truffleruby-1.0.0-rc2/gems/rake-12.2.1/lib/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
Command failed with status (1)
/Users/thbar/.rvm/gems/truffleruby-1.0.0-rc2/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/Users/thbar/.rvm/gems/truffleruby-1.0.0-rc2/bin/truffleruby_executable_hooks:15:in `eval'
/Users/thbar/.rvm/gems/truffleruby-1.0.0-rc2/bin/truffleruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by eregon** [comment] 2018-06-19 15:52
Hello,

I tried those steps but could not reproduce:
```
$ git clone https://github.com/thbar/kiba.git
$ cd kiba
$ gem i bundler
Fetching: bundler-1.16.2.gem (100%)
Successfully installed bundler-1.16.2
1 gem installed

$ bundle install
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Fetching rake 12.3.1
Installing rake 12.3.1
Fetching awesome_print 1.8.0
Installing awesome_print 1.8.0
Using bundler 1.16.2
Using kiba 2.0.0 from source at `.`
Fetching minitest 5.11.3
Installing minitest 5.11.3
Fetching minitest-focus 1.1.2
Installing minitest-focus 1.1.2
Bundle complete! 5 Gemfile dependencies, 6 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ bundle exec rake
Run options: --seed 61485

# Running:

......................................

Fabulous run in 0.005423s, 7006.7652 runs/s, 11432.0906 assertions/s.

38 runs, 62 assertions, 0 failures, 0 errors, 0 skips
```

@thbar Could you try again, and if it fails, copy-paste the seed from minitest?

**Comment by eregon** [comment] 2018-06-19 15:57
Mmh, somehow my environment was messed up and the tests were running on MRI.
Probably due to working too much on Ruby managers :smile: 

But still, I can't reproduce:
```
$ bundle exec rake
Run options: --seed 6490

# Running:

......................................

Fabulous run in 0.680201s, 55.8658 runs/s, 91.1495 assertions/s.

38 runs, 62 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by eregon** [comment] 2018-07-03 14:56
I have tried this again on [TruffleRuby 1.0.0-rc3](https://github.com/oracle/truffleruby/releases/tag/vm-1.0.0-rc3), ran `bundle exec rake` a 100 times and couldn't reproduce.
@thbar Could you try again?

I'm going to close this issue optimistically, but please reopen if you notice the issue again.

**Comment by eregon** [comment] 2019-02-03 22:02
@MaxLap I just saw your comment above.
If you don't mind, could you open a separate issue for it? This seems a problem in Sulong (still fine to report here), and the cause seems unrelated to the original issue.

**Comment by eregon** [comment] 2019-02-04 14:32
Thanks!

**Closed by eregon** 2019-02-04 14:32 UTC
