### ISSUE TITLE
colorls failure: run out of memory on CI

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2309] opened 2021-04-03 11:05 UTC
during invocation of rubocop job:

https://gist.github.com/gogainda/94b24cc195b875183dcad67ddb473ca5

taken from: https://travis-ci.org/github/athityakumar/colorls/jobs/764345233

**Comment by eregon** [comment] 2021-04-06 12:59
Yes, we noticed as well, cc @bjfish.
That message seems to mean the Native Image GC ran out of memory, and we couldn't reproduce it, and a TravisCI run on a fork of the repo also passed.
So I think there is not much to do here besides waiting the next build.
If it happens more often it might be worth to try harder to reproduce it, but so far it's been very difficult to reproduce OOM from TravisCI (maybe they have some special kernel settings so memory overcommitment might be lower than usual or disabled)

Note: please use the `Raw log` from TravisCI when copying, otherwise there are many extra newlines and it's unreadable.

I'll close this because we already have an internal issue tracking this.

**Closed by eregon** 2021-04-06 12:59 UTC
Labels: memory-footprint
