### ISSUE TITLE
yield and block as method argument is not evaluted correctly

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1644] opened 2019-04-05 12:27 UTC
Honestly, I'm not sure how to describe it well but I found this issue in fear gem and TruffleRuby

To reproduce:

```ruby
def evalute(something, inner_values)
  yield(*inner_values, something)
end

def demo(something, inner_values = [], &block)
  evalute(something, inner_values, &block)
end

demo(2) { |x| x * 2 }
```

TruffleRuby 1.0.0 RC14 (wrong)

```
# => [2, 2]
```

MRI 2.6.2 (correct)

```
# => 4
```

MRI is correct in this case

**Comment by eregon** [comment] 2019-04-05 12:52
Just to clarify, this probably means `x` is `[2]` in TruffleRuby and `2` in MRI.

**Comment by aardvark179** [comment] 2019-04-10 12:49
I can't reproduce this on `master`, I think it has been fixed by https://github.com/oracle/truffleruby/commit/0c71a5bf5d2681cf2acbb875fd779c505f6f55b8.

**Closed** 2019-04-10 12:50 UTC
Labels: bug, compatibility
