### ISSUE TITLE
Doesn't have a case for RbStrResizeNodeGen with LLVMPointerImpl Integer=0

### ISSUE THREAD

**Issue by MaxLap** [oracle/truffleruby#1502] opened 2018-12-03 16:20 UTC
I got this failure on Travis during a `bundle install`

```
TypeError: Truffle doesn't have a case for the org.truffleruby.cext.CExtNodesFactory$RbStrResizeNodeFactory$RbStrResizeNodeGen node with values of type  com.oracle.truffle.llvm.runtime.pointer.LLVMPointerImpl java.lang.Integer=0
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/lib/bundler/cli.rb:21:in `internal_raise'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/lib/bundler/cli.rb:21:in `raise'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/lib/bundler/cli.rb:21:in `start'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/bin/bundle:23:in `load'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/bin/bundle:23:in `load'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/bin/bundle:23:in `<main>'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/bin/truffleruby_executable_hooks:24:in `eval'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/bin/truffleruby_executable_hooks:24:in `<main>'
```

https://travis-ci.org/deep-cover/deep-cover/builds/461431558

**Comment by nirvdrum** [comment] 2018-12-04 01:16
I think this is a bad call on `NULL`, but I'll take a look. Thanks for the helpful report.

**Comment by nirvdrum** [comment] 2018-12-06 20:07
Has this been reproducible for you? I haven't been able to induce it yet. I think it might be a spurious issue coming from the OpenSSL extension.

**Comment by MaxLap** [comment] 2018-12-06 21:06
No, I didn't get this issue again

**Comment by nirvdrum** [comment] 2018-12-06 23:08
Okay. If you don't mind, I'm going to deprioritize this one. I'd love to get it fixed, but I think the issue is with the caller of the method and that info isn't available in the backtrace.

**Comment by MaxLap** [comment] 2018-12-06 23:15
No problem, it's unclear how useful those error messages are for you guys, so I posted it just in case.

**Comment by deepj** [comment] 2018-12-07 00:08
@nirvdrum Honestly, sometimes TruffleRuby's errors look a bit cryptic. My favorite is `Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer (IllegalStateException)` 😸

**Comment by nirvdrum** [comment] 2018-12-07 01:45
Unfortunately, it just takes some familiarity with the tools being used. And they're all relatively new, so a lot of people don't have experience. The message here really comes from [Sulong](https://github.com/oracle/graal/tree/master/sulong), which we call into using Truffle's language interop capability.

We should try to make them less cryptic. But often they're the result of a bug or missing functionality that you shouldn't be seeing anyway :-)

**Comment by nirvdrum** [comment] 2018-12-07 01:48
Oh, and posting error logs as issues is helpful. As you might have noticed, the Ruby spec project doesn't have 100% coverage. It's a fantastic test suite and very helpful in developing our runtime, but 3rd party code often finds usages that aren't stressed by the test suite. So, please keep filing issues. I'd be hard-pressed to find a case where they're not helpful. And in in that case, we'd just close it out with an explanation -- no harm done.

**Comment by eregon** [comment] 2020-05-10 10:53
I'd like to close optimistically as I think it doesn't happen anymore.
If it does, please post the full backtrace, which should show where in the C extension the error happens.

**Closed by eregon** 2020-05-10 10:53 UTC
Labels: bug, spurious
