### ISSUE TITLE
ox: error: use of undeclared identifier 'rb_encoding'

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1591] opened 2019-02-23 13:10 UTC
To reproduce:

```
gem install ox
```

Error:
```
Fetching: ox-2.10.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ox:
	ERROR: Failed to build gem native extension.

    current directory: ~/.gem/truffleruby/2.4.4/gems/ox-2.10.0/ext/ox
~/.rubies/truffleruby-1.0.0-rc12/bin/truffleruby -r ./siteconf20190223-36714-1k0ox6t.rb extconf.rb
>>>>> Creating Makefile for truffleruby version 2.4.4 on x86_64-darwin <<<<<
creating Makefile

current directory: ~/.gem/truffleruby/2.4.4/gems/ox-2.10.0/ext/ox
make "DESTDIR=" clean

current directory: ~/.gem/truffleruby/2.4.4/gems/ox-2.10.0/ext/ox
make "DESTDIR="
compiling base64.c
compiling builder.c
compiling cache.c
compiling cache8.c
compiling dump.c
compiling err.c
compiling gen_load.c
compiling hash_load.c
compiling obj_load.c
obj_load.c:65:2: warning: implicit declaration of function 'rb_enc_associate' is invalid in C99 [-Wimplicit-function-declaration]
        rb_enc_associate(rstr, (rb_encoding*)encoding);
        ^
obj_load.c:65:38: error: expected expression
        rb_enc_associate(rstr, (rb_encoding*)encoding);
                                            ^
obj_load.c:65:26: error: use of undeclared identifier 'rb_encoding'; did you mean 'encoding'?
        rb_enc_associate(rstr, (rb_encoding*)encoding);
                                ^~~~~~~~~~~
                                encoding
obj_load.c:58:32: note: 'encoding' declared here
str2sym(const char *str, void *encoding) {
                               ^
obj_load.c:89:6: warning: implicit declaration of function 'rb_enc_associate' is invalid in C99 [-Wimplicit-function-declaration]
            rb_enc_associate(rstr, (rb_encoding*)encoding);
            ^
obj_load.c:89:42: error: expected expression
            rb_enc_associate(rstr, (rb_encoding*)encoding);
                                                ^
obj_load.c:89:30: error: use of undeclared identifier 'rb_encoding'; did you mean 'encoding'?
            rb_enc_associate(rstr, (rb_encoding*)encoding);
                                    ^~~~~~~~~~~
                                    encoding
obj_load.c:77:34: note: 'encoding' declared here
name2var(const char *name, void *encoding) {
                                 ^
2 warnings and 4 errors generated.
make: *** [obj_load.bc] Error 1

make failed, exit code 2

Gem files will remain installed in ~/.gem/truffleruby/2.4.4/gems/ox-2.10.0 for inspection.
```

**Comment by aardvark179** [comment] 2019-02-25 13:40
This seems to be due to `ox`'s extconf.rb` enabling C API features based on the ruby command used to run `extconf.rb`.

**Comment by martijn** [comment] 2020-04-20 10:51
Confirmed, this is an ox issue not a TruffleRuby issue. Ox needs to account for truffleruby in the [extconf.rb](https://github.com/ohler55/ox/blob/develop/ext/ox/extconf.rb#L25). I took a stab at it but there's some other issues cropping up on TruffleRuby that require some more investigation.

**Comment by eregon** [comment] 2020-04-20 11:05
Please use `have_func`/`have_macro`/etc instead of hardcoding Ruby implementation names and versions.
Could you create a new issue for the dumping Range to XML issue?
I'll close this one as third party issue.

**Closed by eregon** 2020-04-20 11:05 UTC

**Comment by gogainda** [comment] 2020-08-29 16:23
@ohler55 was it fix in Ox?

**Comment by eregon** [comment] 2020-08-29 18:42
It seems not yet, I filed an upstream issue: https://github.com/ohler55/ox/issues/246

@martijn Did you have some changes here you could submit to `ox`?

**Comment by martijn** [comment] 2020-08-29 20:33
I haven’t submitted any changes to ox. I suspect the new Truffle Object Model from 20.2 will Alleviate some of the issues I was having so I’ll see if I can make some time to revisit this soon.

**Comment by martijn** [comment] 2020-08-31 08:09
I looked at it this morning, but the Ox code for dumping Ruby objects to XML (where the issues are) is very low level and implementation dependent. This is way out of my comfort zone.

I noticed the CI only tests on MRI and I doubt any of the other implementations mentioned in extconf.rb. currently work 100%.

**Comment by eregon** [comment] 2020-08-31 10:55
Right, I think the first step is to fix https://github.com/ohler55/ox/issues/246. That's worth on its own (even on MRI) just to avoid all these hardcoded and probably wrong in some cases version checks.
@martijn Did you have any changes to address that?

Once that is fixed we can look at issues in TruffleRuby. Before that it does not make sense to me since the gem won't install.

Indeed, I don't think it ever worked on JRuby, at least not since JRuby dropped C extension support (a long time ago already).

**Comment by ohler55** [comment] 2020-08-31 13:41
I'll try to get to the changes this week.

As for JRuby, at one point it did support C extensions. What you are seeing is a file that has not received a lot of attention as the Ruby world changed.

**Comment by eregon** [comment] 2020-08-31 14:00
@ohler55 Thank you :)

**Comment by ohler55** [comment] 2020-09-02 23:59
Just pushed a branch with the changes. Its `mkmf-have`. I wasn't sure how to detect one of the macros. If you have any suggestions for change let me know.

**Comment by eregon** [comment] 2020-09-03 15:07
Thanks, that compiles fine on TruffleRuby:
```
$ cd ext/ox
$ ruby extconf.rb
$ make
compiling base64.c
...
compiling special.c
linking shared-object ox.so
```

For the remaining macro, see https://github.com/ohler55/ox/commit/5cff922c9517689f9927217d955f7c01ad1c9643#r42010463
Could you make a release with that?

**Comment by ohler55** [comment] 2020-09-03 15:26
As soon as CI passes I'll make a release. shortly...

**Comment by eregon** [comment] 2020-11-18 12:06
Ox 2.13.4 was released (https://github.com/ohler55/ox/issues/246), so now it installs and loads fine:
```
~ ∴ ruby -v
truffleruby 21.0.0-dev-2cfd347e, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]
~ ∴ gem i ox
Fetching ox-2.13.4.gem
Building native extensions. This could take a while...
Successfully installed ox-2.13.4
1 gem installed
gem i ox  18.58s user 0.94s system 355% cpu 5.490 total
~ ∴ ruby -rox -e 'p Ox'
Ox
```

**Comment by ohler55** [comment] 2020-11-18 13:05
I should have followed up letting you know CI passed and Ox was released back in September.
