### ISSUE TITLE
Rubygems CI broke yesterday against `truffleruby-head`

### ISSUE THREAD

**Issue by deivid-rodriguez** [oracle/truffleruby#2046] opened 2020-07-10 09:49 UTC
Hi!

We got a notification today informing us that our daily CI against `truffleruby-head` failed yesterday. This is the CI log: https://github.com/rubygems/rubygems/runs/856154343.

Thanks!

**Comment by eregon** [comment] 2020-07-10 13:31
Thanks for reporting!
The issue is:
```
  1) Failure:
TestGemRequire#test_no_kernel_require_in_warn_with_uplevel [/home/runner/work/rubygems/rubygems/test/rubygems/test_require.rb:665]:
Expected /main\.rb:1: warning: uplevel\ntest\n$/ to match "<internal:core> core/kernel.rb:257: warning: uplevel\n" + "test\n".

  2) Failure:
TestGemRequire#test_no_kernel_require_in_Kernel_warn_with_uplevel [/home/runner/work/rubygems/rubygems/test/rubygems/test_require.rb:665]:
Expected /main\.rb:1: warning: uplevel\ntest\n$/ to match "<internal:core> core/kernel.rb:257: warning: uplevel\n" + "test\n".
```

(caused by 68754c65bfaed1f55fd854ae8bccb53da26a0684, fixing #1414).

Maybe we need to adjust the uplevel to be +1 somewhere.

**Comment by eregon** [comment] 2020-07-10 20:02
This needs both a fix in TruffleRuby (coming soon) and in RubyGems: https://github.com/rubygems/rubygems/pull/3810

**Comment by eregon** [comment] 2020-07-11 10:46
5cd679cbcac6501313ca2dc9c9d26d0b884efb7c was merged, so we only need to merge the RubyGems PR now.

**Closed** 2020-07-11 11:03 UTC
Labels: compatibility
